// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package phonecodesmock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v15/authentication/phonecodes"

	"github.com/primandproper/primitives-go/v2/database"
	"github.com/primandproper/primitives-go/v2/tenancy"
)

// Ensure, that StoreMock does implement phonecodes.Store.
// If this is not the case, regenerate this file with moq.
var _ phonecodes.Store = &StoreMock{}

// StoreMock is a mock implementation of phonecodes.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked phonecodes.Store
//		mockedStore := &StoreMock{
//			DeleteForSubjectFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, subjectID string) (int64, error) {
//				panic("mock out the DeleteForSubject method")
//			},
//			IssueFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, request *phonecodes.IssueRequest) (*phonecodes.Issuance, error) {
//				panic("mock out the Issue method")
//			},
//			ListForSubjectFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subjectID string) ([]*phonecodes.Code, error) {
//				panic("mock out the ListForSubject method")
//			},
//			RedeemFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, phoneNumber string, code string) (*phonecodes.Code, bool, error) {
//				panic("mock out the Redeem method")
//			},
//			RevokeForSubjectFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, subjectID string) (int64, error) {
//				panic("mock out the RevokeForSubject method")
//			},
//		}
//
//		// use mockedStore in code that requires phonecodes.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// DeleteForSubjectFunc mocks the DeleteForSubject method.
	DeleteForSubjectFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, subjectID string) (int64, error)

	// IssueFunc mocks the Issue method.
	IssueFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, request *phonecodes.IssueRequest) (*phonecodes.Issuance, error)

	// ListForSubjectFunc mocks the ListForSubject method.
	ListForSubjectFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subjectID string) ([]*phonecodes.Code, error)

	// RedeemFunc mocks the Redeem method.
	RedeemFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, phoneNumber string, code string) (*phonecodes.Code, bool, error)

	// RevokeForSubjectFunc mocks the RevokeForSubject method.
	RevokeForSubjectFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, subjectID string) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteForSubject holds details about calls to the DeleteForSubject method.
		DeleteForSubject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// SubjectID is the subjectID argument value.
			SubjectID string
		}
		// Issue holds details about calls to the Issue method.
		Issue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Request is the request argument value.
			Request *phonecodes.IssueRequest
		}
		// ListForSubject holds details about calls to the ListForSubject method.
		ListForSubject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// SubjectID is the subjectID argument value.
			SubjectID string
		}
		// Redeem holds details about calls to the Redeem method.
		Redeem []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// PhoneNumber is the phoneNumber argument value.
			PhoneNumber string
			// Code is the code argument value.
			Code string
		}
		// RevokeForSubject holds details about calls to the RevokeForSubject method.
		RevokeForSubject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// SubjectID is the subjectID argument value.
			SubjectID string
		}
	}
	lockDeleteForSubject sync.RWMutex
	lockIssue            sync.RWMutex
	lockListForSubject   sync.RWMutex
	lockRedeem           sync.RWMutex
	lockRevokeForSubject sync.RWMutex
}

// DeleteForSubject calls DeleteForSubjectFunc.
func (mock *StoreMock) DeleteForSubject(ctx context.Context, tx database.Tx, scope tenancy.Scope, subjectID string) (int64, error) {
	if mock.DeleteForSubjectFunc == nil {
		panic("StoreMock.DeleteForSubjectFunc: method is nil but Store.DeleteForSubject was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Tx        database.Tx
		Scope     tenancy.Scope
		SubjectID string
	}{
		Ctx:       ctx,
		Tx:        tx,
		Scope:     scope,
		SubjectID: subjectID,
	}
	mock.lockDeleteForSubject.Lock()
	mock.calls.DeleteForSubject = append(mock.calls.DeleteForSubject, callInfo)
	mock.lockDeleteForSubject.Unlock()
	return mock.DeleteForSubjectFunc(ctx, tx, scope, subjectID)
}

// DeleteForSubjectCalls gets all the calls that were made to DeleteForSubject.
// Check the length with:
//
//	len(mockedStore.DeleteForSubjectCalls())
func (mock *StoreMock) DeleteForSubjectCalls() []struct {
	Ctx       context.Context
	Tx        database.Tx
	Scope     tenancy.Scope
	SubjectID string
} {
	var calls []struct {
		Ctx       context.Context
		Tx        database.Tx
		Scope     tenancy.Scope
		SubjectID string
	}
	mock.lockDeleteForSubject.RLock()
	calls = mock.calls.DeleteForSubject
	mock.lockDeleteForSubject.RUnlock()
	return calls
}

// Issue calls IssueFunc.
func (mock *StoreMock) Issue(ctx context.Context, tx database.Tx, scope tenancy.Scope, request *phonecodes.IssueRequest) (*phonecodes.Issuance, error) {
	if mock.IssueFunc == nil {
		panic("StoreMock.IssueFunc: method is nil but Store.Issue was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Tx      database.Tx
		Scope   tenancy.Scope
		Request *phonecodes.IssueRequest
	}{
		Ctx:     ctx,
		Tx:      tx,
		Scope:   scope,
		Request: request,
	}
	mock.lockIssue.Lock()
	mock.calls.Issue = append(mock.calls.Issue, callInfo)
	mock.lockIssue.Unlock()
	return mock.IssueFunc(ctx, tx, scope, request)
}

// IssueCalls gets all the calls that were made to Issue.
// Check the length with:
//
//	len(mockedStore.IssueCalls())
func (mock *StoreMock) IssueCalls() []struct {
	Ctx     context.Context
	Tx      database.Tx
	Scope   tenancy.Scope
	Request *phonecodes.IssueRequest
} {
	var calls []struct {
		Ctx     context.Context
		Tx      database.Tx
		Scope   tenancy.Scope
		Request *phonecodes.IssueRequest
	}
	mock.lockIssue.RLock()
	calls = mock.calls.Issue
	mock.lockIssue.RUnlock()
	return calls
}

// ListForSubject calls ListForSubjectFunc.
func (mock *StoreMock) ListForSubject(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subjectID string) ([]*phonecodes.Code, error) {
	if mock.ListForSubjectFunc == nil {
		panic("StoreMock.ListForSubjectFunc: method is nil but Store.ListForSubject was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Q         database.SQLQueryExecutor
		Scope     tenancy.Scope
		SubjectID string
	}{
		Ctx:       ctx,
		Q:         q,
		Scope:     scope,
		SubjectID: subjectID,
	}
	mock.lockListForSubject.Lock()
	mock.calls.ListForSubject = append(mock.calls.ListForSubject, callInfo)
	mock.lockListForSubject.Unlock()
	return mock.ListForSubjectFunc(ctx, q, scope, subjectID)
}

// ListForSubjectCalls gets all the calls that were made to ListForSubject.
// Check the length with:
//
//	len(mockedStore.ListForSubjectCalls())
func (mock *StoreMock) ListForSubjectCalls() []struct {
	Ctx       context.Context
	Q         database.SQLQueryExecutor
	Scope     tenancy.Scope
	SubjectID string
} {
	var calls []struct {
		Ctx       context.Context
		Q         database.SQLQueryExecutor
		Scope     tenancy.Scope
		SubjectID string
	}
	mock.lockListForSubject.RLock()
	calls = mock.calls.ListForSubject
	mock.lockListForSubject.RUnlock()
	return calls
}

// Redeem calls RedeemFunc.
func (mock *StoreMock) Redeem(ctx context.Context, tx database.Tx, scope tenancy.Scope, phoneNumber string, code string) (*phonecodes.Code, bool, error) {
	if mock.RedeemFunc == nil {
		panic("StoreMock.RedeemFunc: method is nil but Store.Redeem was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Tx          database.Tx
		Scope       tenancy.Scope
		PhoneNumber string
		Code        string
	}{
		Ctx:         ctx,
		Tx:          tx,
		Scope:       scope,
		PhoneNumber: phoneNumber,
		Code:        code,
	}
	mock.lockRedeem.Lock()
	mock.calls.Redeem = append(mock.calls.Redeem, callInfo)
	mock.lockRedeem.Unlock()
	return mock.RedeemFunc(ctx, tx, scope, phoneNumber, code)
}

// RedeemCalls gets all the calls that were made to Redeem.
// Check the length with:
//
//	len(mockedStore.RedeemCalls())
func (mock *StoreMock) RedeemCalls() []struct {
	Ctx         context.Context
	Tx          database.Tx
	Scope       tenancy.Scope
	PhoneNumber string
	Code        string
} {
	var calls []struct {
		Ctx         context.Context
		Tx          database.Tx
		Scope       tenancy.Scope
		PhoneNumber string
		Code        string
	}
	mock.lockRedeem.RLock()
	calls = mock.calls.Redeem
	mock.lockRedeem.RUnlock()
	return calls
}

// RevokeForSubject calls RevokeForSubjectFunc.
func (mock *StoreMock) RevokeForSubject(ctx context.Context, tx database.Tx, scope tenancy.Scope, subjectID string) (int64, error) {
	if mock.RevokeForSubjectFunc == nil {
		panic("StoreMock.RevokeForSubjectFunc: method is nil but Store.RevokeForSubject was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Tx        database.Tx
		Scope     tenancy.Scope
		SubjectID string
	}{
		Ctx:       ctx,
		Tx:        tx,
		Scope:     scope,
		SubjectID: subjectID,
	}
	mock.lockRevokeForSubject.Lock()
	mock.calls.RevokeForSubject = append(mock.calls.RevokeForSubject, callInfo)
	mock.lockRevokeForSubject.Unlock()
	return mock.RevokeForSubjectFunc(ctx, tx, scope, subjectID)
}

// RevokeForSubjectCalls gets all the calls that were made to RevokeForSubject.
// Check the length with:
//
//	len(mockedStore.RevokeForSubjectCalls())
func (mock *StoreMock) RevokeForSubjectCalls() []struct {
	Ctx       context.Context
	Tx        database.Tx
	Scope     tenancy.Scope
	SubjectID string
} {
	var calls []struct {
		Ctx       context.Context
		Tx        database.Tx
		Scope     tenancy.Scope
		SubjectID string
	}
	mock.lockRevokeForSubject.RLock()
	calls = mock.calls.RevokeForSubject
	mock.lockRevokeForSubject.RUnlock()
	return calls
}
