// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package registrymock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v14/uploads/registry"

	"github.com/primandproper/primitives-go/database"
	"github.com/primandproper/primitives-go/filtering"
	"github.com/primandproper/primitives-go/tenancy"
)

// Ensure, that StoreMock does implement registry.Store.
// If this is not the case, regenerate this file with moq.
var _ registry.Store = &StoreMock{}

// StoreMock is a mock implementation of registry.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked registry.Store
//		mockedStore := &StoreMock{
//			ArchiveObjectFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, objectID string) error {
//				panic("mock out the ArchiveObject method")
//			},
//			GetObjectFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, objectID string) (*registry.Object, error) {
//				panic("mock out the GetObject method")
//			},
//			GetObjectByKeyFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, key string) (*registry.Object, error) {
//				panic("mock out the GetObjectByKey method")
//			},
//			ListObjectsFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error) {
//				panic("mock out the ListObjects method")
//			},
//			ListObjectsByOwnerFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, ownerID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error) {
//				panic("mock out the ListObjectsByOwner method")
//			},
//			ListObjectsBySubjectFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subject registry.Subject, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error) {
//				panic("mock out the ListObjectsBySubject method")
//			},
//			RecordObjectFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, object *registry.Object) error {
//				panic("mock out the RecordObject method")
//			},
//		}
//
//		// use mockedStore in code that requires registry.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// ArchiveObjectFunc mocks the ArchiveObject method.
	ArchiveObjectFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, objectID string) error

	// GetObjectFunc mocks the GetObject method.
	GetObjectFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, objectID string) (*registry.Object, error)

	// GetObjectByKeyFunc mocks the GetObjectByKey method.
	GetObjectByKeyFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, key string) (*registry.Object, error)

	// ListObjectsFunc mocks the ListObjects method.
	ListObjectsFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error)

	// ListObjectsByOwnerFunc mocks the ListObjectsByOwner method.
	ListObjectsByOwnerFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, ownerID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error)

	// ListObjectsBySubjectFunc mocks the ListObjectsBySubject method.
	ListObjectsBySubjectFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subject registry.Subject, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error)

	// RecordObjectFunc mocks the RecordObject method.
	RecordObjectFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, object *registry.Object) error

	// calls tracks calls to the methods.
	calls struct {
		// ArchiveObject holds details about calls to the ArchiveObject method.
		ArchiveObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// ObjectID is the objectID argument value.
			ObjectID string
		}
		// GetObject holds details about calls to the GetObject method.
		GetObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// ObjectID is the objectID argument value.
			ObjectID string
		}
		// GetObjectByKey holds details about calls to the GetObjectByKey method.
		GetObjectByKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Key is the key argument value.
			Key string
		}
		// ListObjects holds details about calls to the ListObjects method.
		ListObjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// ListObjectsByOwner holds details about calls to the ListObjectsByOwner method.
		ListObjectsByOwner []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// OwnerID is the ownerID argument value.
			OwnerID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// ListObjectsBySubject holds details about calls to the ListObjectsBySubject method.
		ListObjectsBySubject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Subject is the subject argument value.
			Subject registry.Subject
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// RecordObject holds details about calls to the RecordObject method.
		RecordObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Object is the object argument value.
			Object *registry.Object
		}
	}
	lockArchiveObject        sync.RWMutex
	lockGetObject            sync.RWMutex
	lockGetObjectByKey       sync.RWMutex
	lockListObjects          sync.RWMutex
	lockListObjectsByOwner   sync.RWMutex
	lockListObjectsBySubject sync.RWMutex
	lockRecordObject         sync.RWMutex
}

// ArchiveObject calls ArchiveObjectFunc.
func (mock *StoreMock) ArchiveObject(ctx context.Context, tx database.Tx, scope tenancy.Scope, objectID string) error {
	if mock.ArchiveObjectFunc == nil {
		panic("StoreMock.ArchiveObjectFunc: method is nil but Store.ArchiveObject was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Tx       database.Tx
		Scope    tenancy.Scope
		ObjectID string
	}{
		Ctx:      ctx,
		Tx:       tx,
		Scope:    scope,
		ObjectID: objectID,
	}
	mock.lockArchiveObject.Lock()
	mock.calls.ArchiveObject = append(mock.calls.ArchiveObject, callInfo)
	mock.lockArchiveObject.Unlock()
	return mock.ArchiveObjectFunc(ctx, tx, scope, objectID)
}

// ArchiveObjectCalls gets all the calls that were made to ArchiveObject.
// Check the length with:
//
//	len(mockedStore.ArchiveObjectCalls())
func (mock *StoreMock) ArchiveObjectCalls() []struct {
	Ctx      context.Context
	Tx       database.Tx
	Scope    tenancy.Scope
	ObjectID string
} {
	var calls []struct {
		Ctx      context.Context
		Tx       database.Tx
		Scope    tenancy.Scope
		ObjectID string
	}
	mock.lockArchiveObject.RLock()
	calls = mock.calls.ArchiveObject
	mock.lockArchiveObject.RUnlock()
	return calls
}

// GetObject calls GetObjectFunc.
func (mock *StoreMock) GetObject(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, objectID string) (*registry.Object, error) {
	if mock.GetObjectFunc == nil {
		panic("StoreMock.GetObjectFunc: method is nil but Store.GetObject was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Q        database.SQLQueryExecutor
		Scope    tenancy.Scope
		ObjectID string
	}{
		Ctx:      ctx,
		Q:        q,
		Scope:    scope,
		ObjectID: objectID,
	}
	mock.lockGetObject.Lock()
	mock.calls.GetObject = append(mock.calls.GetObject, callInfo)
	mock.lockGetObject.Unlock()
	return mock.GetObjectFunc(ctx, q, scope, objectID)
}

// GetObjectCalls gets all the calls that were made to GetObject.
// Check the length with:
//
//	len(mockedStore.GetObjectCalls())
func (mock *StoreMock) GetObjectCalls() []struct {
	Ctx      context.Context
	Q        database.SQLQueryExecutor
	Scope    tenancy.Scope
	ObjectID string
} {
	var calls []struct {
		Ctx      context.Context
		Q        database.SQLQueryExecutor
		Scope    tenancy.Scope
		ObjectID string
	}
	mock.lockGetObject.RLock()
	calls = mock.calls.GetObject
	mock.lockGetObject.RUnlock()
	return calls
}

// GetObjectByKey calls GetObjectByKeyFunc.
func (mock *StoreMock) GetObjectByKey(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, key string) (*registry.Object, error) {
	if mock.GetObjectByKeyFunc == nil {
		panic("StoreMock.GetObjectByKeyFunc: method is nil but Store.GetObjectByKey was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Q     database.SQLQueryExecutor
		Scope tenancy.Scope
		Key   string
	}{
		Ctx:   ctx,
		Q:     q,
		Scope: scope,
		Key:   key,
	}
	mock.lockGetObjectByKey.Lock()
	mock.calls.GetObjectByKey = append(mock.calls.GetObjectByKey, callInfo)
	mock.lockGetObjectByKey.Unlock()
	return mock.GetObjectByKeyFunc(ctx, q, scope, key)
}

// GetObjectByKeyCalls gets all the calls that were made to GetObjectByKey.
// Check the length with:
//
//	len(mockedStore.GetObjectByKeyCalls())
func (mock *StoreMock) GetObjectByKeyCalls() []struct {
	Ctx   context.Context
	Q     database.SQLQueryExecutor
	Scope tenancy.Scope
	Key   string
} {
	var calls []struct {
		Ctx   context.Context
		Q     database.SQLQueryExecutor
		Scope tenancy.Scope
		Key   string
	}
	mock.lockGetObjectByKey.RLock()
	calls = mock.calls.GetObjectByKey
	mock.lockGetObjectByKey.RUnlock()
	return calls
}

// ListObjects calls ListObjectsFunc.
func (mock *StoreMock) ListObjects(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error) {
	if mock.ListObjectsFunc == nil {
		panic("StoreMock.ListObjectsFunc: method is nil but Store.ListObjects was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Q      database.SQLQueryExecutor
		Scope  tenancy.Scope
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		Q:      q,
		Scope:  scope,
		Filter: filter,
	}
	mock.lockListObjects.Lock()
	mock.calls.ListObjects = append(mock.calls.ListObjects, callInfo)
	mock.lockListObjects.Unlock()
	return mock.ListObjectsFunc(ctx, q, scope, filter)
}

// ListObjectsCalls gets all the calls that were made to ListObjects.
// Check the length with:
//
//	len(mockedStore.ListObjectsCalls())
func (mock *StoreMock) ListObjectsCalls() []struct {
	Ctx    context.Context
	Q      database.SQLQueryExecutor
	Scope  tenancy.Scope
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		Q      database.SQLQueryExecutor
		Scope  tenancy.Scope
		Filter *filtering.QueryFilter
	}
	mock.lockListObjects.RLock()
	calls = mock.calls.ListObjects
	mock.lockListObjects.RUnlock()
	return calls
}

// ListObjectsByOwner calls ListObjectsByOwnerFunc.
func (mock *StoreMock) ListObjectsByOwner(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, ownerID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error) {
	if mock.ListObjectsByOwnerFunc == nil {
		panic("StoreMock.ListObjectsByOwnerFunc: method is nil but Store.ListObjectsByOwner was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Q       database.SQLQueryExecutor
		Scope   tenancy.Scope
		OwnerID string
		Filter  *filtering.QueryFilter
	}{
		Ctx:     ctx,
		Q:       q,
		Scope:   scope,
		OwnerID: ownerID,
		Filter:  filter,
	}
	mock.lockListObjectsByOwner.Lock()
	mock.calls.ListObjectsByOwner = append(mock.calls.ListObjectsByOwner, callInfo)
	mock.lockListObjectsByOwner.Unlock()
	return mock.ListObjectsByOwnerFunc(ctx, q, scope, ownerID, filter)
}

// ListObjectsByOwnerCalls gets all the calls that were made to ListObjectsByOwner.
// Check the length with:
//
//	len(mockedStore.ListObjectsByOwnerCalls())
func (mock *StoreMock) ListObjectsByOwnerCalls() []struct {
	Ctx     context.Context
	Q       database.SQLQueryExecutor
	Scope   tenancy.Scope
	OwnerID string
	Filter  *filtering.QueryFilter
} {
	var calls []struct {
		Ctx     context.Context
		Q       database.SQLQueryExecutor
		Scope   tenancy.Scope
		OwnerID string
		Filter  *filtering.QueryFilter
	}
	mock.lockListObjectsByOwner.RLock()
	calls = mock.calls.ListObjectsByOwner
	mock.lockListObjectsByOwner.RUnlock()
	return calls
}

// ListObjectsBySubject calls ListObjectsBySubjectFunc.
func (mock *StoreMock) ListObjectsBySubject(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subject registry.Subject, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[registry.Object], error) {
	if mock.ListObjectsBySubjectFunc == nil {
		panic("StoreMock.ListObjectsBySubjectFunc: method is nil but Store.ListObjectsBySubject was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Q       database.SQLQueryExecutor
		Scope   tenancy.Scope
		Subject registry.Subject
		Filter  *filtering.QueryFilter
	}{
		Ctx:     ctx,
		Q:       q,
		Scope:   scope,
		Subject: subject,
		Filter:  filter,
	}
	mock.lockListObjectsBySubject.Lock()
	mock.calls.ListObjectsBySubject = append(mock.calls.ListObjectsBySubject, callInfo)
	mock.lockListObjectsBySubject.Unlock()
	return mock.ListObjectsBySubjectFunc(ctx, q, scope, subject, filter)
}

// ListObjectsBySubjectCalls gets all the calls that were made to ListObjectsBySubject.
// Check the length with:
//
//	len(mockedStore.ListObjectsBySubjectCalls())
func (mock *StoreMock) ListObjectsBySubjectCalls() []struct {
	Ctx     context.Context
	Q       database.SQLQueryExecutor
	Scope   tenancy.Scope
	Subject registry.Subject
	Filter  *filtering.QueryFilter
} {
	var calls []struct {
		Ctx     context.Context
		Q       database.SQLQueryExecutor
		Scope   tenancy.Scope
		Subject registry.Subject
		Filter  *filtering.QueryFilter
	}
	mock.lockListObjectsBySubject.RLock()
	calls = mock.calls.ListObjectsBySubject
	mock.lockListObjectsBySubject.RUnlock()
	return calls
}

// RecordObject calls RecordObjectFunc.
func (mock *StoreMock) RecordObject(ctx context.Context, tx database.Tx, scope tenancy.Scope, object *registry.Object) error {
	if mock.RecordObjectFunc == nil {
		panic("StoreMock.RecordObjectFunc: method is nil but Store.RecordObject was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Tx     database.Tx
		Scope  tenancy.Scope
		Object *registry.Object
	}{
		Ctx:    ctx,
		Tx:     tx,
		Scope:  scope,
		Object: object,
	}
	mock.lockRecordObject.Lock()
	mock.calls.RecordObject = append(mock.calls.RecordObject, callInfo)
	mock.lockRecordObject.Unlock()
	return mock.RecordObjectFunc(ctx, tx, scope, object)
}

// RecordObjectCalls gets all the calls that were made to RecordObject.
// Check the length with:
//
//	len(mockedStore.RecordObjectCalls())
func (mock *StoreMock) RecordObjectCalls() []struct {
	Ctx    context.Context
	Tx     database.Tx
	Scope  tenancy.Scope
	Object *registry.Object
} {
	var calls []struct {
		Ctx    context.Context
		Tx     database.Tx
		Scope  tenancy.Scope
		Object *registry.Object
	}
	mock.lockRecordObject.RLock()
	calls = mock.calls.RecordObject
	mock.lockRecordObject.RUnlock()
	return calls
}
