-- Code generated by github.com/primandproper/platform-go/v14/shredding/internal/queriesgen. DO NOT EDIT.

-- name: GetSubjectKey :one
SELECT
	shredding_subject_keys.subject_type,
	shredding_subject_keys.subject_id,
	shredding_subject_keys.wrapped_key,
	shredding_subject_keys.created_at,
	shredding_subject_keys.shredded_at
FROM shredding_subject_keys
WHERE shredding_subject_keys.subject_type = sqlc.arg(subject_type)
	AND shredding_subject_keys.subject_id = sqlc.arg(subject_id);

-- name: InsertSubjectKey :execrows
INSERT INTO shredding_subject_keys (
	subject_type,
	subject_id,
	wrapped_key,
	created_at,
	shredded_at
) VALUES (
	sqlc.arg(subject_type),
	sqlc.arg(subject_id),
	sqlc.narg(wrapped_key),
	sqlc.arg(created_at),
	sqlc.narg(shredded_at)
)
ON CONFLICT (subject_type, subject_id) DO NOTHING;

-- name: ShredSubjectKey :execrows
UPDATE shredding_subject_keys SET
	wrapped_key = sqlc.narg(wrapped_key),
	shredded_at = sqlc.narg(shredded_at),
	last_updated_at = sqlc.narg(last_updated_at)
WHERE subject_type = sqlc.arg(subject_type)
	AND subject_id = sqlc.arg(subject_id)
	AND shredded_at IS NULL;
