// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package recoverycodedb

import (
	"context"
	"strings"
	"time"

	"github.com/primandproper/primitives-go/v2/tenancy"
)

const countUnspentRecoveryCodesPostgreSQL = `SELECT COUNT(*)
FROM {{prefix}}signin_recovery_codes
WHERE {{prefix}}signin_recovery_codes.scope = $1
	AND {{prefix}}signin_recovery_codes.user_id = $2
	AND {{prefix}}signin_recovery_codes.used_at IS NULL`

const deleteRecoveryCodesForUserPostgreSQL = `DELETE FROM {{prefix}}signin_recovery_codes
WHERE scope = $1
	AND user_id = $2`

const insertRecoveryCodePostgreSQL = `
INSERT INTO {{prefix}}signin_recovery_codes (
	scope,
	user_id,
	hash,
	issued_at
) VALUES (
	$1,
	$2,
	$3,
	$4
)`

const listRecoveryCodesForUserPostgreSQL = `SELECT
	{{prefix}}signin_recovery_codes.scope,
	{{prefix}}signin_recovery_codes.user_id,
	{{prefix}}signin_recovery_codes.issued_at,
	{{prefix}}signin_recovery_codes.used_at
FROM {{prefix}}signin_recovery_codes
WHERE {{prefix}}signin_recovery_codes.scope = $1
	AND {{prefix}}signin_recovery_codes.user_id = $2
ORDER BY {{prefix}}signin_recovery_codes.issued_at ASC`

const recoveryCodeUnspentPostgreSQL = `SELECT EXISTS (
	SELECT 1
	FROM {{prefix}}signin_recovery_codes
	WHERE {{prefix}}signin_recovery_codes.scope = $1
		AND {{prefix}}signin_recovery_codes.user_id = $2
		AND {{prefix}}signin_recovery_codes.hash = $3
		AND {{prefix}}signin_recovery_codes.used_at IS NULL
)`

const spendRecoveryCodePostgreSQL = `UPDATE {{prefix}}signin_recovery_codes SET
	used_at = $1
WHERE scope = $2
	AND user_id = $3
	AND hash = $4
	AND used_at IS NULL`

// postgresqlQueries answers every query in Querier against postgresql.
type postgresqlQueries struct {
	countUnspentRecoveryCodes  string
	deleteRecoveryCodesForUser string
	insertRecoveryCode         string
	listRecoveryCodesForUser   string
	recoveryCodeUnspent        string
	spendRecoveryCode          string
}

// newPostgreSQL returns the postgresql querier with prefix substituted into every
// table name the analyzer identified.
func newPostgreSQL(prefix string) *postgresqlQueries {
	return &postgresqlQueries{
		countUnspentRecoveryCodes:  strings.ReplaceAll(countUnspentRecoveryCodesPostgreSQL, prefixMarker, prefix),
		deleteRecoveryCodesForUser: strings.ReplaceAll(deleteRecoveryCodesForUserPostgreSQL, prefixMarker, prefix),
		insertRecoveryCode:         strings.ReplaceAll(insertRecoveryCodePostgreSQL, prefixMarker, prefix),
		listRecoveryCodesForUser:   strings.ReplaceAll(listRecoveryCodesForUserPostgreSQL, prefixMarker, prefix),
		recoveryCodeUnspent:        strings.ReplaceAll(recoveryCodeUnspentPostgreSQL, prefixMarker, prefix),
		spendRecoveryCode:          strings.ReplaceAll(spendRecoveryCodePostgreSQL, prefixMarker, prefix),
	}
}

// CountUnspentRecoveryCodes runs the :one query against postgresql.
func (q *postgresqlQueries) CountUnspentRecoveryCodes(ctx context.Context, db DBTX, arg CountUnspentRecoveryCodesParams) (CountUnspentRecoveryCodesRow, error) {
	row := db.QueryRowContext(ctx, q.countUnspentRecoveryCodes,
		arg.Scope,
		arg.UserID,
	)

	var i CountUnspentRecoveryCodesRow

	err := row.Scan(
		&i.Count,
	)

	return i, err
}

// DeleteRecoveryCodesForUser runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteRecoveryCodesForUser(ctx context.Context, db DBTX, arg DeleteRecoveryCodesForUserParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteRecoveryCodesForUser,
		arg.Scope,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// InsertRecoveryCode runs the :exec query against postgresql.
func (q *postgresqlQueries) InsertRecoveryCode(ctx context.Context, db DBTX, arg InsertRecoveryCodeParams) error {
	_, err := db.ExecContext(ctx, q.insertRecoveryCode,
		arg.Scope,
		arg.UserID,
		arg.Hash,
		arg.IssuedAt,
	)

	return err
}

// ListRecoveryCodesForUser runs the :many query against postgresql.
func (q *postgresqlQueries) ListRecoveryCodesForUser(ctx context.Context, db DBTX, arg ListRecoveryCodesForUserParams) ([]ListRecoveryCodesForUserRow, error) {
	rows, err := db.QueryContext(ctx, q.listRecoveryCodesForUser,
		arg.Scope,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRecoveryCodesForUserRow

	for rows.Next() {
		var i ListRecoveryCodesForUserRow

		if err := rows.Scan(
			&i.Scope,
			&i.UserID,
			&i.IssuedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// RecoveryCodeUnspent runs the :one query against postgresql.
func (q *postgresqlQueries) RecoveryCodeUnspent(ctx context.Context, db DBTX, arg RecoveryCodeUnspentParams) (RecoveryCodeUnspentRow, error) {
	row := db.QueryRowContext(ctx, q.recoveryCodeUnspent,
		arg.Scope,
		arg.UserID,
		arg.Hash,
	)

	var i RecoveryCodeUnspentRow

	err := row.Scan(
		&i.Exists,
	)

	return i, err
}

// SpendRecoveryCode runs the :execrows query against postgresql.
func (q *postgresqlQueries) SpendRecoveryCode(ctx context.Context, db DBTX, arg SpendRecoveryCodeParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.spendRecoveryCode,
		arg.UsedAt,
		arg.Scope,
		arg.UserID,
		arg.Hash,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		Scope  tenancy.Scope
		UserID string
	}(CountUnspentRecoveryCodesParams{})
	_ = struct {
		Count int64
	}(CountUnspentRecoveryCodesRow{})
	_ = struct {
		Scope  tenancy.Scope
		UserID string
	}(DeleteRecoveryCodesForUserParams{})
	_ = struct {
		Scope    tenancy.Scope
		UserID   string
		Hash     string
		IssuedAt time.Time
	}(InsertRecoveryCodeParams{})
	_ = struct {
		Scope  tenancy.Scope
		UserID string
	}(ListRecoveryCodesForUserParams{})
	_ = struct {
		Scope    tenancy.Scope
		UserID   string
		IssuedAt time.Time
		UsedAt   *time.Time
	}(ListRecoveryCodesForUserRow{})
	_ = struct {
		Scope  tenancy.Scope
		UserID string
		Hash   string
	}(RecoveryCodeUnspentParams{})
	_ = struct {
		Exists bool
	}(RecoveryCodeUnspentRow{})
	_ = struct {
		UsedAt *time.Time
		Scope  tenancy.Scope
		UserID string
		Hash   string
	}(SpendRecoveryCodeParams{})
)
