-- Code generated by github.com/primandproper/platform-go/v14/workqueue/internal/queriesgen. DO NOT EDIT.

-- name: EnqueueItem :exec
INSERT INTO work_queue_items (
	queue_name,
	item_key,
	priority,
	attempts,
	enqueued_at,
	available_at,
	lease_until
) VALUES (
	sqlc.arg(queue_name),
	sqlc.arg(item_key),
	sqlc.arg(priority),
	0,
	CURRENT_TIMESTAMP(6),
	(CURRENT_TIMESTAMP(6) + INTERVAL sqlc.arg(delay_microseconds) MICROSECOND),
	'1970-01-01 00:00:00'
)
ON DUPLICATE KEY UPDATE
	priority = GREATEST(work_queue_items.priority, VALUES(priority)),
	available_at = CASE
		WHEN work_queue_items.completed_at IS NULL THEN LEAST(work_queue_items.available_at, VALUES(available_at))
		ELSE VALUES(available_at)
	END,
	enqueued_at = CASE
		WHEN work_queue_items.completed_at IS NULL THEN work_queue_items.enqueued_at
		ELSE VALUES(enqueued_at)
	END,
	attempts = CASE
		WHEN work_queue_items.completed_at IS NULL THEN work_queue_items.attempts
		ELSE 0
	END,
	last_error = CASE
		WHEN work_queue_items.completed_at IS NULL THEN work_queue_items.last_error
		ELSE NULL
	END,
	completed_at = NULL;

-- name: SelectDueItems :many
SELECT
	work_queue_items.item_key,
	(work_queue_items.lease_until > '1970-01-01 00:00:00') AS reclaimed
FROM work_queue_items
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NULL
	AND work_queue_items.lease_until <= CURRENT_TIMESTAMP(6)
	AND work_queue_items.available_at <= CURRENT_TIMESTAMP(6)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR work_queue_items.attempts < sqlc.arg(attempt_ceiling))
ORDER BY work_queue_items.priority DESC, work_queue_items.available_at, work_queue_items.item_key
LIMIT ?
FOR UPDATE SKIP LOCKED;

-- name: LeaseItems :execrows
UPDATE work_queue_items SET
	lease_until = (CURRENT_TIMESTAMP(6) + INTERVAL sqlc.arg(lease_microseconds) MICROSECOND),
	leased_by = sqlc.arg(leased_by),
	attempts = work_queue_items.attempts + 1
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NULL
	AND work_queue_items.lease_until <= CURRENT_TIMESTAMP(6)
	AND work_queue_items.available_at <= CURRENT_TIMESTAMP(6)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR work_queue_items.attempts < sqlc.arg(attempt_ceiling))
	AND work_queue_items.item_key IN (sqlc.slice(item_keys));

-- name: FetchLeasedItems :many
SELECT
	work_queue_items.item_key,
	work_queue_items.priority,
	work_queue_items.attempts
FROM work_queue_items
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.leased_by = sqlc.arg(leased_by)
ORDER BY work_queue_items.priority DESC, work_queue_items.available_at, work_queue_items.item_key;

-- name: ExtendItems :execrows
UPDATE work_queue_items SET
	lease_until = GREATEST(work_queue_items.lease_until, (CURRENT_TIMESTAMP(6) + INTERVAL sqlc.arg(lease_microseconds) MICROSECOND))
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NULL
	AND work_queue_items.leased_by = sqlc.arg(leased_by)
	AND work_queue_items.item_key IN (sqlc.slice(item_keys))
ORDER BY work_queue_items.item_key;

-- name: CountHeldItems :one
SELECT COUNT(*) AS held
FROM work_queue_items
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NULL
	AND work_queue_items.leased_by = sqlc.arg(leased_by)
	AND work_queue_items.item_key IN (sqlc.slice(item_keys));

-- name: CompleteItems :execrows
UPDATE work_queue_items SET
	completed_at = CURRENT_TIMESTAMP(6),
	lease_until = '1970-01-01 00:00:00',
	leased_by = NULL,
	last_error = NULL
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.leased_by = sqlc.arg(leased_by)
	AND work_queue_items.item_key IN (sqlc.slice(item_keys))
ORDER BY work_queue_items.item_key;

-- name: ReleaseItems :execrows
UPDATE work_queue_items SET
	lease_until = '1970-01-01 00:00:00',
	leased_by = NULL,
	available_at = (CURRENT_TIMESTAMP(6) + INTERVAL sqlc.arg(delay_microseconds) MICROSECOND),
	last_error = sqlc.narg(last_error)
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NULL
	AND work_queue_items.leased_by = sqlc.arg(leased_by)
	AND work_queue_items.item_key IN (sqlc.slice(item_keys))
ORDER BY work_queue_items.item_key;

-- name: RemoveItems :execrows
DELETE FROM work_queue_items
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.item_key IN (sqlc.slice(item_keys))
ORDER BY work_queue_items.item_key;

-- name: RequeueItems :execrows
UPDATE work_queue_items SET
	attempts = 0,
	available_at = CURRENT_TIMESTAMP(6)
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NULL
	AND work_queue_items.item_key IN (sqlc.slice(item_keys))
ORDER BY work_queue_items.item_key;

-- name: SelectReapableItems :many
SELECT work_queue_items.item_key
FROM work_queue_items
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NOT NULL
	AND work_queue_items.completed_at < (CURRENT_TIMESTAMP(6) - INTERVAL sqlc.arg(retention_microseconds) MICROSECOND)
ORDER BY work_queue_items.completed_at
LIMIT ?
FOR UPDATE SKIP LOCKED;

-- name: DeleteReapedItems :execrows
DELETE FROM work_queue_items
WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NOT NULL
	AND work_queue_items.completed_at < (CURRENT_TIMESTAMP(6) - INTERVAL sqlc.arg(retention_microseconds) MICROSECOND)
	AND work_queue_items.item_key IN (sqlc.slice(item_keys))
ORDER BY work_queue_items.item_key;

-- name: ReadQueueStats :one
SELECT
	CAST(COALESCE(SUM(CASE WHEN work_queue_items.completed_at IS NULL THEN 1 ELSE 0 END), 0) AS SIGNED) AS pending,
	CAST(COALESCE(SUM(CASE WHEN work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NULL
	AND work_queue_items.lease_until <= CURRENT_TIMESTAMP(6)
	AND work_queue_items.available_at <= CURRENT_TIMESTAMP(6)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR work_queue_items.attempts < sqlc.arg(attempt_ceiling)) THEN 1 ELSE 0 END), 0) AS SIGNED) AS ready,
	CAST(COALESCE(SUM(CASE WHEN work_queue_items.completed_at IS NULL AND work_queue_items.lease_until > CURRENT_TIMESTAMP(6) THEN 1 ELSE 0 END), 0) AS SIGNED) AS leased,
	CAST(COALESCE(SUM(CASE WHEN work_queue_items.completed_at IS NULL AND sqlc.arg(attempt_ceiling) > 0
		AND work_queue_items.attempts >= sqlc.arg(attempt_ceiling) THEN 1 ELSE 0 END), 0) AS SIGNED) AS stalled,
	CAST(COALESCE(SUM(CASE WHEN work_queue_items.completed_at IS NOT NULL THEN 1 ELSE 0 END), 0) AS SIGNED) AS completed,
	CAST(COALESCE(TIMESTAMPDIFF(MICROSECOND, MIN(CASE WHEN work_queue_items.queue_name = sqlc.arg(queue_name)
	AND work_queue_items.completed_at IS NULL
	AND work_queue_items.lease_until <= CURRENT_TIMESTAMP(6)
	AND work_queue_items.available_at <= CURRENT_TIMESTAMP(6)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR work_queue_items.attempts < sqlc.arg(attempt_ceiling)) THEN work_queue_items.available_at END), CURRENT_TIMESTAMP(6)), 0) AS SIGNED) AS oldest_ready_microseconds
FROM work_queue_items
WHERE work_queue_items.queue_name = sqlc.arg(queue_name);
