-- Code generated by github.com/primandproper/platform-go/v14/workqueue/internal/queriesgen. DO NOT EDIT.

-- name: EnqueueItems :exec
INSERT INTO work_queue_items (
	queue_name,
	item_key,
	priority,
	attempts,
	enqueued_at,
	available_at,
	lease_until
)
SELECT
	sqlc.arg(queue_name),
	keys.item_key,
	priorities.priority,
	0,
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP + (delays.delay_microseconds * INTERVAL '1 microsecond'),
	TIMESTAMPTZ 'epoch'
FROM unnest(sqlc.arg(item_keys)::text[]) WITH ORDINALITY AS keys(item_key, ordinal)
	JOIN unnest(sqlc.arg(priorities)::int[]) WITH ORDINALITY AS priorities(priority, ordinal) USING (ordinal)
	JOIN unnest(sqlc.arg(delay_microseconds)::bigint[]) WITH ORDINALITY AS delays(delay_microseconds, ordinal) USING (ordinal)
ORDER BY keys.item_key
ON CONFLICT (queue_name, item_key) DO UPDATE SET
	priority = GREATEST(work_queue_items.priority, excluded.priority),
	available_at = CASE
		WHEN work_queue_items.completed_at IS NULL THEN LEAST(work_queue_items.available_at, excluded.available_at)
		ELSE excluded.available_at
	END,
	enqueued_at = CASE
		WHEN work_queue_items.completed_at IS NULL THEN work_queue_items.enqueued_at
		ELSE excluded.enqueued_at
	END,
	attempts = CASE
		WHEN work_queue_items.completed_at IS NULL THEN work_queue_items.attempts
		ELSE 0
	END,
	last_error = CASE
		WHEN work_queue_items.completed_at IS NULL THEN work_queue_items.last_error
		ELSE NULL
	END,
	completed_at = NULL;

-- name: ClaimDueItems :many
WITH due AS (
	SELECT
		work_queue_items.queue_name,
		work_queue_items.item_key,
		work_queue_items.lease_until AS prior_lease
	FROM work_queue_items
	WHERE work_queue_items.queue_name = sqlc.arg(queue_name) AND work_queue_items.completed_at IS NULL AND work_queue_items.lease_until <= CURRENT_TIMESTAMP AND work_queue_items.available_at <= CURRENT_TIMESTAMP AND (sqlc.arg(attempt_ceiling)::int <= 0 OR work_queue_items.attempts < sqlc.arg(attempt_ceiling)::int)
	ORDER BY work_queue_items.priority DESC, work_queue_items.available_at, work_queue_items.item_key
	LIMIT sqlc.arg(claim_limit)::int
	FOR UPDATE SKIP LOCKED
)
UPDATE work_queue_items SET
	lease_until = CURRENT_TIMESTAMP + (sqlc.arg(lease_microseconds)::bigint * INTERVAL '1 microsecond'),
	leased_by = sqlc.arg(leased_by),
	attempts = work_queue_items.attempts + 1
FROM due
WHERE work_queue_items.queue_name = due.queue_name
	AND work_queue_items.item_key = due.item_key
RETURNING
	work_queue_items.item_key,
	work_queue_items.priority,
	work_queue_items.attempts,
	(due.prior_lease > TIMESTAMPTZ 'epoch') AS reclaimed;

-- name: CompleteItems :execrows
WITH target AS (
	SELECT work_queue_items.queue_name, work_queue_items.item_key
	FROM work_queue_items
	WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
		AND (work_queue_items.item_key, work_queue_items.leased_by) IN (
			SELECT keys.item_key, holders.leased_by
			FROM unnest(sqlc.arg(item_keys)::text[]) WITH ORDINALITY AS keys(item_key, ordinal)
				JOIN unnest(sqlc.arg(leased_bys)::text[]) WITH ORDINALITY AS holders(leased_by, ordinal) USING (ordinal)
		)
	ORDER BY work_queue_items.queue_name, work_queue_items.item_key
	FOR UPDATE
)
UPDATE work_queue_items SET
	completed_at = CURRENT_TIMESTAMP,
	lease_until = TIMESTAMPTZ 'epoch',
	leased_by = NULL,
	last_error = NULL
FROM target
WHERE work_queue_items.queue_name = target.queue_name
	AND work_queue_items.item_key = target.item_key;

-- name: ReleaseItems :execrows
WITH target AS (
	SELECT work_queue_items.queue_name, work_queue_items.item_key
	FROM work_queue_items
	WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
		AND work_queue_items.completed_at IS NULL
		AND (work_queue_items.item_key, work_queue_items.leased_by) IN (
			SELECT keys.item_key, holders.leased_by
			FROM unnest(sqlc.arg(item_keys)::text[]) WITH ORDINALITY AS keys(item_key, ordinal)
				JOIN unnest(sqlc.arg(leased_bys)::text[]) WITH ORDINALITY AS holders(leased_by, ordinal) USING (ordinal)
		)
	ORDER BY work_queue_items.queue_name, work_queue_items.item_key
	FOR UPDATE
)
UPDATE work_queue_items SET
	lease_until = TIMESTAMPTZ 'epoch',
	leased_by = NULL,
	available_at = CURRENT_TIMESTAMP + (sqlc.arg(delay_microseconds)::bigint * INTERVAL '1 microsecond'),
	last_error = sqlc.narg(last_error)
FROM target
WHERE work_queue_items.queue_name = target.queue_name
	AND work_queue_items.item_key = target.item_key;

-- name: RemoveItems :execrows
WITH target AS (
	SELECT work_queue_items.queue_name, work_queue_items.item_key
	FROM work_queue_items
	WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
		AND work_queue_items.item_key = ANY(sqlc.arg(item_keys)::text[])
	ORDER BY work_queue_items.queue_name, work_queue_items.item_key
	FOR UPDATE
)
DELETE FROM work_queue_items
USING target
WHERE work_queue_items.queue_name = target.queue_name
	AND work_queue_items.item_key = target.item_key;

-- name: RequeueItems :execrows
WITH target AS (
	SELECT work_queue_items.queue_name, work_queue_items.item_key
	FROM work_queue_items
	WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
		AND work_queue_items.completed_at IS NULL
		AND work_queue_items.item_key = ANY(sqlc.arg(item_keys)::text[])
	ORDER BY work_queue_items.queue_name, work_queue_items.item_key
	FOR UPDATE
)
UPDATE work_queue_items SET
	attempts = 0,
	available_at = CURRENT_TIMESTAMP
FROM target
WHERE work_queue_items.queue_name = target.queue_name
	AND work_queue_items.item_key = target.item_key;

-- name: ReapCompletedItems :execrows
WITH doomed AS (
	SELECT work_queue_items.queue_name, work_queue_items.item_key
	FROM work_queue_items
	WHERE work_queue_items.queue_name = sqlc.arg(queue_name)
		AND work_queue_items.completed_at IS NOT NULL
		AND work_queue_items.completed_at < CURRENT_TIMESTAMP - (sqlc.arg(retention_microseconds)::bigint * INTERVAL '1 microsecond')
	ORDER BY work_queue_items.queue_name, work_queue_items.item_key
	LIMIT sqlc.arg(reap_limit)::int
	FOR UPDATE SKIP LOCKED
)
DELETE FROM work_queue_items
USING doomed
WHERE work_queue_items.queue_name = doomed.queue_name
	AND work_queue_items.item_key = doomed.item_key;

-- name: ReadQueueStats :one
SELECT
	COALESCE(SUM(CASE WHEN work_queue_items.completed_at IS NULL THEN 1 ELSE 0 END), 0)::bigint AS pending,
	COALESCE(SUM(CASE WHEN work_queue_items.queue_name = sqlc.arg(queue_name) AND work_queue_items.completed_at IS NULL AND work_queue_items.lease_until <= CURRENT_TIMESTAMP AND work_queue_items.available_at <= CURRENT_TIMESTAMP AND (sqlc.arg(attempt_ceiling)::int <= 0 OR work_queue_items.attempts < sqlc.arg(attempt_ceiling)::int) THEN 1 ELSE 0 END), 0)::bigint AS ready,
	COALESCE(SUM(CASE WHEN work_queue_items.completed_at IS NULL AND work_queue_items.lease_until > CURRENT_TIMESTAMP THEN 1 ELSE 0 END), 0)::bigint AS leased,
	COALESCE(SUM(CASE WHEN work_queue_items.completed_at IS NULL AND sqlc.arg(attempt_ceiling)::int > 0
		AND work_queue_items.attempts >= sqlc.arg(attempt_ceiling)::int THEN 1 ELSE 0 END), 0)::bigint AS stalled,
	COALESCE(SUM(CASE WHEN work_queue_items.completed_at IS NOT NULL THEN 1 ELSE 0 END), 0)::bigint AS completed,
	COALESCE((EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - MIN(CASE WHEN work_queue_items.queue_name = sqlc.arg(queue_name) AND work_queue_items.completed_at IS NULL AND work_queue_items.lease_until <= CURRENT_TIMESTAMP AND work_queue_items.available_at <= CURRENT_TIMESTAMP AND (sqlc.arg(attempt_ceiling)::int <= 0 OR work_queue_items.attempts < sqlc.arg(attempt_ceiling)::int) THEN work_queue_items.available_at END))) * 1000000)::bigint, 0)::bigint AS oldest_ready_microseconds
FROM work_queue_items
WHERE work_queue_items.queue_name = sqlc.arg(queue_name);
