// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package shreddingmock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/platform-go/v13/cryptography/shredding"
)

// Ensure, that StoreMock does implement shredding.Store.
// If this is not the case, regenerate this file with moq.
var _ shredding.Store = &StoreMock{}

// StoreMock is a mock implementation of shredding.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked shredding.Store
//		mockedStore := &StoreMock{
//			InsertFunc: func(ctx context.Context, record *shredding.Record) (bool, error) {
//				panic("mock out the Insert method")
//			},
//			LoadFunc: func(ctx context.Context, subject shredding.Subject) (*shredding.Record, error) {
//				panic("mock out the Load method")
//			},
//			ShredFunc: func(ctx context.Context, subject shredding.Subject, at time.Time) (shredding.Receipt, error) {
//				panic("mock out the Shred method")
//			},
//		}
//
//		// use mockedStore in code that requires shredding.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// InsertFunc mocks the Insert method.
	InsertFunc func(ctx context.Context, record *shredding.Record) (bool, error)

	// LoadFunc mocks the Load method.
	LoadFunc func(ctx context.Context, subject shredding.Subject) (*shredding.Record, error)

	// ShredFunc mocks the Shred method.
	ShredFunc func(ctx context.Context, subject shredding.Subject, at time.Time) (shredding.Receipt, error)

	// calls tracks calls to the methods.
	calls struct {
		// Insert holds details about calls to the Insert method.
		Insert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Record is the record argument value.
			Record *shredding.Record
		}
		// Load holds details about calls to the Load method.
		Load []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Subject is the subject argument value.
			Subject shredding.Subject
		}
		// Shred holds details about calls to the Shred method.
		Shred []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Subject is the subject argument value.
			Subject shredding.Subject
			// At is the at argument value.
			At time.Time
		}
	}
	lockInsert sync.RWMutex
	lockLoad   sync.RWMutex
	lockShred  sync.RWMutex
}

// Insert calls InsertFunc.
func (mock *StoreMock) Insert(ctx context.Context, record *shredding.Record) (bool, error) {
	if mock.InsertFunc == nil {
		panic("StoreMock.InsertFunc: method is nil but Store.Insert was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Record *shredding.Record
	}{
		Ctx:    ctx,
		Record: record,
	}
	mock.lockInsert.Lock()
	mock.calls.Insert = append(mock.calls.Insert, callInfo)
	mock.lockInsert.Unlock()
	return mock.InsertFunc(ctx, record)
}

// InsertCalls gets all the calls that were made to Insert.
// Check the length with:
//
//	len(mockedStore.InsertCalls())
func (mock *StoreMock) InsertCalls() []struct {
	Ctx    context.Context
	Record *shredding.Record
} {
	var calls []struct {
		Ctx    context.Context
		Record *shredding.Record
	}
	mock.lockInsert.RLock()
	calls = mock.calls.Insert
	mock.lockInsert.RUnlock()
	return calls
}

// Load calls LoadFunc.
func (mock *StoreMock) Load(ctx context.Context, subject shredding.Subject) (*shredding.Record, error) {
	if mock.LoadFunc == nil {
		panic("StoreMock.LoadFunc: method is nil but Store.Load was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Subject shredding.Subject
	}{
		Ctx:     ctx,
		Subject: subject,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(ctx, subject)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedStore.LoadCalls())
func (mock *StoreMock) LoadCalls() []struct {
	Ctx     context.Context
	Subject shredding.Subject
} {
	var calls []struct {
		Ctx     context.Context
		Subject shredding.Subject
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Shred calls ShredFunc.
func (mock *StoreMock) Shred(ctx context.Context, subject shredding.Subject, at time.Time) (shredding.Receipt, error) {
	if mock.ShredFunc == nil {
		panic("StoreMock.ShredFunc: method is nil but Store.Shred was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Subject shredding.Subject
		At      time.Time
	}{
		Ctx:     ctx,
		Subject: subject,
		At:      at,
	}
	mock.lockShred.Lock()
	mock.calls.Shred = append(mock.calls.Shred, callInfo)
	mock.lockShred.Unlock()
	return mock.ShredFunc(ctx, subject, at)
}

// ShredCalls gets all the calls that were made to Shred.
// Check the length with:
//
//	len(mockedStore.ShredCalls())
func (mock *StoreMock) ShredCalls() []struct {
	Ctx     context.Context
	Subject shredding.Subject
	At      time.Time
} {
	var calls []struct {
		Ctx     context.Context
		Subject shredding.Subject
		At      time.Time
	}
	mock.lockShred.RLock()
	calls = mock.calls.Shred
	mock.lockShred.RUnlock()
	return calls
}
