// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package registrydb

import (
	"context"
	"strings"
	"time"

	"github.com/primandproper/primitives-go/tenancy"
)

const archiveObjectSQLite = `UPDATE {{prefix}}uploads_objects SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = ?1
	AND scope = ?2`

const createObjectSQLite = `
INSERT INTO {{prefix}}uploads_objects (
	id,
	scope,
	object_key,
	content_type,
	size_bytes,
	owner_id,
	belongs_to_type,
	belongs_to_id
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8
)`

const getObjectSQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.archived_at IS NULL
	AND {{prefix}}uploads_objects.id = ?1
	AND {{prefix}}uploads_objects.scope = ?2`

const getObjectByKeySQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.archived_at IS NULL
	AND {{prefix}}uploads_objects.object_key = ?1
	AND {{prefix}}uploads_objects.scope = ?2`

const getObjectCreatedAtSQLite = `SELECT
	{{prefix}}uploads_objects.created_at
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.id = ?1
	AND {{prefix}}uploads_objects.scope = ?2`

const getObjectIdbyKeySQLite = `SELECT
	{{prefix}}uploads_objects.id
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.object_key = ?1
	AND {{prefix}}uploads_objects.scope = ?2`

const listObjectsSQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
	) AS total_count
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
	AND {{prefix}}uploads_objects.scope = ?6
	AND {{prefix}}uploads_objects.id > COALESCE(?7, '')
ORDER BY {{prefix}}uploads_objects.id ASC
LIMIT COALESCE(?8, 50)`

const listObjectsByIDsSQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.archived_at IS NULL
	AND {{prefix}}uploads_objects.scope = ?1
	AND {{prefix}}uploads_objects.id IN (/*SLICE:ids*/?)
ORDER BY {{prefix}}uploads_objects.id ASC`

const listObjectsByOwnerSQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
			AND {{prefix}}uploads_objects.owner_id = ?7
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
			AND {{prefix}}uploads_objects.owner_id = ?7
	) AS total_count
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
	AND {{prefix}}uploads_objects.scope = ?6
	AND {{prefix}}uploads_objects.owner_id = ?7
	AND {{prefix}}uploads_objects.id > COALESCE(?8, '')
ORDER BY {{prefix}}uploads_objects.id ASC
LIMIT COALESCE(?9, 50)`

const listObjectsByOwnerDescendingSQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
			AND {{prefix}}uploads_objects.owner_id = ?7
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
			AND {{prefix}}uploads_objects.owner_id = ?7
	) AS total_count
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
	AND {{prefix}}uploads_objects.scope = ?6
	AND {{prefix}}uploads_objects.owner_id = ?7
	AND ({{prefix}}uploads_objects.id <= COALESCE(?8, {{prefix}}uploads_objects.id) AND {{prefix}}uploads_objects.id <> COALESCE(?8, ''))
ORDER BY {{prefix}}uploads_objects.id DESC
LIMIT COALESCE(?9, 50)`

const listObjectsBySubjectSQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
			AND {{prefix}}uploads_objects.belongs_to_type = ?7
			AND {{prefix}}uploads_objects.belongs_to_id = ?8
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
			AND {{prefix}}uploads_objects.belongs_to_type = ?7
			AND {{prefix}}uploads_objects.belongs_to_id = ?8
	) AS total_count
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
	AND {{prefix}}uploads_objects.scope = ?6
	AND {{prefix}}uploads_objects.belongs_to_type = ?7
	AND {{prefix}}uploads_objects.belongs_to_id = ?8
	AND {{prefix}}uploads_objects.id > COALESCE(?9, '')
ORDER BY {{prefix}}uploads_objects.id ASC
LIMIT COALESCE(?10, 50)`

const listObjectsBySubjectDescendingSQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
			AND {{prefix}}uploads_objects.belongs_to_type = ?7
			AND {{prefix}}uploads_objects.belongs_to_id = ?8
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
			AND {{prefix}}uploads_objects.belongs_to_type = ?7
			AND {{prefix}}uploads_objects.belongs_to_id = ?8
	) AS total_count
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
	AND {{prefix}}uploads_objects.scope = ?6
	AND {{prefix}}uploads_objects.belongs_to_type = ?7
	AND {{prefix}}uploads_objects.belongs_to_id = ?8
	AND ({{prefix}}uploads_objects.id <= COALESCE(?9, {{prefix}}uploads_objects.id) AND {{prefix}}uploads_objects.id <> COALESCE(?9, ''))
ORDER BY {{prefix}}uploads_objects.id DESC
LIMIT COALESCE(?10, 50)`

const listObjectsDescendingSQLite = `SELECT
	{{prefix}}uploads_objects.id,
	{{prefix}}uploads_objects.scope,
	{{prefix}}uploads_objects.object_key,
	{{prefix}}uploads_objects.content_type,
	{{prefix}}uploads_objects.size_bytes,
	{{prefix}}uploads_objects.owner_id,
	{{prefix}}uploads_objects.belongs_to_type,
	{{prefix}}uploads_objects.belongs_to_id,
	{{prefix}}uploads_objects.created_at,
	{{prefix}}uploads_objects.last_updated_at,
	{{prefix}}uploads_objects.archived_at,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
			)
			AND (
				{{prefix}}uploads_objects.last_updated_at IS NULL
				OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
			)
			AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}uploads_objects.id)
		FROM {{prefix}}uploads_objects
		WHERE (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
			AND {{prefix}}uploads_objects.scope = ?6
	) AS total_count
FROM {{prefix}}uploads_objects
WHERE {{prefix}}uploads_objects.created_at > COALESCE(?1, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	AND {{prefix}}uploads_objects.created_at < COALESCE(?2, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at > COALESCE(?3, (SELECT datetime(CURRENT_TIMESTAMP, '-999 years')))
	)
	AND (
		{{prefix}}uploads_objects.last_updated_at IS NULL
		OR {{prefix}}uploads_objects.last_updated_at < COALESCE(?4, (SELECT datetime(CURRENT_TIMESTAMP, '+999 years')))
	)
	AND (COALESCE(?5, false) = true OR {{prefix}}uploads_objects.archived_at IS NULL)
	AND {{prefix}}uploads_objects.scope = ?6
	AND ({{prefix}}uploads_objects.id <= COALESCE(?7, {{prefix}}uploads_objects.id) AND {{prefix}}uploads_objects.id <> COALESCE(?7, ''))
ORDER BY {{prefix}}uploads_objects.id DESC
LIMIT COALESCE(?8, 50)`

// sqliteQueries answers every query in Querier against sqlite.
type sqliteQueries struct {
	archiveObject                  string
	createObject                   string
	getObject                      string
	getObjectByKey                 string
	getObjectCreatedAt             string
	getObjectIdbyKey               string
	listObjects                    string
	listObjectsByIDs               string
	listObjectsByOwner             string
	listObjectsByOwnerDescending   string
	listObjectsBySubject           string
	listObjectsBySubjectDescending string
	listObjectsDescending          string
}

// newSQLite returns the sqlite querier with prefix substituted into every
// table name the analyzer identified.
func newSQLite(prefix string) *sqliteQueries {
	return &sqliteQueries{
		archiveObject:                  strings.ReplaceAll(archiveObjectSQLite, prefixMarker, prefix),
		createObject:                   strings.ReplaceAll(createObjectSQLite, prefixMarker, prefix),
		getObject:                      strings.ReplaceAll(getObjectSQLite, prefixMarker, prefix),
		getObjectByKey:                 strings.ReplaceAll(getObjectByKeySQLite, prefixMarker, prefix),
		getObjectCreatedAt:             strings.ReplaceAll(getObjectCreatedAtSQLite, prefixMarker, prefix),
		getObjectIdbyKey:               strings.ReplaceAll(getObjectIdbyKeySQLite, prefixMarker, prefix),
		listObjects:                    strings.ReplaceAll(listObjectsSQLite, prefixMarker, prefix),
		listObjectsByIDs:               strings.ReplaceAll(listObjectsByIDsSQLite, prefixMarker, prefix),
		listObjectsByOwner:             strings.ReplaceAll(listObjectsByOwnerSQLite, prefixMarker, prefix),
		listObjectsByOwnerDescending:   strings.ReplaceAll(listObjectsByOwnerDescendingSQLite, prefixMarker, prefix),
		listObjectsBySubject:           strings.ReplaceAll(listObjectsBySubjectSQLite, prefixMarker, prefix),
		listObjectsBySubjectDescending: strings.ReplaceAll(listObjectsBySubjectDescendingSQLite, prefixMarker, prefix),
		listObjectsDescending:          strings.ReplaceAll(listObjectsDescendingSQLite, prefixMarker, prefix),
	}
}

// timeText renders a time argument as the text this engine stores timestamps as.
//
// This engine has no date type: a DATETIME column holds text, and a comparison
// between two of them compares two strings. What a driver writes for a bound
// time.Time is Go's own rendering of it, whose leading characters happen to be
// the stored shape — but only while the value is UTC. A time carrying any other
// zone puts its own wall clock in those leading characters, so every window
// comparison is off by that offset, silently, and only for the callers whose
// clock is not UTC.
//
// Converting here is what makes the bound text the stored shape by
// construction rather than by accident, whatever zone the caller's time
// carries. The layout is whole seconds, which is what CURRENT_TIMESTAMP writes,
// so a bound value and a stored one are one shape rather than two that sort
// alike — which does mean a sub-second time bound here is stored truncated to
// the second on this engine.
func timeText(t time.Time) string {
	return t.UTC().Format("2006-01-02 15:04:05")
}

// timeTextPtr is timeText for a nullable argument. It preserves nil, so a
// field the caller left unset still binds NULL rather than the zero time.
func timeTextPtr(t *time.Time) any {
	if t == nil {
		return nil
	}

	return timeText(*t)
}

// ArchiveObject runs the :execrows query against sqlite.
func (q *sqliteQueries) ArchiveObject(ctx context.Context, db DBTX, arg ArchiveObjectParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveObject,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// CreateObject runs the :exec query against sqlite.
func (q *sqliteQueries) CreateObject(ctx context.Context, db DBTX, arg CreateObjectParams) error {
	_, err := db.ExecContext(ctx, q.createObject,
		arg.ID,
		arg.Scope,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
		arg.OwnerID,
		arg.BelongsToType,
		arg.BelongsToID,
	)

	return err
}

// GetObject runs the :one query against sqlite.
func (q *sqliteQueries) GetObject(ctx context.Context, db DBTX, arg GetObjectParams) (GetObjectRow, error) {
	row := db.QueryRowContext(ctx, q.getObject,
		arg.ID,
		arg.Scope,
	)

	var i GetObjectRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.OwnerID,
		&i.BelongsToType,
		&i.BelongsToID,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetObjectByKey runs the :one query against sqlite.
func (q *sqliteQueries) GetObjectByKey(ctx context.Context, db DBTX, arg GetObjectByKeyParams) (GetObjectByKeyRow, error) {
	row := db.QueryRowContext(ctx, q.getObjectByKey,
		arg.ObjectKey,
		arg.Scope,
	)

	var i GetObjectByKeyRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.OwnerID,
		&i.BelongsToType,
		&i.BelongsToID,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetObjectCreatedAt runs the :one query against sqlite.
func (q *sqliteQueries) GetObjectCreatedAt(ctx context.Context, db DBTX, arg GetObjectCreatedAtParams) (GetObjectCreatedAtRow, error) {
	row := db.QueryRowContext(ctx, q.getObjectCreatedAt,
		arg.ID,
		arg.Scope,
	)

	var i GetObjectCreatedAtRow

	err := row.Scan(
		&i.CreatedAt,
	)

	return i, err
}

// GetObjectIDByKey runs the :one query against sqlite.
func (q *sqliteQueries) GetObjectIDByKey(ctx context.Context, db DBTX, arg GetObjectIDByKeyParams) (GetObjectIDByKeyRow, error) {
	row := db.QueryRowContext(ctx, q.getObjectIdbyKey,
		arg.ObjectKey,
		arg.Scope,
	)

	var i GetObjectIDByKeyRow

	err := row.Scan(
		&i.ID,
	)

	return i, err
}

// ListObjects runs the :many query against sqlite.
func (q *sqliteQueries) ListObjects(ctx context.Context, db DBTX, arg ListObjectsParams) ([]ListObjectsRow, error) {
	rows, err := db.QueryContext(ctx, q.listObjects,
		timeTextPtr(arg.CreatedAfter),
		timeTextPtr(arg.CreatedBefore),
		timeTextPtr(arg.UpdatedAfter),
		timeTextPtr(arg.UpdatedBefore),
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListObjectsRow

	for rows.Next() {
		var i ListObjectsRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.OwnerID,
			&i.BelongsToType,
			&i.BelongsToID,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListObjectsByIDs runs the :many query against sqlite.
func (q *sqliteQueries) ListObjectsByIDs(ctx context.Context, db DBTX, arg ListObjectsByIDsParams) ([]ListObjectsByIDsRow, error) {
	query := q.listObjectsByIDs

	args := make([]any, 0, 1+len(arg.IDs))

	args = append(args, arg.Scope)

	query = strings.Replace(query, "/*SLICE:ids*/?", slicePlaceholders("?", len(arg.IDs)), 1)

	for _, v := range arg.IDs {
		args = append(args, v)
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListObjectsByIDsRow

	for rows.Next() {
		var i ListObjectsByIDsRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.OwnerID,
			&i.BelongsToType,
			&i.BelongsToID,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListObjectsByOwner runs the :many query against sqlite.
func (q *sqliteQueries) ListObjectsByOwner(ctx context.Context, db DBTX, arg ListObjectsByOwnerParams) ([]ListObjectsByOwnerRow, error) {
	rows, err := db.QueryContext(ctx, q.listObjectsByOwner,
		timeTextPtr(arg.CreatedAfter),
		timeTextPtr(arg.CreatedBefore),
		timeTextPtr(arg.UpdatedAfter),
		timeTextPtr(arg.UpdatedBefore),
		arg.IncludeArchived,
		arg.Scope,
		arg.OwnerID,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListObjectsByOwnerRow

	for rows.Next() {
		var i ListObjectsByOwnerRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.OwnerID,
			&i.BelongsToType,
			&i.BelongsToID,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListObjectsByOwnerDescending runs the :many query against sqlite.
func (q *sqliteQueries) ListObjectsByOwnerDescending(ctx context.Context, db DBTX, arg ListObjectsByOwnerDescendingParams) ([]ListObjectsByOwnerDescendingRow, error) {
	rows, err := db.QueryContext(ctx, q.listObjectsByOwnerDescending,
		timeTextPtr(arg.CreatedAfter),
		timeTextPtr(arg.CreatedBefore),
		timeTextPtr(arg.UpdatedAfter),
		timeTextPtr(arg.UpdatedBefore),
		arg.IncludeArchived,
		arg.Scope,
		arg.OwnerID,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListObjectsByOwnerDescendingRow

	for rows.Next() {
		var i ListObjectsByOwnerDescendingRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.OwnerID,
			&i.BelongsToType,
			&i.BelongsToID,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListObjectsBySubject runs the :many query against sqlite.
func (q *sqliteQueries) ListObjectsBySubject(ctx context.Context, db DBTX, arg ListObjectsBySubjectParams) ([]ListObjectsBySubjectRow, error) {
	rows, err := db.QueryContext(ctx, q.listObjectsBySubject,
		timeTextPtr(arg.CreatedAfter),
		timeTextPtr(arg.CreatedBefore),
		timeTextPtr(arg.UpdatedAfter),
		timeTextPtr(arg.UpdatedBefore),
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToType,
		arg.BelongsToID,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListObjectsBySubjectRow

	for rows.Next() {
		var i ListObjectsBySubjectRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.OwnerID,
			&i.BelongsToType,
			&i.BelongsToID,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListObjectsBySubjectDescending runs the :many query against sqlite.
func (q *sqliteQueries) ListObjectsBySubjectDescending(ctx context.Context, db DBTX, arg ListObjectsBySubjectDescendingParams) ([]ListObjectsBySubjectDescendingRow, error) {
	rows, err := db.QueryContext(ctx, q.listObjectsBySubjectDescending,
		timeTextPtr(arg.CreatedAfter),
		timeTextPtr(arg.CreatedBefore),
		timeTextPtr(arg.UpdatedAfter),
		timeTextPtr(arg.UpdatedBefore),
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToType,
		arg.BelongsToID,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListObjectsBySubjectDescendingRow

	for rows.Next() {
		var i ListObjectsBySubjectDescendingRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.OwnerID,
			&i.BelongsToType,
			&i.BelongsToID,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListObjectsDescending runs the :many query against sqlite.
func (q *sqliteQueries) ListObjectsDescending(ctx context.Context, db DBTX, arg ListObjectsDescendingParams) ([]ListObjectsDescendingRow, error) {
	rows, err := db.QueryContext(ctx, q.listObjectsDescending,
		timeTextPtr(arg.CreatedAfter),
		timeTextPtr(arg.CreatedBefore),
		timeTextPtr(arg.UpdatedAfter),
		timeTextPtr(arg.UpdatedBefore),
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListObjectsDescendingRow

	for rows.Next() {
		var i ListObjectsDescendingRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.OwnerID,
			&i.BelongsToType,
			&i.BelongsToID,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(ArchiveObjectParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
	}(CreateObjectParams{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetObjectParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetObjectRow{})
	_ = struct {
		ObjectKey string
		Scope     tenancy.Scope
	}(GetObjectByKeyParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetObjectByKeyRow{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetObjectCreatedAtParams{})
	_ = struct {
		CreatedAt time.Time
	}(GetObjectCreatedAtRow{})
	_ = struct {
		ObjectKey string
		Scope     tenancy.Scope
	}(GetObjectIDByKeyParams{})
	_ = struct {
		ID string
	}(GetObjectIDByKeyRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListObjectsParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListObjectsRow{})
	_ = struct {
		Scope tenancy.Scope
		IDs   []string
	}(ListObjectsByIDsParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(ListObjectsByIDsRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		OwnerID         string
		PageCursor      *string
		ResultLimit     int64
	}(ListObjectsByOwnerParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListObjectsByOwnerRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		OwnerID         string
		PageCursor      *string
		ResultLimit     int64
	}(ListObjectsByOwnerDescendingParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListObjectsByOwnerDescendingRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		BelongsToType   string
		BelongsToID     string
		PageCursor      *string
		ResultLimit     int64
	}(ListObjectsBySubjectParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListObjectsBySubjectRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		BelongsToType   string
		BelongsToID     string
		PageCursor      *string
		ResultLimit     int64
	}(ListObjectsBySubjectDescendingParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListObjectsBySubjectDescendingRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListObjectsDescendingParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		ObjectKey     string
		ContentType   string
		SizeBytes     int64
		OwnerID       string
		BelongsToType string
		BelongsToID   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListObjectsDescendingRow{})
)
