// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sessionsmock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/platform-go/v13/sessions"
)

// Ensure, that StoreMock does implement sessions.Store.
// If this is not the case, regenerate this file with moq.
var _ sessions.Store[any] = &StoreMock[any]{}

// StoreMock is a mock implementation of sessions.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked sessions.Store
//		mockedStore := &StoreMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) (*sessions.Session[T], error) {
//				panic("mock out the Get method")
//			},
//			NewFunc: func(ctx context.Context, data *T) (*sessions.Session[T], error) {
//				panic("mock out the New method")
//			},
//			PolicyFunc: func() sessions.Policy {
//				panic("mock out the Policy method")
//			},
//			RenewFunc: func(ctx context.Context, oldID string) (string, error) {
//				panic("mock out the Renew method")
//			},
//			SaveFunc: func(ctx context.Context, id string, data *T) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedStore in code that requires sessions.Store
//		// and then make assertions.
//
//	}
type StoreMock[T any] struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) (*sessions.Session[T], error)

	// NewFunc mocks the New method.
	NewFunc func(ctx context.Context, data *T) (*sessions.Session[T], error)

	// PolicyFunc mocks the Policy method.
	PolicyFunc func() sessions.Policy

	// RenewFunc mocks the Renew method.
	RenewFunc func(ctx context.Context, oldID string) (string, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, id string, data *T) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// New holds details about calls to the New method.
		New []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Data is the data argument value.
			Data *T
		}
		// Policy holds details about calls to the Policy method.
		Policy []struct {
		}
		// Renew holds details about calls to the Renew method.
		Renew []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OldID is the oldID argument value.
			OldID string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Data is the data argument value.
			Data *T
		}
	}
	lockClose  sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockNew    sync.RWMutex
	lockPolicy sync.RWMutex
	lockRenew  sync.RWMutex
	lockSave   sync.RWMutex
}

// Close calls CloseFunc.
func (mock *StoreMock[T]) Close() error {
	if mock.CloseFunc == nil {
		panic("StoreMock.CloseFunc: method is nil but Store.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStore.CloseCalls())
func (mock *StoreMock[T]) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *StoreMock[T]) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("StoreMock.DeleteFunc: method is nil but Store.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedStore.DeleteCalls())
func (mock *StoreMock[T]) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *StoreMock[T]) Get(ctx context.Context, id string) (*sessions.Session[T], error) {
	if mock.GetFunc == nil {
		panic("StoreMock.GetFunc: method is nil but Store.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedStore.GetCalls())
func (mock *StoreMock[T]) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// New calls NewFunc.
func (mock *StoreMock[T]) New(ctx context.Context, data *T) (*sessions.Session[T], error) {
	if mock.NewFunc == nil {
		panic("StoreMock.NewFunc: method is nil but Store.New was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Data *T
	}{
		Ctx:  ctx,
		Data: data,
	}
	mock.lockNew.Lock()
	mock.calls.New = append(mock.calls.New, callInfo)
	mock.lockNew.Unlock()
	return mock.NewFunc(ctx, data)
}

// NewCalls gets all the calls that were made to New.
// Check the length with:
//
//	len(mockedStore.NewCalls())
func (mock *StoreMock[T]) NewCalls() []struct {
	Ctx  context.Context
	Data *T
} {
	var calls []struct {
		Ctx  context.Context
		Data *T
	}
	mock.lockNew.RLock()
	calls = mock.calls.New
	mock.lockNew.RUnlock()
	return calls
}

// Policy calls PolicyFunc.
func (mock *StoreMock[T]) Policy() sessions.Policy {
	if mock.PolicyFunc == nil {
		panic("StoreMock.PolicyFunc: method is nil but Store.Policy was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPolicy.Lock()
	mock.calls.Policy = append(mock.calls.Policy, callInfo)
	mock.lockPolicy.Unlock()
	return mock.PolicyFunc()
}

// PolicyCalls gets all the calls that were made to Policy.
// Check the length with:
//
//	len(mockedStore.PolicyCalls())
func (mock *StoreMock[T]) PolicyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPolicy.RLock()
	calls = mock.calls.Policy
	mock.lockPolicy.RUnlock()
	return calls
}

// Renew calls RenewFunc.
func (mock *StoreMock[T]) Renew(ctx context.Context, oldID string) (string, error) {
	if mock.RenewFunc == nil {
		panic("StoreMock.RenewFunc: method is nil but Store.Renew was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		OldID string
	}{
		Ctx:   ctx,
		OldID: oldID,
	}
	mock.lockRenew.Lock()
	mock.calls.Renew = append(mock.calls.Renew, callInfo)
	mock.lockRenew.Unlock()
	return mock.RenewFunc(ctx, oldID)
}

// RenewCalls gets all the calls that were made to Renew.
// Check the length with:
//
//	len(mockedStore.RenewCalls())
func (mock *StoreMock[T]) RenewCalls() []struct {
	Ctx   context.Context
	OldID string
} {
	var calls []struct {
		Ctx   context.Context
		OldID string
	}
	mock.lockRenew.RLock()
	calls = mock.calls.Renew
	mock.lockRenew.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *StoreMock[T]) Save(ctx context.Context, id string, data *T) error {
	if mock.SaveFunc == nil {
		panic("StoreMock.SaveFunc: method is nil but Store.Save was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		ID   string
		Data *T
	}{
		Ctx:  ctx,
		ID:   id,
		Data: data,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, id, data)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedStore.SaveCalls())
func (mock *StoreMock[T]) SaveCalls() []struct {
	Ctx  context.Context
	ID   string
	Data *T
} {
	var calls []struct {
		Ctx  context.Context
		ID   string
		Data *T
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}

// Ensure, that BackendMock does implement sessions.Backend.
// If this is not the case, regenerate this file with moq.
var _ sessions.Backend[any] = &BackendMock[any]{}

// BackendMock is a mock implementation of sessions.Backend.
//
//	func TestSomethingThatUsesBackend(t *testing.T) {
//
//		// make and configure a mocked sessions.Backend
//		mockedBackend := &BackendMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CreateFunc: func(ctx context.Context, id string, record *sessions.Record[T], ttl time.Duration) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			LoadFunc: func(ctx context.Context, id string) (*sessions.Record[T], error) {
//				panic("mock out the Load method")
//			},
//			RenameFunc: func(ctx context.Context, oldID string, newID string, record *sessions.Record[T], ttl time.Duration) error {
//				panic("mock out the Rename method")
//			},
//			UpdateFunc: func(ctx context.Context, id string, record *sessions.Record[T], ttl time.Duration) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedBackend in code that requires sessions.Backend
//		// and then make assertions.
//
//	}
type BackendMock[T any] struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, id string, record *sessions.Record[T], ttl time.Duration) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// LoadFunc mocks the Load method.
	LoadFunc func(ctx context.Context, id string) (*sessions.Record[T], error)

	// RenameFunc mocks the Rename method.
	RenameFunc func(ctx context.Context, oldID string, newID string, record *sessions.Record[T], ttl time.Duration) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id string, record *sessions.Record[T], ttl time.Duration) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Record is the record argument value.
			Record *sessions.Record[T]
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Load holds details about calls to the Load method.
		Load []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Rename holds details about calls to the Rename method.
		Rename []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OldID is the oldID argument value.
			OldID string
			// NewID is the newID argument value.
			NewID string
			// Record is the record argument value.
			Record *sessions.Record[T]
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Record is the record argument value.
			Record *sessions.Record[T]
			// TTL is the ttl argument value.
			TTL time.Duration
		}
	}
	lockClose  sync.RWMutex
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockLoad   sync.RWMutex
	lockRename sync.RWMutex
	lockUpdate sync.RWMutex
}

// Close calls CloseFunc.
func (mock *BackendMock[T]) Close() error {
	if mock.CloseFunc == nil {
		panic("BackendMock.CloseFunc: method is nil but Backend.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedBackend.CloseCalls())
func (mock *BackendMock[T]) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *BackendMock[T]) Create(ctx context.Context, id string, record *sessions.Record[T], ttl time.Duration) error {
	if mock.CreateFunc == nil {
		panic("BackendMock.CreateFunc: method is nil but Backend.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     string
		Record *sessions.Record[T]
		TTL    time.Duration
	}{
		Ctx:    ctx,
		ID:     id,
		Record: record,
		TTL:    ttl,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, id, record, ttl)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedBackend.CreateCalls())
func (mock *BackendMock[T]) CreateCalls() []struct {
	Ctx    context.Context
	ID     string
	Record *sessions.Record[T]
	TTL    time.Duration
} {
	var calls []struct {
		Ctx    context.Context
		ID     string
		Record *sessions.Record[T]
		TTL    time.Duration
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *BackendMock[T]) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("BackendMock.DeleteFunc: method is nil but Backend.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedBackend.DeleteCalls())
func (mock *BackendMock[T]) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Load calls LoadFunc.
func (mock *BackendMock[T]) Load(ctx context.Context, id string) (*sessions.Record[T], error) {
	if mock.LoadFunc == nil {
		panic("BackendMock.LoadFunc: method is nil but Backend.Load was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(ctx, id)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedBackend.LoadCalls())
func (mock *BackendMock[T]) LoadCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// Rename calls RenameFunc.
func (mock *BackendMock[T]) Rename(ctx context.Context, oldID string, newID string, record *sessions.Record[T], ttl time.Duration) error {
	if mock.RenameFunc == nil {
		panic("BackendMock.RenameFunc: method is nil but Backend.Rename was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		OldID  string
		NewID  string
		Record *sessions.Record[T]
		TTL    time.Duration
	}{
		Ctx:    ctx,
		OldID:  oldID,
		NewID:  newID,
		Record: record,
		TTL:    ttl,
	}
	mock.lockRename.Lock()
	mock.calls.Rename = append(mock.calls.Rename, callInfo)
	mock.lockRename.Unlock()
	return mock.RenameFunc(ctx, oldID, newID, record, ttl)
}

// RenameCalls gets all the calls that were made to Rename.
// Check the length with:
//
//	len(mockedBackend.RenameCalls())
func (mock *BackendMock[T]) RenameCalls() []struct {
	Ctx    context.Context
	OldID  string
	NewID  string
	Record *sessions.Record[T]
	TTL    time.Duration
} {
	var calls []struct {
		Ctx    context.Context
		OldID  string
		NewID  string
		Record *sessions.Record[T]
		TTL    time.Duration
	}
	mock.lockRename.RLock()
	calls = mock.calls.Rename
	mock.lockRename.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *BackendMock[T]) Update(ctx context.Context, id string, record *sessions.Record[T], ttl time.Duration) error {
	if mock.UpdateFunc == nil {
		panic("BackendMock.UpdateFunc: method is nil but Backend.Update was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ID     string
		Record *sessions.Record[T]
		TTL    time.Duration
	}{
		Ctx:    ctx,
		ID:     id,
		Record: record,
		TTL:    ttl,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, record, ttl)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedBackend.UpdateCalls())
func (mock *BackendMock[T]) UpdateCalls() []struct {
	Ctx    context.Context
	ID     string
	Record *sessions.Record[T]
	TTL    time.Duration
} {
	var calls []struct {
		Ctx    context.Context
		ID     string
		Record *sessions.Record[T]
		TTL    time.Duration
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
