// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package shreddingdb

import (
	"context"
	"strings"
	"time"
)

const getSubjectKeySQLite = `
SELECT
	{{prefix}}shredding_subject_keys.subject_type,
	{{prefix}}shredding_subject_keys.subject_id,
	{{prefix}}shredding_subject_keys.wrapped_key,
	{{prefix}}shredding_subject_keys.created_at,
	{{prefix}}shredding_subject_keys.shredded_at
FROM {{prefix}}shredding_subject_keys
WHERE {{prefix}}shredding_subject_keys.subject_type = ?1
	AND {{prefix}}shredding_subject_keys.subject_id = ?2`

const insertSubjectKeySQLite = `INSERT OR IGNORE INTO {{prefix}}shredding_subject_keys (
	subject_type,
	subject_id,
	wrapped_key,
	created_at,
	shredded_at
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5
)`

const shredSubjectKeySQLite = `UPDATE {{prefix}}shredding_subject_keys SET
	wrapped_key = ?1,
	shredded_at = ?2,
	last_updated_at = ?3
WHERE subject_type = ?4
	AND subject_id = ?5
	AND shredded_at IS NULL`

// sqliteQueries answers every query in Querier against sqlite.
type sqliteQueries struct {
	getSubjectKey    string
	insertSubjectKey string
	shredSubjectKey  string
}

// newSQLite returns the sqlite querier with prefix substituted into every
// table name the analyzer identified.
func newSQLite(prefix string) *sqliteQueries {
	return &sqliteQueries{
		getSubjectKey:    strings.ReplaceAll(getSubjectKeySQLite, prefixMarker, prefix),
		insertSubjectKey: strings.ReplaceAll(insertSubjectKeySQLite, prefixMarker, prefix),
		shredSubjectKey:  strings.ReplaceAll(shredSubjectKeySQLite, prefixMarker, prefix),
	}
}

// timeText renders a time argument as the text this engine stores timestamps as.
//
// This engine has no date type: a DATETIME column holds text, and a comparison
// between two of them compares two strings. What a driver writes for a bound
// time.Time is Go's own rendering of it, whose leading characters happen to be
// the stored shape — but only while the value is UTC. A time carrying any other
// zone puts its own wall clock in those leading characters, so every window
// comparison is off by that offset, silently, and only for the callers whose
// clock is not UTC.
//
// Converting here is what makes the bound text the stored shape by
// construction rather than by accident, whatever zone the caller's time
// carries. The layout is whole seconds, which is what CURRENT_TIMESTAMP writes,
// so a bound value and a stored one are one shape rather than two that sort
// alike — which does mean a sub-second time bound here is stored truncated to
// the second on this engine.
func timeText(t time.Time) string {
	return t.UTC().Format("2006-01-02 15:04:05")
}

// timeTextPtr is timeText for a nullable argument. It preserves nil, so a
// field the caller left unset still binds NULL rather than the zero time.
func timeTextPtr(t *time.Time) any {
	if t == nil {
		return nil
	}

	return timeText(*t)
}

// GetSubjectKey runs the :one query against sqlite.
func (q *sqliteQueries) GetSubjectKey(ctx context.Context, db DBTX, arg GetSubjectKeyParams) (GetSubjectKeyRow, error) {
	row := db.QueryRowContext(ctx, q.getSubjectKey,
		arg.SubjectType,
		arg.SubjectID,
	)

	var i GetSubjectKeyRow

	err := row.Scan(
		&i.SubjectType,
		&i.SubjectID,
		&i.WrappedKey,
		&i.CreatedAt,
		&i.ShreddedAt,
	)

	return i, err
}

// InsertSubjectKey runs the :execrows query against sqlite.
func (q *sqliteQueries) InsertSubjectKey(ctx context.Context, db DBTX, arg InsertSubjectKeyParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.insertSubjectKey,
		arg.SubjectType,
		arg.SubjectID,
		arg.WrappedKey,
		timeText(arg.CreatedAt),
		timeTextPtr(arg.ShreddedAt),
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// ShredSubjectKey runs the :execrows query against sqlite.
func (q *sqliteQueries) ShredSubjectKey(ctx context.Context, db DBTX, arg ShredSubjectKeyParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.shredSubjectKey,
		arg.WrappedKey,
		timeTextPtr(arg.ShreddedAt),
		timeTextPtr(arg.LastUpdatedAt),
		arg.SubjectType,
		arg.SubjectID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		SubjectType string
		SubjectID   string
	}(GetSubjectKeyParams{})
	_ = struct {
		SubjectType string
		SubjectID   string
		WrappedKey  []byte
		CreatedAt   time.Time
		ShreddedAt  *time.Time
	}(GetSubjectKeyRow{})
	_ = struct {
		SubjectType string
		SubjectID   string
		WrappedKey  []byte
		CreatedAt   time.Time
		ShreddedAt  *time.Time
	}(InsertSubjectKeyParams{})
	_ = struct {
		WrappedKey    []byte
		ShreddedAt    *time.Time
		LastUpdatedAt *time.Time
		SubjectType   string
		SubjectID     string
	}(ShredSubjectKeyParams{})
)
