// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package signindb

import (
	"context"
	"strings"
	"time"

	"github.com/primandproper/primitives-go/v2/tenancy"
)

const getRefreshTokenSQLite = `SELECT
	{{prefix}}signin_refresh_tokens.scope,
	{{prefix}}signin_refresh_tokens.family_id,
	{{prefix}}signin_refresh_tokens.subject_id,
	{{prefix}}signin_refresh_tokens.active_account_id,
	{{prefix}}signin_refresh_tokens.administrative,
	{{prefix}}signin_refresh_tokens.issued_at,
	{{prefix}}signin_refresh_tokens.expires_at,
	{{prefix}}signin_refresh_tokens.purge_after,
	{{prefix}}signin_refresh_tokens.redeemed_at,
	{{prefix}}signin_refresh_tokens.revoked_at
FROM {{prefix}}signin_refresh_tokens
WHERE {{prefix}}signin_refresh_tokens.hash = ?1
	AND {{prefix}}signin_refresh_tokens.scope = ?2`

const insertRefreshTokenSQLite = `
INSERT INTO {{prefix}}signin_refresh_tokens (
	hash,
	scope,
	family_id,
	subject_id,
	active_account_id,
	administrative,
	issued_at,
	expires_at,
	purge_after
) VALUES (
	?1,
	?2,
	?3,
	?4,
	?5,
	?6,
	?7,
	?8,
	?9
)`

const redeemRefreshTokenSQLite = `UPDATE {{prefix}}signin_refresh_tokens SET
	redeemed_at = ?1
WHERE hash = ?2
	AND scope = ?3
	AND redeemed_at IS NULL
	AND revoked_at IS NULL
	AND expires_at > ?4`

const revokeRefreshTokenFamilySQLite = `UPDATE {{prefix}}signin_refresh_tokens SET
	revoked_at = ?1
WHERE scope = ?2
	AND family_id = ?3
	AND revoked_at IS NULL`

const revokeRefreshTokensForSubjectSQLite = `UPDATE {{prefix}}signin_refresh_tokens SET
	revoked_at = ?1
WHERE scope = ?2
	AND subject_id = ?3
	AND revoked_at IS NULL`

const sweepRefreshTokensSQLite = `DELETE FROM {{prefix}}signin_refresh_tokens
WHERE purge_after <= ?1`

// sqliteQueries answers every query in Querier against sqlite.
type sqliteQueries struct {
	getRefreshToken               string
	insertRefreshToken            string
	redeemRefreshToken            string
	revokeRefreshTokenFamily      string
	revokeRefreshTokensForSubject string
	sweepRefreshTokens            string
}

// newSQLite returns the sqlite querier with prefix substituted into every
// table name the analyzer identified.
func newSQLite(prefix string) *sqliteQueries {
	return &sqliteQueries{
		getRefreshToken:               strings.ReplaceAll(getRefreshTokenSQLite, prefixMarker, prefix),
		insertRefreshToken:            strings.ReplaceAll(insertRefreshTokenSQLite, prefixMarker, prefix),
		redeemRefreshToken:            strings.ReplaceAll(redeemRefreshTokenSQLite, prefixMarker, prefix),
		revokeRefreshTokenFamily:      strings.ReplaceAll(revokeRefreshTokenFamilySQLite, prefixMarker, prefix),
		revokeRefreshTokensForSubject: strings.ReplaceAll(revokeRefreshTokensForSubjectSQLite, prefixMarker, prefix),
		sweepRefreshTokens:            strings.ReplaceAll(sweepRefreshTokensSQLite, prefixMarker, prefix),
	}
}

// timeText renders a time argument as the text this engine stores timestamps as.
//
// This engine has no date type: a DATETIME column holds text, and a comparison
// between two of them compares two strings. What a driver writes for a bound
// time.Time is Go's own rendering of it, whose leading characters happen to be
// the stored shape — but only while the value is UTC. A time carrying any other
// zone puts its own wall clock in those leading characters, so every window
// comparison is off by that offset, silently, and only for the callers whose
// clock is not UTC.
//
// Converting here is what makes the bound text the stored shape by
// construction rather than by accident, whatever zone the caller's time
// carries. The layout is whole seconds, which is what CURRENT_TIMESTAMP writes,
// so a bound value and a stored one are one shape rather than two that sort
// alike — which does mean a sub-second time bound here is stored truncated to
// the second on this engine.
func timeText(t time.Time) string {
	return t.UTC().Format("2006-01-02 15:04:05")
}

// timeTextPtr is timeText for a nullable argument. It preserves nil, so a
// field the caller left unset still binds NULL rather than the zero time.
func timeTextPtr(t *time.Time) any {
	if t == nil {
		return nil
	}

	return timeText(*t)
}

// GetRefreshToken runs the :one query against sqlite.
func (q *sqliteQueries) GetRefreshToken(ctx context.Context, db DBTX, arg GetRefreshTokenParams) (GetRefreshTokenRow, error) {
	row := db.QueryRowContext(ctx, q.getRefreshToken,
		arg.Hash,
		arg.Scope,
	)

	var i GetRefreshTokenRow

	err := row.Scan(
		&i.Scope,
		&i.FamilyID,
		&i.SubjectID,
		&i.ActiveAccountID,
		&i.Administrative,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.PurgeAfter,
		&i.RedeemedAt,
		&i.RevokedAt,
	)

	return i, err
}

// InsertRefreshToken runs the :exec query against sqlite.
func (q *sqliteQueries) InsertRefreshToken(ctx context.Context, db DBTX, arg InsertRefreshTokenParams) error {
	_, err := db.ExecContext(ctx, q.insertRefreshToken,
		arg.Hash,
		arg.Scope,
		arg.FamilyID,
		arg.SubjectID,
		arg.ActiveAccountID,
		arg.Administrative,
		timeText(arg.IssuedAt),
		timeText(arg.ExpiresAt),
		timeText(arg.PurgeAfter),
	)

	return err
}

// RedeemRefreshToken runs the :execrows query against sqlite.
func (q *sqliteQueries) RedeemRefreshToken(ctx context.Context, db DBTX, arg RedeemRefreshTokenParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.redeemRefreshToken,
		timeTextPtr(arg.RedeemedAt),
		arg.Hash,
		arg.Scope,
		timeText(arg.Now),
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// RevokeRefreshTokenFamily runs the :execrows query against sqlite.
func (q *sqliteQueries) RevokeRefreshTokenFamily(ctx context.Context, db DBTX, arg RevokeRefreshTokenFamilyParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.revokeRefreshTokenFamily,
		timeTextPtr(arg.RevokedAt),
		arg.Scope,
		arg.FamilyID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// RevokeRefreshTokensForSubject runs the :execrows query against sqlite.
func (q *sqliteQueries) RevokeRefreshTokensForSubject(ctx context.Context, db DBTX, arg RevokeRefreshTokensForSubjectParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.revokeRefreshTokensForSubject,
		timeTextPtr(arg.RevokedAt),
		arg.Scope,
		arg.SubjectID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SweepRefreshTokens runs the :execrows query against sqlite.
func (q *sqliteQueries) SweepRefreshTokens(ctx context.Context, db DBTX, arg SweepRefreshTokensParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepRefreshTokens,
		timeText(arg.PurgeBefore),
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		Hash  string
		Scope tenancy.Scope
	}(GetRefreshTokenParams{})
	_ = struct {
		Scope           tenancy.Scope
		FamilyID        string
		SubjectID       string
		ActiveAccountID string
		Administrative  bool
		IssuedAt        time.Time
		ExpiresAt       time.Time
		PurgeAfter      time.Time
		RedeemedAt      *time.Time
		RevokedAt       *time.Time
	}(GetRefreshTokenRow{})
	_ = struct {
		Hash            string
		Scope           tenancy.Scope
		FamilyID        string
		SubjectID       string
		ActiveAccountID string
		Administrative  bool
		IssuedAt        time.Time
		ExpiresAt       time.Time
		PurgeAfter      time.Time
	}(InsertRefreshTokenParams{})
	_ = struct {
		RedeemedAt *time.Time
		Hash       string
		Scope      tenancy.Scope
		Now        time.Time
	}(RedeemRefreshTokenParams{})
	_ = struct {
		RevokedAt *time.Time
		Scope     tenancy.Scope
		FamilyID  string
	}(RevokeRefreshTokenFamilyParams{})
	_ = struct {
		RevokedAt *time.Time
		Scope     tenancy.Scope
		SubjectID string
	}(RevokeRefreshTokensForSubjectParams{})
	_ = struct {
		PurgeBefore time.Time
	}(SweepRefreshTokensParams{})
)
