// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package signindb

import (
	"time"

	"github.com/primandproper/primitives-go/v2/tenancy"
)

// GetRefreshTokenParams are the arguments to GetRefreshToken.
type GetRefreshTokenParams struct {
	Hash  string
	Scope tenancy.Scope
}

// GetRefreshTokenRow is one row of GetRefreshToken's result.
type GetRefreshTokenRow struct {
	Scope           tenancy.Scope
	FamilyID        string
	SubjectID       string
	ActiveAccountID string
	Administrative  bool
	IssuedAt        time.Time
	ExpiresAt       time.Time
	PurgeAfter      time.Time
	RedeemedAt      *time.Time
	RevokedAt       *time.Time
}

// InsertRefreshTokenParams are the arguments to InsertRefreshToken.
type InsertRefreshTokenParams struct {
	Hash            string
	Scope           tenancy.Scope
	FamilyID        string
	SubjectID       string
	ActiveAccountID string
	Administrative  bool
	IssuedAt        time.Time
	ExpiresAt       time.Time
	PurgeAfter      time.Time
}

// RedeemRefreshTokenParams are the arguments to RedeemRefreshToken.
type RedeemRefreshTokenParams struct {
	RedeemedAt *time.Time
	Hash       string
	Scope      tenancy.Scope
	Now        time.Time
}

// RevokeRefreshTokenFamilyParams are the arguments to RevokeRefreshTokenFamily.
type RevokeRefreshTokenFamilyParams struct {
	RevokedAt *time.Time
	Scope     tenancy.Scope
	FamilyID  string
}

// RevokeRefreshTokensForSubjectParams are the arguments to RevokeRefreshTokensForSubject.
type RevokeRefreshTokensForSubjectParams struct {
	RevokedAt *time.Time
	Scope     tenancy.Scope
	SubjectID string
}

// SweepRefreshTokensParams are the arguments to SweepRefreshTokens.
type SweepRefreshTokensParams struct {
	PurgeBefore time.Time
}
