// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package notificationsdb

import (
	"time"

	"github.com/primandproper/primitives-go/v2/tenancy"
)

// ArchiveNotificationParams are the arguments to ArchiveNotification.
type ArchiveNotificationParams struct {
	ID        string
	Scope     tenancy.Scope
	Principal string
}

// CreateNotificationParams are the arguments to CreateNotification.
type CreateNotificationParams struct {
	ID        string
	Scope     tenancy.Scope
	Principal string
	Topic     string
	Title     string
	Body      string
	Link      string
	ReadAt    *time.Time
}

// DeleteDeviceTokenParams are the arguments to DeleteDeviceToken.
type DeleteDeviceTokenParams struct {
	Platform string
	Token    string
}

// GetArchivedNotificationParams are the arguments to GetArchivedNotification.
type GetArchivedNotificationParams struct {
	ID        string
	Scope     tenancy.Scope
	Principal string
}

// GetArchivedNotificationRow is one row of GetArchivedNotification's result.
type GetArchivedNotificationRow struct {
	ID            string
	Scope         tenancy.Scope
	Principal     string
	Topic         string
	Title         string
	Body          string
	Link          string
	ReadAt        *time.Time
	CreatedAt     time.Time
	LastUpdatedAt *time.Time
	ArchivedAt    *time.Time
}

// GetDeviceParams are the arguments to GetDevice.
type GetDeviceParams struct {
	ID        string
	Scope     tenancy.Scope
	Principal string
}

// GetDeviceRow is one row of GetDevice's result.
type GetDeviceRow struct {
	ID         string
	Scope      tenancy.Scope
	Principal  string
	Platform   string
	Token      string
	LastSeenAt time.Time
	CreatedAt  time.Time
}

// GetDeviceByTokenParams are the arguments to GetDeviceByToken.
type GetDeviceByTokenParams struct {
	Scope    tenancy.Scope
	Platform string
	Token    string
}

// GetDeviceByTokenRow is one row of GetDeviceByToken's result.
type GetDeviceByTokenRow struct {
	ID         string
	Scope      tenancy.Scope
	Principal  string
	Platform   string
	Token      string
	LastSeenAt time.Time
	CreatedAt  time.Time
}

// GetNotificationParams are the arguments to GetNotification.
type GetNotificationParams struct {
	ID        string
	Scope     tenancy.Scope
	Principal string
}

// GetNotificationRow is one row of GetNotification's result.
type GetNotificationRow struct {
	ID            string
	Scope         tenancy.Scope
	Principal     string
	Topic         string
	Title         string
	Body          string
	Link          string
	ReadAt        *time.Time
	CreatedAt     time.Time
	LastUpdatedAt *time.Time
	ArchivedAt    *time.Time
}

// ListDevicesParams are the arguments to ListDevices.
type ListDevicesParams struct {
	CreatedAfter  *time.Time
	CreatedBefore *time.Time
	Scope         tenancy.Scope
	Principal     string
	PageCursor    *string
	ResultLimit   int64
}

// ListDevicesRow is one row of ListDevices's result.
type ListDevicesRow struct {
	ID            string
	Scope         tenancy.Scope
	Principal     string
	Platform      string
	Token         string
	LastSeenAt    time.Time
	CreatedAt     time.Time
	FilteredCount int64
	TotalCount    int64
}

// ListDevicesByPrincipalsParams are the arguments to ListDevicesByPrincipals.
type ListDevicesByPrincipalsParams struct {
	Scope      tenancy.Scope
	Principals []string
}

// ListDevicesByPrincipalsRow is one row of ListDevicesByPrincipals's result.
type ListDevicesByPrincipalsRow struct {
	ID         string
	Scope      tenancy.Scope
	Principal  string
	Platform   string
	Token      string
	LastSeenAt time.Time
	CreatedAt  time.Time
}

// ListDevicesDescendingParams are the arguments to ListDevicesDescending.
type ListDevicesDescendingParams struct {
	CreatedAfter  *time.Time
	CreatedBefore *time.Time
	Scope         tenancy.Scope
	Principal     string
	PageCursor    *string
	ResultLimit   int64
}

// ListDevicesDescendingRow is one row of ListDevicesDescending's result.
type ListDevicesDescendingRow struct {
	ID            string
	Scope         tenancy.Scope
	Principal     string
	Platform      string
	Token         string
	LastSeenAt    time.Time
	CreatedAt     time.Time
	FilteredCount int64
	TotalCount    int64
}

// ListNotificationsParams are the arguments to ListNotifications.
type ListNotificationsParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	Principal       string
	PageCursor      *string
	ResultLimit     int64
}

// ListNotificationsRow is one row of ListNotifications's result.
type ListNotificationsRow struct {
	ID            string
	Scope         tenancy.Scope
	Principal     string
	Topic         string
	Title         string
	Body          string
	Link          string
	ReadAt        *time.Time
	CreatedAt     time.Time
	LastUpdatedAt *time.Time
	ArchivedAt    *time.Time
	FilteredCount int64
	TotalCount    int64
}

// ListNotificationsDescendingParams are the arguments to ListNotificationsDescending.
type ListNotificationsDescendingParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	Principal       string
	PageCursor      *string
	ResultLimit     int64
}

// ListNotificationsDescendingRow is one row of ListNotificationsDescending's result.
type ListNotificationsDescendingRow struct {
	ID            string
	Scope         tenancy.Scope
	Principal     string
	Topic         string
	Title         string
	Body          string
	Link          string
	ReadAt        *time.Time
	CreatedAt     time.Time
	LastUpdatedAt *time.Time
	ArchivedAt    *time.Time
	FilteredCount int64
	TotalCount    int64
}

// ListUnreadNotificationsParams are the arguments to ListUnreadNotifications.
type ListUnreadNotificationsParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	Principal       string
	PageCursor      *string
	ResultLimit     int64
}

// ListUnreadNotificationsRow is one row of ListUnreadNotifications's result.
type ListUnreadNotificationsRow struct {
	ID            string
	Scope         tenancy.Scope
	Principal     string
	Topic         string
	Title         string
	Body          string
	Link          string
	ReadAt        *time.Time
	CreatedAt     time.Time
	LastUpdatedAt *time.Time
	ArchivedAt    *time.Time
	FilteredCount int64
	TotalCount    int64
}

// ListUnreadNotificationsDescendingParams are the arguments to ListUnreadNotificationsDescending.
type ListUnreadNotificationsDescendingParams struct {
	CreatedAfter    *time.Time
	CreatedBefore   *time.Time
	UpdatedAfter    *time.Time
	UpdatedBefore   *time.Time
	IncludeArchived bool
	Scope           tenancy.Scope
	Principal       string
	PageCursor      *string
	ResultLimit     int64
}

// ListUnreadNotificationsDescendingRow is one row of ListUnreadNotificationsDescending's result.
type ListUnreadNotificationsDescendingRow struct {
	ID            string
	Scope         tenancy.Scope
	Principal     string
	Topic         string
	Title         string
	Body          string
	Link          string
	ReadAt        *time.Time
	CreatedAt     time.Time
	LastUpdatedAt *time.Time
	ArchivedAt    *time.Time
	FilteredCount int64
	TotalCount    int64
}

// MarkAllNotificationsReadParams are the arguments to MarkAllNotificationsRead.
type MarkAllNotificationsReadParams struct {
	ReadAt    *time.Time
	Scope     tenancy.Scope
	Principal string
}

// MarkNotificationReadParams are the arguments to MarkNotificationRead.
type MarkNotificationReadParams struct {
	ReadAt    *time.Time
	ID        string
	Scope     tenancy.Scope
	Principal string
}

// RegisterDeviceParams are the arguments to RegisterDevice.
type RegisterDeviceParams struct {
	ID         string
	Scope      tenancy.Scope
	Principal  string
	Platform   string
	Token      string
	LastSeenAt time.Time
}

// RevokeDeviceParams are the arguments to RevokeDevice.
type RevokeDeviceParams struct {
	ID        string
	Scope     tenancy.Scope
	Principal string
}
