// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package sessionsdb

import (
	"context"
	"strings"
	"time"

	"github.com/primandproper/primitives-go/tenancy"
)

const createSessionPostgreSQL = `
INSERT INTO {{prefix}}sessions (
	id,
	scope,
	principal,
	data,
	device_name,
	ip_address,
	user_agent,
	login_method,
	created_at,
	last_seen_at,
	expires_at,
	version
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11,
	$12
)
ON CONFLICT (id) DO NOTHING`

const deleteSessionPostgreSQL = `DELETE FROM {{prefix}}sessions
WHERE id = $1`

const deleteSessionForPrincipalPostgreSQL = `DELETE FROM {{prefix}}sessions
WHERE id = $1
	AND scope = $2
	AND principal = $3`

const deleteSessionsForPrincipalPostgreSQL = `DELETE FROM {{prefix}}sessions
WHERE scope = $1
	AND principal = $2
	AND id <> COALESCE($3, '')`

const getSessionPostgreSQL = `SELECT
	{{prefix}}sessions.scope,
	{{prefix}}sessions.principal,
	{{prefix}}sessions.data,
	{{prefix}}sessions.device_name,
	{{prefix}}sessions.ip_address,
	{{prefix}}sessions.user_agent,
	{{prefix}}sessions.login_method,
	{{prefix}}sessions.created_at,
	{{prefix}}sessions.last_seen_at,
	{{prefix}}sessions.version
FROM {{prefix}}sessions
WHERE {{prefix}}sessions.id = $1`

const listSessionsForPrincipalPostgreSQL = `SELECT
	{{prefix}}sessions.id,
	{{prefix}}sessions.data,
	{{prefix}}sessions.device_name,
	{{prefix}}sessions.ip_address,
	{{prefix}}sessions.user_agent,
	{{prefix}}sessions.login_method,
	{{prefix}}sessions.created_at,
	{{prefix}}sessions.last_seen_at,
	{{prefix}}sessions.version
FROM {{prefix}}sessions
WHERE {{prefix}}sessions.scope = $1
	AND {{prefix}}sessions.principal = $2
ORDER BY {{prefix}}sessions.created_at DESC, {{prefix}}sessions.id DESC`

const sessionExistsPostgreSQL = `SELECT EXISTS (
	SELECT {{prefix}}sessions.id
	FROM {{prefix}}sessions
	WHERE {{prefix}}sessions.id = $1
)`

const sweepSessionsPostgreSQL = `DELETE FROM {{prefix}}sessions
WHERE expires_at <= $1`

const updateSessionPostgreSQL = `UPDATE {{prefix}}sessions SET
	data = $1,
	last_seen_at = $2,
	expires_at = $3,
	version = $4
WHERE id = $5`

// postgresqlQueries answers every query in Querier against postgresql.
type postgresqlQueries struct {
	createSession              string
	deleteSession              string
	deleteSessionForPrincipal  string
	deleteSessionsForPrincipal string
	getSession                 string
	listSessionsForPrincipal   string
	sessionExists              string
	sweepSessions              string
	updateSession              string
}

// newPostgreSQL returns the postgresql querier with prefix substituted into every
// table name the analyzer identified.
func newPostgreSQL(prefix string) *postgresqlQueries {
	return &postgresqlQueries{
		createSession:              strings.ReplaceAll(createSessionPostgreSQL, prefixMarker, prefix),
		deleteSession:              strings.ReplaceAll(deleteSessionPostgreSQL, prefixMarker, prefix),
		deleteSessionForPrincipal:  strings.ReplaceAll(deleteSessionForPrincipalPostgreSQL, prefixMarker, prefix),
		deleteSessionsForPrincipal: strings.ReplaceAll(deleteSessionsForPrincipalPostgreSQL, prefixMarker, prefix),
		getSession:                 strings.ReplaceAll(getSessionPostgreSQL, prefixMarker, prefix),
		listSessionsForPrincipal:   strings.ReplaceAll(listSessionsForPrincipalPostgreSQL, prefixMarker, prefix),
		sessionExists:              strings.ReplaceAll(sessionExistsPostgreSQL, prefixMarker, prefix),
		sweepSessions:              strings.ReplaceAll(sweepSessionsPostgreSQL, prefixMarker, prefix),
		updateSession:              strings.ReplaceAll(updateSessionPostgreSQL, prefixMarker, prefix),
	}
}

// CreateSession runs the :execrows query against postgresql.
func (q *postgresqlQueries) CreateSession(ctx context.Context, db DBTX, arg CreateSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createSession,
		arg.ID,
		arg.Scope,
		arg.Principal,
		arg.Data,
		arg.DeviceName,
		arg.IPAddress,
		arg.UserAgent,
		arg.LoginMethod,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteSession runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteSession(ctx context.Context, db DBTX, arg DeleteSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteSession,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteSessionForPrincipal runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteSessionForPrincipal(ctx context.Context, db DBTX, arg DeleteSessionForPrincipalParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteSessionForPrincipal,
		arg.ID,
		arg.Scope,
		arg.Principal,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteSessionsForPrincipal runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteSessionsForPrincipal(ctx context.Context, db DBTX, arg DeleteSessionsForPrincipalParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteSessionsForPrincipal,
		arg.Scope,
		arg.Principal,
		arg.KeptSessionID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetSession runs the :one query against postgresql.
func (q *postgresqlQueries) GetSession(ctx context.Context, db DBTX, arg GetSessionParams) (GetSessionRow, error) {
	row := db.QueryRowContext(ctx, q.getSession,
		arg.ID,
	)

	var i GetSessionRow

	err := row.Scan(
		&i.Scope,
		&i.Principal,
		&i.Data,
		&i.DeviceName,
		&i.IPAddress,
		&i.UserAgent,
		&i.LoginMethod,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Version,
	)

	return i, err
}

// ListSessionsForPrincipal runs the :many query against postgresql.
func (q *postgresqlQueries) ListSessionsForPrincipal(ctx context.Context, db DBTX, arg ListSessionsForPrincipalParams) ([]ListSessionsForPrincipalRow, error) {
	rows, err := db.QueryContext(ctx, q.listSessionsForPrincipal,
		arg.Scope,
		arg.Principal,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListSessionsForPrincipalRow

	for rows.Next() {
		var i ListSessionsForPrincipalRow

		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.DeviceName,
			&i.IPAddress,
			&i.UserAgent,
			&i.LoginMethod,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.Version,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SessionExists runs the :one query against postgresql.
func (q *postgresqlQueries) SessionExists(ctx context.Context, db DBTX, arg SessionExistsParams) (SessionExistsRow, error) {
	row := db.QueryRowContext(ctx, q.sessionExists,
		arg.ID,
	)

	var i SessionExistsRow

	err := row.Scan(
		&i.Exists,
	)

	return i, err
}

// SweepSessions runs the :execrows query against postgresql.
func (q *postgresqlQueries) SweepSessions(ctx context.Context, db DBTX, arg SweepSessionsParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepSessions,
		arg.Cutoff,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpdateSession runs the :execrows query against postgresql.
func (q *postgresqlQueries) UpdateSession(ctx context.Context, db DBTX, arg UpdateSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateSession,
		arg.Data,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.Version,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID          string
		Scope       tenancy.Scope
		Principal   string
		Data        []byte
		DeviceName  string
		IPAddress   string
		UserAgent   string
		LoginMethod string
		CreatedAt   time.Time
		LastSeenAt  time.Time
		ExpiresAt   time.Time
		Version     int64
	}(CreateSessionParams{})
	_ = struct {
		ID string
	}(DeleteSessionParams{})
	_ = struct {
		ID        string
		Scope     tenancy.Scope
		Principal string
	}(DeleteSessionForPrincipalParams{})
	_ = struct {
		Scope         tenancy.Scope
		Principal     string
		KeptSessionID *string
	}(DeleteSessionsForPrincipalParams{})
	_ = struct {
		ID string
	}(GetSessionParams{})
	_ = struct {
		Scope       tenancy.Scope
		Principal   string
		Data        []byte
		DeviceName  string
		IPAddress   string
		UserAgent   string
		LoginMethod string
		CreatedAt   time.Time
		LastSeenAt  time.Time
		Version     int64
	}(GetSessionRow{})
	_ = struct {
		Scope     tenancy.Scope
		Principal string
	}(ListSessionsForPrincipalParams{})
	_ = struct {
		ID          string
		Data        []byte
		DeviceName  string
		IPAddress   string
		UserAgent   string
		LoginMethod string
		CreatedAt   time.Time
		LastSeenAt  time.Time
		Version     int64
	}(ListSessionsForPrincipalRow{})
	_ = struct {
		ID string
	}(SessionExistsParams{})
	_ = struct {
		Exists bool
	}(SessionExistsRow{})
	_ = struct {
		Cutoff time.Time
	}(SweepSessionsParams{})
	_ = struct {
		Data       []byte
		LastSeenAt time.Time
		ExpiresAt  time.Time
		Version    int64
		ID         string
	}(UpdateSessionParams{})
)
