// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package oauth2clientsdb

import (
	"context"
	"strings"
	"time"

	"github.com/primandproper/primitives-go/v2/tenancy"
)

const archiveRegisteredClientPostgreSQL = `UPDATE {{prefix}}oauth2_registered_clients SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = $1
	AND scope = $2`

const createRegisteredClientPostgreSQL = `INSERT INTO {{prefix}}oauth2_registered_clients (
	id,
	scope,
	belongs_to_user,
	name,
	description,
	client_id,
	secret_hash,
	redirect_uris,
	scopes
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9
)
ON CONFLICT (client_id) DO NOTHING`

const getArchivedRegisteredClientPostgreSQL = `SELECT
	{{prefix}}oauth2_registered_clients.id,
	{{prefix}}oauth2_registered_clients.scope,
	{{prefix}}oauth2_registered_clients.belongs_to_user,
	{{prefix}}oauth2_registered_clients.name,
	{{prefix}}oauth2_registered_clients.description,
	{{prefix}}oauth2_registered_clients.client_id,
	{{prefix}}oauth2_registered_clients.secret_hash,
	{{prefix}}oauth2_registered_clients.redirect_uris,
	{{prefix}}oauth2_registered_clients.scopes,
	{{prefix}}oauth2_registered_clients.created_at,
	{{prefix}}oauth2_registered_clients.last_updated_at,
	{{prefix}}oauth2_registered_clients.archived_at
FROM {{prefix}}oauth2_registered_clients
WHERE {{prefix}}oauth2_registered_clients.id = $1
	AND {{prefix}}oauth2_registered_clients.scope = $2
	AND {{prefix}}oauth2_registered_clients.archived_at IS NOT NULL`

const getRegisteredClientPostgreSQL = `
SELECT
	{{prefix}}oauth2_registered_clients.id,
	{{prefix}}oauth2_registered_clients.scope,
	{{prefix}}oauth2_registered_clients.belongs_to_user,
	{{prefix}}oauth2_registered_clients.name,
	{{prefix}}oauth2_registered_clients.description,
	{{prefix}}oauth2_registered_clients.client_id,
	{{prefix}}oauth2_registered_clients.secret_hash,
	{{prefix}}oauth2_registered_clients.redirect_uris,
	{{prefix}}oauth2_registered_clients.scopes,
	{{prefix}}oauth2_registered_clients.created_at,
	{{prefix}}oauth2_registered_clients.last_updated_at,
	{{prefix}}oauth2_registered_clients.archived_at
FROM {{prefix}}oauth2_registered_clients
WHERE {{prefix}}oauth2_registered_clients.archived_at IS NULL
	AND {{prefix}}oauth2_registered_clients.id = $1
	AND {{prefix}}oauth2_registered_clients.scope = $2`

const getRegisteredClientByClientIDPostgreSQL = `SELECT
	{{prefix}}oauth2_registered_clients.id,
	{{prefix}}oauth2_registered_clients.scope,
	{{prefix}}oauth2_registered_clients.belongs_to_user,
	{{prefix}}oauth2_registered_clients.name,
	{{prefix}}oauth2_registered_clients.description,
	{{prefix}}oauth2_registered_clients.client_id,
	{{prefix}}oauth2_registered_clients.secret_hash,
	{{prefix}}oauth2_registered_clients.redirect_uris,
	{{prefix}}oauth2_registered_clients.scopes,
	{{prefix}}oauth2_registered_clients.created_at,
	{{prefix}}oauth2_registered_clients.last_updated_at,
	{{prefix}}oauth2_registered_clients.archived_at
FROM {{prefix}}oauth2_registered_clients
WHERE {{prefix}}oauth2_registered_clients.client_id = $1`

const listRegisteredClientsPostgreSQL = `SELECT
	{{prefix}}oauth2_registered_clients.id,
	{{prefix}}oauth2_registered_clients.scope,
	{{prefix}}oauth2_registered_clients.belongs_to_user,
	{{prefix}}oauth2_registered_clients.name,
	{{prefix}}oauth2_registered_clients.description,
	{{prefix}}oauth2_registered_clients.client_id,
	{{prefix}}oauth2_registered_clients.secret_hash,
	{{prefix}}oauth2_registered_clients.redirect_uris,
	{{prefix}}oauth2_registered_clients.scopes,
	{{prefix}}oauth2_registered_clients.created_at,
	{{prefix}}oauth2_registered_clients.last_updated_at,
	{{prefix}}oauth2_registered_clients.archived_at,
	(
		SELECT COUNT({{prefix}}oauth2_registered_clients.id)
		FROM {{prefix}}oauth2_registered_clients
		WHERE {{prefix}}oauth2_registered_clients.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}oauth2_registered_clients.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
				OR {{prefix}}oauth2_registered_clients.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
				OR {{prefix}}oauth2_registered_clients.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
			AND {{prefix}}oauth2_registered_clients.scope = $6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}oauth2_registered_clients.id)
		FROM {{prefix}}oauth2_registered_clients
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
			AND {{prefix}}oauth2_registered_clients.scope = $6
	) AS total_count
FROM {{prefix}}oauth2_registered_clients
WHERE {{prefix}}oauth2_registered_clients.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}oauth2_registered_clients.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
		OR {{prefix}}oauth2_registered_clients.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
		OR {{prefix}}oauth2_registered_clients.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
	AND {{prefix}}oauth2_registered_clients.scope = $6
	AND {{prefix}}oauth2_registered_clients.id > COALESCE($7, '')
ORDER BY {{prefix}}oauth2_registered_clients.id ASC
LIMIT COALESCE($8, 50)`

const listRegisteredClientsDescendingPostgreSQL = `SELECT
	{{prefix}}oauth2_registered_clients.id,
	{{prefix}}oauth2_registered_clients.scope,
	{{prefix}}oauth2_registered_clients.belongs_to_user,
	{{prefix}}oauth2_registered_clients.name,
	{{prefix}}oauth2_registered_clients.description,
	{{prefix}}oauth2_registered_clients.client_id,
	{{prefix}}oauth2_registered_clients.secret_hash,
	{{prefix}}oauth2_registered_clients.redirect_uris,
	{{prefix}}oauth2_registered_clients.scopes,
	{{prefix}}oauth2_registered_clients.created_at,
	{{prefix}}oauth2_registered_clients.last_updated_at,
	{{prefix}}oauth2_registered_clients.archived_at,
	(
		SELECT COUNT({{prefix}}oauth2_registered_clients.id)
		FROM {{prefix}}oauth2_registered_clients
		WHERE {{prefix}}oauth2_registered_clients.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}oauth2_registered_clients.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
				OR {{prefix}}oauth2_registered_clients.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
				OR {{prefix}}oauth2_registered_clients.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
			AND {{prefix}}oauth2_registered_clients.scope = $6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}oauth2_registered_clients.id)
		FROM {{prefix}}oauth2_registered_clients
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
			AND {{prefix}}oauth2_registered_clients.scope = $6
	) AS total_count
FROM {{prefix}}oauth2_registered_clients
WHERE {{prefix}}oauth2_registered_clients.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}oauth2_registered_clients.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
		OR {{prefix}}oauth2_registered_clients.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
		OR {{prefix}}oauth2_registered_clients.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
	AND {{prefix}}oauth2_registered_clients.scope = $6
	AND ({{prefix}}oauth2_registered_clients.id <= COALESCE($7, {{prefix}}oauth2_registered_clients.id) AND {{prefix}}oauth2_registered_clients.id <> COALESCE($7, ''))
ORDER BY {{prefix}}oauth2_registered_clients.id DESC
LIMIT COALESCE($8, 50)`

const listRegisteredClientsForOwnerPostgreSQL = `SELECT
	{{prefix}}oauth2_registered_clients.id,
	{{prefix}}oauth2_registered_clients.scope,
	{{prefix}}oauth2_registered_clients.belongs_to_user,
	{{prefix}}oauth2_registered_clients.name,
	{{prefix}}oauth2_registered_clients.description,
	{{prefix}}oauth2_registered_clients.client_id,
	{{prefix}}oauth2_registered_clients.secret_hash,
	{{prefix}}oauth2_registered_clients.redirect_uris,
	{{prefix}}oauth2_registered_clients.scopes,
	{{prefix}}oauth2_registered_clients.created_at,
	{{prefix}}oauth2_registered_clients.last_updated_at,
	{{prefix}}oauth2_registered_clients.archived_at,
	(
		SELECT COUNT({{prefix}}oauth2_registered_clients.id)
		FROM {{prefix}}oauth2_registered_clients
		WHERE {{prefix}}oauth2_registered_clients.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}oauth2_registered_clients.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
				OR {{prefix}}oauth2_registered_clients.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
				OR {{prefix}}oauth2_registered_clients.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
			AND {{prefix}}oauth2_registered_clients.scope = $6
			AND {{prefix}}oauth2_registered_clients.belongs_to_user = $7
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}oauth2_registered_clients.id)
		FROM {{prefix}}oauth2_registered_clients
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
			AND {{prefix}}oauth2_registered_clients.scope = $6
			AND {{prefix}}oauth2_registered_clients.belongs_to_user = $7
	) AS total_count
FROM {{prefix}}oauth2_registered_clients
WHERE {{prefix}}oauth2_registered_clients.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}oauth2_registered_clients.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
		OR {{prefix}}oauth2_registered_clients.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
		OR {{prefix}}oauth2_registered_clients.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
	AND {{prefix}}oauth2_registered_clients.scope = $6
	AND {{prefix}}oauth2_registered_clients.belongs_to_user = $7
	AND {{prefix}}oauth2_registered_clients.id > COALESCE($8, '')
ORDER BY {{prefix}}oauth2_registered_clients.id ASC
LIMIT COALESCE($9, 50)`

const listRegisteredClientsForOwnerDescendingPostgreSQL = `SELECT
	{{prefix}}oauth2_registered_clients.id,
	{{prefix}}oauth2_registered_clients.scope,
	{{prefix}}oauth2_registered_clients.belongs_to_user,
	{{prefix}}oauth2_registered_clients.name,
	{{prefix}}oauth2_registered_clients.description,
	{{prefix}}oauth2_registered_clients.client_id,
	{{prefix}}oauth2_registered_clients.secret_hash,
	{{prefix}}oauth2_registered_clients.redirect_uris,
	{{prefix}}oauth2_registered_clients.scopes,
	{{prefix}}oauth2_registered_clients.created_at,
	{{prefix}}oauth2_registered_clients.last_updated_at,
	{{prefix}}oauth2_registered_clients.archived_at,
	(
		SELECT COUNT({{prefix}}oauth2_registered_clients.id)
		FROM {{prefix}}oauth2_registered_clients
		WHERE {{prefix}}oauth2_registered_clients.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}oauth2_registered_clients.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
				OR {{prefix}}oauth2_registered_clients.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
				OR {{prefix}}oauth2_registered_clients.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
			AND {{prefix}}oauth2_registered_clients.scope = $6
			AND {{prefix}}oauth2_registered_clients.belongs_to_user = $7
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}oauth2_registered_clients.id)
		FROM {{prefix}}oauth2_registered_clients
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
			AND {{prefix}}oauth2_registered_clients.scope = $6
			AND {{prefix}}oauth2_registered_clients.belongs_to_user = $7
	) AS total_count
FROM {{prefix}}oauth2_registered_clients
WHERE {{prefix}}oauth2_registered_clients.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}oauth2_registered_clients.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
		OR {{prefix}}oauth2_registered_clients.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}oauth2_registered_clients.last_updated_at IS NULL
		OR {{prefix}}oauth2_registered_clients.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}oauth2_registered_clients.archived_at IS NULL)
	AND {{prefix}}oauth2_registered_clients.scope = $6
	AND {{prefix}}oauth2_registered_clients.belongs_to_user = $7
	AND ({{prefix}}oauth2_registered_clients.id <= COALESCE($8, {{prefix}}oauth2_registered_clients.id) AND {{prefix}}oauth2_registered_clients.id <> COALESCE($8, ''))
ORDER BY {{prefix}}oauth2_registered_clients.id DESC
LIMIT COALESCE($9, 50)`

const updateRegisteredClientPostgreSQL = `UPDATE {{prefix}}oauth2_registered_clients SET
	name = $1,
	description = $2,
	redirect_uris = $3,
	scopes = $4,
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = $5
	AND scope = $6`

// postgresqlQueries answers every query in Querier against postgresql.
type postgresqlQueries struct {
	archiveRegisteredClient                 string
	createRegisteredClient                  string
	getArchivedRegisteredClient             string
	getRegisteredClient                     string
	getRegisteredClientByClientID           string
	listRegisteredClients                   string
	listRegisteredClientsDescending         string
	listRegisteredClientsForOwner           string
	listRegisteredClientsForOwnerDescending string
	updateRegisteredClient                  string
}

// newPostgreSQL returns the postgresql querier with prefix substituted into every
// table name the analyzer identified.
func newPostgreSQL(prefix string) *postgresqlQueries {
	return &postgresqlQueries{
		archiveRegisteredClient:                 strings.ReplaceAll(archiveRegisteredClientPostgreSQL, prefixMarker, prefix),
		createRegisteredClient:                  strings.ReplaceAll(createRegisteredClientPostgreSQL, prefixMarker, prefix),
		getArchivedRegisteredClient:             strings.ReplaceAll(getArchivedRegisteredClientPostgreSQL, prefixMarker, prefix),
		getRegisteredClient:                     strings.ReplaceAll(getRegisteredClientPostgreSQL, prefixMarker, prefix),
		getRegisteredClientByClientID:           strings.ReplaceAll(getRegisteredClientByClientIDPostgreSQL, prefixMarker, prefix),
		listRegisteredClients:                   strings.ReplaceAll(listRegisteredClientsPostgreSQL, prefixMarker, prefix),
		listRegisteredClientsDescending:         strings.ReplaceAll(listRegisteredClientsDescendingPostgreSQL, prefixMarker, prefix),
		listRegisteredClientsForOwner:           strings.ReplaceAll(listRegisteredClientsForOwnerPostgreSQL, prefixMarker, prefix),
		listRegisteredClientsForOwnerDescending: strings.ReplaceAll(listRegisteredClientsForOwnerDescendingPostgreSQL, prefixMarker, prefix),
		updateRegisteredClient:                  strings.ReplaceAll(updateRegisteredClientPostgreSQL, prefixMarker, prefix),
	}
}

// ArchiveRegisteredClient runs the :execrows query against postgresql.
func (q *postgresqlQueries) ArchiveRegisteredClient(ctx context.Context, db DBTX, arg ArchiveRegisteredClientParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveRegisteredClient,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// CreateRegisteredClient runs the :execrows query against postgresql.
func (q *postgresqlQueries) CreateRegisteredClient(ctx context.Context, db DBTX, arg CreateRegisteredClientParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createRegisteredClient,
		arg.ID,
		arg.Scope,
		arg.BelongsToUser,
		arg.Name,
		arg.Description,
		arg.ClientID,
		arg.SecretHash,
		arg.RedirectUris,
		arg.Scopes,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetArchivedRegisteredClient runs the :one query against postgresql.
func (q *postgresqlQueries) GetArchivedRegisteredClient(ctx context.Context, db DBTX, arg GetArchivedRegisteredClientParams) (GetArchivedRegisteredClientRow, error) {
	row := db.QueryRowContext(ctx, q.getArchivedRegisteredClient,
		arg.ID,
		arg.Scope,
	)

	var i GetArchivedRegisteredClientRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.BelongsToUser,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.SecretHash,
		&i.RedirectUris,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetRegisteredClient runs the :one query against postgresql.
func (q *postgresqlQueries) GetRegisteredClient(ctx context.Context, db DBTX, arg GetRegisteredClientParams) (GetRegisteredClientRow, error) {
	row := db.QueryRowContext(ctx, q.getRegisteredClient,
		arg.ID,
		arg.Scope,
	)

	var i GetRegisteredClientRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.BelongsToUser,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.SecretHash,
		&i.RedirectUris,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetRegisteredClientByClientID runs the :one query against postgresql.
func (q *postgresqlQueries) GetRegisteredClientByClientID(ctx context.Context, db DBTX, arg GetRegisteredClientByClientIDParams) (GetRegisteredClientByClientIDRow, error) {
	row := db.QueryRowContext(ctx, q.getRegisteredClientByClientID,
		arg.ClientID,
	)

	var i GetRegisteredClientByClientIDRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.BelongsToUser,
		&i.Name,
		&i.Description,
		&i.ClientID,
		&i.SecretHash,
		&i.RedirectUris,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// ListRegisteredClients runs the :many query against postgresql.
func (q *postgresqlQueries) ListRegisteredClients(ctx context.Context, db DBTX, arg ListRegisteredClientsParams) ([]ListRegisteredClientsRow, error) {
	rows, err := db.QueryContext(ctx, q.listRegisteredClients,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRegisteredClientsRow

	for rows.Next() {
		var i ListRegisteredClientsRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToUser,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.SecretHash,
			&i.RedirectUris,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRegisteredClientsDescending runs the :many query against postgresql.
func (q *postgresqlQueries) ListRegisteredClientsDescending(ctx context.Context, db DBTX, arg ListRegisteredClientsDescendingParams) ([]ListRegisteredClientsDescendingRow, error) {
	rows, err := db.QueryContext(ctx, q.listRegisteredClientsDescending,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRegisteredClientsDescendingRow

	for rows.Next() {
		var i ListRegisteredClientsDescendingRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToUser,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.SecretHash,
			&i.RedirectUris,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRegisteredClientsForOwner runs the :many query against postgresql.
func (q *postgresqlQueries) ListRegisteredClientsForOwner(ctx context.Context, db DBTX, arg ListRegisteredClientsForOwnerParams) ([]ListRegisteredClientsForOwnerRow, error) {
	rows, err := db.QueryContext(ctx, q.listRegisteredClientsForOwner,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToUser,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRegisteredClientsForOwnerRow

	for rows.Next() {
		var i ListRegisteredClientsForOwnerRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToUser,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.SecretHash,
			&i.RedirectUris,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRegisteredClientsForOwnerDescending runs the :many query against postgresql.
func (q *postgresqlQueries) ListRegisteredClientsForOwnerDescending(ctx context.Context, db DBTX, arg ListRegisteredClientsForOwnerDescendingParams) ([]ListRegisteredClientsForOwnerDescendingRow, error) {
	rows, err := db.QueryContext(ctx, q.listRegisteredClientsForOwnerDescending,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.BelongsToUser,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRegisteredClientsForOwnerDescendingRow

	for rows.Next() {
		var i ListRegisteredClientsForOwnerDescendingRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.BelongsToUser,
			&i.Name,
			&i.Description,
			&i.ClientID,
			&i.SecretHash,
			&i.RedirectUris,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// UpdateRegisteredClient runs the :execrows query against postgresql.
func (q *postgresqlQueries) UpdateRegisteredClient(ctx context.Context, db DBTX, arg UpdateRegisteredClientParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateRegisteredClient,
		arg.Name,
		arg.Description,
		arg.RedirectUris,
		arg.Scopes,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(ArchiveRegisteredClientParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		BelongsToUser string
		Name          string
		Description   string
		ClientID      string
		SecretHash    string
		RedirectUris  string
		Scopes        string
	}(CreateRegisteredClientParams{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetArchivedRegisteredClientParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		BelongsToUser string
		Name          string
		Description   string
		ClientID      string
		SecretHash    string
		RedirectUris  string
		Scopes        string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetArchivedRegisteredClientRow{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetRegisteredClientParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		BelongsToUser string
		Name          string
		Description   string
		ClientID      string
		SecretHash    string
		RedirectUris  string
		Scopes        string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetRegisteredClientRow{})
	_ = struct {
		ClientID string
	}(GetRegisteredClientByClientIDParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		BelongsToUser string
		Name          string
		Description   string
		ClientID      string
		SecretHash    string
		RedirectUris  string
		Scopes        string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetRegisteredClientByClientIDRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListRegisteredClientsParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		BelongsToUser string
		Name          string
		Description   string
		ClientID      string
		SecretHash    string
		RedirectUris  string
		Scopes        string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListRegisteredClientsRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListRegisteredClientsDescendingParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		BelongsToUser string
		Name          string
		Description   string
		ClientID      string
		SecretHash    string
		RedirectUris  string
		Scopes        string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListRegisteredClientsDescendingRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		BelongsToUser   string
		PageCursor      *string
		ResultLimit     int64
	}(ListRegisteredClientsForOwnerParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		BelongsToUser string
		Name          string
		Description   string
		ClientID      string
		SecretHash    string
		RedirectUris  string
		Scopes        string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListRegisteredClientsForOwnerRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		BelongsToUser   string
		PageCursor      *string
		ResultLimit     int64
	}(ListRegisteredClientsForOwnerDescendingParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		BelongsToUser string
		Name          string
		Description   string
		ClientID      string
		SecretHash    string
		RedirectUris  string
		Scopes        string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListRegisteredClientsForOwnerDescendingRow{})
	_ = struct {
		Name         string
		Description  string
		RedirectUris string
		Scopes       string
		ID           string
		Scope        tenancy.Scope
	}(UpdateRegisteredClientParams{})
)
