// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package authorizationdb

import (
	"context"
	"strings"
	"time"
)

const archiveRoleByNamePostgreSQL = `UPDATE {{prefix}}authz_roles SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND name = $1`

const createRoleHierarchyEdgePostgreSQL = `INSERT INTO {{prefix}}authz_role_hierarchy (
	child_role_id,
	parent_role_id
) VALUES (
	$1,
	$2
)
ON CONFLICT (child_role_id, parent_role_id) DO NOTHING`

const createRolePermissionPostgreSQL = `INSERT INTO {{prefix}}authz_role_permissions (
	role_id,
	permission_id
) VALUES (
	$1,
	$2
)
ON CONFLICT (role_id, permission_id) DO NOTHING`

const deleteRoleHierarchyPostgreSQL = `DELETE FROM {{prefix}}authz_role_hierarchy
WHERE child_role_id = $1`

const deleteRolePermissionsPostgreSQL = `DELETE FROM {{prefix}}authz_role_permissions
WHERE role_id = $1`

const getRoleIdbyNamePostgreSQL = `SELECT
	{{prefix}}authz_roles.id,
	{{prefix}}authz_roles.archived_at
FROM {{prefix}}authz_roles
WHERE {{prefix}}authz_roles.name = $1`

const listPermissionsByNamesPostgreSQL = `SELECT
	{{prefix}}authz_permissions.id,
	{{prefix}}authz_permissions.name,
	{{prefix}}authz_permissions.description,
	{{prefix}}authz_permissions.archived_at
FROM {{prefix}}authz_permissions
WHERE {{prefix}}authz_permissions.name = ANY($1::text[])
ORDER BY {{prefix}}authz_permissions.name ASC`

const listRoleHierarchyPostgreSQL = `SELECT
	{{prefix}}authz_role_hierarchy.child_role_id,
	{{prefix}}authz_roles.id AS parent_id,
	{{prefix}}authz_roles.name AS parent_name,
	{{prefix}}authz_roles.description AS parent_description,
	{{prefix}}authz_roles.created_at AS parent_created_at,
	{{prefix}}authz_roles.last_updated_at AS parent_last_updated_at,
	{{prefix}}authz_roles.archived_at AS parent_archived_at
FROM {{prefix}}authz_role_hierarchy
JOIN {{prefix}}authz_roles ON {{prefix}}authz_role_hierarchy.parent_role_id={{prefix}}authz_roles.id
WHERE {{prefix}}authz_roles.archived_at IS NULL
ORDER BY {{prefix}}authz_role_hierarchy.child_role_id ASC`

const listRolePermissionsPostgreSQL = `SELECT
	{{prefix}}authz_role_permissions.role_id,
	{{prefix}}authz_permissions.id AS permission_id,
	{{prefix}}authz_permissions.name AS permission_name,
	{{prefix}}authz_permissions.description AS permission_description,
	{{prefix}}authz_permissions.created_at AS permission_created_at,
	{{prefix}}authz_permissions.last_updated_at AS permission_last_updated_at,
	{{prefix}}authz_permissions.archived_at AS permission_archived_at
FROM {{prefix}}authz_role_permissions
JOIN {{prefix}}authz_permissions ON {{prefix}}authz_role_permissions.permission_id={{prefix}}authz_permissions.id
WHERE {{prefix}}authz_permissions.archived_at IS NULL
ORDER BY {{prefix}}authz_role_permissions.role_id ASC`

const listRolesPostgreSQL = `SELECT
	{{prefix}}authz_roles.id,
	{{prefix}}authz_roles.name,
	{{prefix}}authz_roles.description,
	{{prefix}}authz_roles.created_at,
	{{prefix}}authz_roles.last_updated_at,
	{{prefix}}authz_roles.archived_at
FROM {{prefix}}authz_roles
WHERE {{prefix}}authz_roles.archived_at IS NULL
ORDER BY {{prefix}}authz_roles.name ASC`

const listRolesByNamesPostgreSQL = `SELECT
	{{prefix}}authz_roles.id,
	{{prefix}}authz_roles.name,
	{{prefix}}authz_roles.description,
	{{prefix}}authz_roles.archived_at
FROM {{prefix}}authz_roles
WHERE {{prefix}}authz_roles.name = ANY($1::text[])
ORDER BY {{prefix}}authz_roles.name ASC`

const resolvePermissionsForRolesPostgreSQL = `
WITH RECURSIVE role_closure AS (
	SELECT
		{{prefix}}authz_roles.id
	FROM {{prefix}}authz_roles
	WHERE {{prefix}}authz_roles.archived_at IS NULL
		AND {{prefix}}authz_roles.name = ANY($1::text[])
	UNION
	SELECT
		{{prefix}}authz_roles.id
	FROM role_closure
	JOIN {{prefix}}authz_role_hierarchy ON role_closure.id={{prefix}}authz_role_hierarchy.child_role_id
	JOIN {{prefix}}authz_roles ON {{prefix}}authz_role_hierarchy.parent_role_id={{prefix}}authz_roles.id
	WHERE {{prefix}}authz_roles.archived_at IS NULL
)
SELECT DISTINCT
	{{prefix}}authz_permissions.name
FROM role_closure
JOIN {{prefix}}authz_role_permissions ON role_closure.id={{prefix}}authz_role_permissions.role_id
JOIN {{prefix}}authz_permissions ON {{prefix}}authz_role_permissions.permission_id={{prefix}}authz_permissions.id
WHERE {{prefix}}authz_permissions.archived_at IS NULL
ORDER BY {{prefix}}authz_permissions.name`

const upsertPermissionPostgreSQL = `INSERT INTO {{prefix}}authz_permissions (
	id,
	name,
	description
) VALUES (
	$1,
	$2,
	$3
)
ON CONFLICT (name) DO UPDATE SET
	description = EXCLUDED.description,
	archived_at = NULL,
	last_updated_at = CURRENT_TIMESTAMP`

const upsertRolePostgreSQL = `INSERT INTO {{prefix}}authz_roles (
	id,
	name,
	description
) VALUES (
	$1,
	$2,
	$3
)
ON CONFLICT (name) DO UPDATE SET
	description = EXCLUDED.description,
	archived_at = NULL,
	last_updated_at = CURRENT_TIMESTAMP`

// postgresqlQueries answers every query in Querier against postgresql.
type postgresqlQueries struct {
	archiveRoleByName          string
	createRoleHierarchyEdge    string
	createRolePermission       string
	deleteRoleHierarchy        string
	deleteRolePermissions      string
	getRoleIdbyName            string
	listPermissionsByNames     string
	listRoleHierarchy          string
	listRolePermissions        string
	listRoles                  string
	listRolesByNames           string
	resolvePermissionsForRoles string
	upsertPermission           string
	upsertRole                 string
}

// newPostgreSQL returns the postgresql querier with prefix substituted into every
// table name the analyzer identified.
func newPostgreSQL(prefix string) *postgresqlQueries {
	return &postgresqlQueries{
		archiveRoleByName:          strings.ReplaceAll(archiveRoleByNamePostgreSQL, prefixMarker, prefix),
		createRoleHierarchyEdge:    strings.ReplaceAll(createRoleHierarchyEdgePostgreSQL, prefixMarker, prefix),
		createRolePermission:       strings.ReplaceAll(createRolePermissionPostgreSQL, prefixMarker, prefix),
		deleteRoleHierarchy:        strings.ReplaceAll(deleteRoleHierarchyPostgreSQL, prefixMarker, prefix),
		deleteRolePermissions:      strings.ReplaceAll(deleteRolePermissionsPostgreSQL, prefixMarker, prefix),
		getRoleIdbyName:            strings.ReplaceAll(getRoleIdbyNamePostgreSQL, prefixMarker, prefix),
		listPermissionsByNames:     strings.ReplaceAll(listPermissionsByNamesPostgreSQL, prefixMarker, prefix),
		listRoleHierarchy:          strings.ReplaceAll(listRoleHierarchyPostgreSQL, prefixMarker, prefix),
		listRolePermissions:        strings.ReplaceAll(listRolePermissionsPostgreSQL, prefixMarker, prefix),
		listRoles:                  strings.ReplaceAll(listRolesPostgreSQL, prefixMarker, prefix),
		listRolesByNames:           strings.ReplaceAll(listRolesByNamesPostgreSQL, prefixMarker, prefix),
		resolvePermissionsForRoles: strings.ReplaceAll(resolvePermissionsForRolesPostgreSQL, prefixMarker, prefix),
		upsertPermission:           strings.ReplaceAll(upsertPermissionPostgreSQL, prefixMarker, prefix),
		upsertRole:                 strings.ReplaceAll(upsertRolePostgreSQL, prefixMarker, prefix),
	}
}

// ArchiveRoleByName runs the :execrows query against postgresql.
func (q *postgresqlQueries) ArchiveRoleByName(ctx context.Context, db DBTX, arg ArchiveRoleByNameParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveRoleByName,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// CreateRoleHierarchyEdge runs the :execrows query against postgresql.
func (q *postgresqlQueries) CreateRoleHierarchyEdge(ctx context.Context, db DBTX, arg CreateRoleHierarchyEdgeParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createRoleHierarchyEdge,
		arg.ChildRoleID,
		arg.ParentRoleID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// CreateRolePermission runs the :execrows query against postgresql.
func (q *postgresqlQueries) CreateRolePermission(ctx context.Context, db DBTX, arg CreateRolePermissionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createRolePermission,
		arg.RoleID,
		arg.PermissionID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteRoleHierarchy runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteRoleHierarchy(ctx context.Context, db DBTX, arg DeleteRoleHierarchyParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteRoleHierarchy,
		arg.ChildRoleID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteRolePermissions runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteRolePermissions(ctx context.Context, db DBTX, arg DeleteRolePermissionsParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteRolePermissions,
		arg.RoleID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetRoleIDByName runs the :one query against postgresql.
func (q *postgresqlQueries) GetRoleIDByName(ctx context.Context, db DBTX, arg GetRoleIDByNameParams) (GetRoleIDByNameRow, error) {
	row := db.QueryRowContext(ctx, q.getRoleIdbyName,
		arg.Name,
	)

	var i GetRoleIDByNameRow

	err := row.Scan(
		&i.ID,
		&i.ArchivedAt,
	)

	return i, err
}

// ListPermissionsByNames runs the :many query against postgresql.
func (q *postgresqlQueries) ListPermissionsByNames(ctx context.Context, db DBTX, arg ListPermissionsByNamesParams) ([]ListPermissionsByNamesRow, error) {
	rows, err := db.QueryContext(ctx, q.listPermissionsByNames,
		arg.Names,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListPermissionsByNamesRow

	for rows.Next() {
		var i ListPermissionsByNamesRow

		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRoleHierarchy runs the :many query against postgresql.
func (q *postgresqlQueries) ListRoleHierarchy(ctx context.Context, db DBTX) ([]ListRoleHierarchyRow, error) {
	rows, err := db.QueryContext(ctx, q.listRoleHierarchy)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRoleHierarchyRow

	for rows.Next() {
		var i ListRoleHierarchyRow

		if err := rows.Scan(
			&i.ChildRoleID,
			&i.ParentID,
			&i.ParentName,
			&i.ParentDescription,
			&i.ParentCreatedAt,
			&i.ParentLastUpdatedAt,
			&i.ParentArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRolePermissions runs the :many query against postgresql.
func (q *postgresqlQueries) ListRolePermissions(ctx context.Context, db DBTX) ([]ListRolePermissionsRow, error) {
	rows, err := db.QueryContext(ctx, q.listRolePermissions)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRolePermissionsRow

	for rows.Next() {
		var i ListRolePermissionsRow

		if err := rows.Scan(
			&i.RoleID,
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionDescription,
			&i.PermissionCreatedAt,
			&i.PermissionLastUpdatedAt,
			&i.PermissionArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRoles runs the :many query against postgresql.
func (q *postgresqlQueries) ListRoles(ctx context.Context, db DBTX) ([]ListRolesRow, error) {
	rows, err := db.QueryContext(ctx, q.listRoles)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRolesRow

	for rows.Next() {
		var i ListRolesRow

		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRolesByNames runs the :many query against postgresql.
func (q *postgresqlQueries) ListRolesByNames(ctx context.Context, db DBTX, arg ListRolesByNamesParams) ([]ListRolesByNamesRow, error) {
	rows, err := db.QueryContext(ctx, q.listRolesByNames,
		arg.Names,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRolesByNamesRow

	for rows.Next() {
		var i ListRolesByNamesRow

		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ResolvePermissionsForRoles runs the :many query against postgresql.
func (q *postgresqlQueries) ResolvePermissionsForRoles(ctx context.Context, db DBTX, arg ResolvePermissionsForRolesParams) ([]ResolvePermissionsForRolesRow, error) {
	rows, err := db.QueryContext(ctx, q.resolvePermissionsForRoles,
		arg.Names,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ResolvePermissionsForRolesRow

	for rows.Next() {
		var i ResolvePermissionsForRolesRow

		if err := rows.Scan(
			&i.Name,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// UpsertPermission runs the :exec query against postgresql.
func (q *postgresqlQueries) UpsertPermission(ctx context.Context, db DBTX, arg UpsertPermissionParams) error {
	_, err := db.ExecContext(ctx, q.upsertPermission,
		arg.ID,
		arg.Name,
		arg.Description,
	)

	return err
}

// UpsertRole runs the :exec query against postgresql.
func (q *postgresqlQueries) UpsertRole(ctx context.Context, db DBTX, arg UpsertRoleParams) error {
	_, err := db.ExecContext(ctx, q.upsertRole,
		arg.ID,
		arg.Name,
		arg.Description,
	)

	return err
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		Name string
	}(ArchiveRoleByNameParams{})
	_ = struct {
		ChildRoleID  string
		ParentRoleID string
	}(CreateRoleHierarchyEdgeParams{})
	_ = struct {
		RoleID       string
		PermissionID string
	}(CreateRolePermissionParams{})
	_ = struct {
		ChildRoleID string
	}(DeleteRoleHierarchyParams{})
	_ = struct {
		RoleID string
	}(DeleteRolePermissionsParams{})
	_ = struct {
		Name string
	}(GetRoleIDByNameParams{})
	_ = struct {
		ID         string
		ArchivedAt *time.Time
	}(GetRoleIDByNameRow{})
	_ = struct {
		Names []string
	}(ListPermissionsByNamesParams{})
	_ = struct {
		ID          string
		Name        string
		Description string
		ArchivedAt  *time.Time
	}(ListPermissionsByNamesRow{})
	_ = struct {
		ChildRoleID         string
		ParentID            string
		ParentName          string
		ParentDescription   string
		ParentCreatedAt     time.Time
		ParentLastUpdatedAt *time.Time
		ParentArchivedAt    *time.Time
	}(ListRoleHierarchyRow{})
	_ = struct {
		RoleID                  string
		PermissionID            string
		PermissionName          string
		PermissionDescription   string
		PermissionCreatedAt     time.Time
		PermissionLastUpdatedAt *time.Time
		PermissionArchivedAt    *time.Time
	}(ListRolePermissionsRow{})
	_ = struct {
		ID            string
		Name          string
		Description   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(ListRolesRow{})
	_ = struct {
		Names []string
	}(ListRolesByNamesParams{})
	_ = struct {
		ID          string
		Name        string
		Description string
		ArchivedAt  *time.Time
	}(ListRolesByNamesRow{})
	_ = struct {
		Names []string
	}(ResolvePermissionsForRolesParams{})
	_ = struct {
		Name string
	}(ResolvePermissionsForRolesRow{})
	_ = struct {
		ID          string
		Name        string
		Description string
	}(UpsertPermissionParams{})
	_ = struct {
		ID          string
		Name        string
		Description string
	}(UpsertRoleParams{})
)
