// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package authorizationdb

import (
	"context"
	"strings"
	"time"
)

const archiveRoleByNameMySQL = `UPDATE {{prefix}}authz_roles SET
	archived_at = CURRENT_TIMESTAMP(6)
WHERE archived_at IS NULL
	AND name = ?`

const createRoleHierarchyEdgeMySQL = `INSERT IGNORE INTO {{prefix}}authz_role_hierarchy (
	child_role_id,
	parent_role_id
) VALUES (
	?,
	?
)`

const createRolePermissionMySQL = `INSERT IGNORE INTO {{prefix}}authz_role_permissions (
	role_id,
	permission_id
) VALUES (
	?,
	?
)`

const deleteRoleHierarchyMySQL = `DELETE FROM {{prefix}}authz_role_hierarchy
WHERE child_role_id = ?`

const deleteRolePermissionsMySQL = `DELETE FROM {{prefix}}authz_role_permissions
WHERE role_id = ?`

const getRoleIdbyNameMySQL = `SELECT
	{{prefix}}authz_roles.id,
	{{prefix}}authz_roles.archived_at
FROM {{prefix}}authz_roles
WHERE {{prefix}}authz_roles.name = ?`

const listPermissionsByNamesMySQL = `SELECT
	{{prefix}}authz_permissions.id,
	{{prefix}}authz_permissions.name,
	{{prefix}}authz_permissions.description,
	{{prefix}}authz_permissions.archived_at
FROM {{prefix}}authz_permissions
WHERE {{prefix}}authz_permissions.name IN (/*SLICE:names*/?)
ORDER BY {{prefix}}authz_permissions.name ASC`

const listRoleHierarchyMySQL = `SELECT
	{{prefix}}authz_role_hierarchy.child_role_id,
	{{prefix}}authz_roles.id AS parent_id,
	{{prefix}}authz_roles.name AS parent_name,
	{{prefix}}authz_roles.description AS parent_description,
	{{prefix}}authz_roles.created_at AS parent_created_at,
	{{prefix}}authz_roles.last_updated_at AS parent_last_updated_at,
	{{prefix}}authz_roles.archived_at AS parent_archived_at
FROM {{prefix}}authz_role_hierarchy
JOIN {{prefix}}authz_roles ON {{prefix}}authz_role_hierarchy.parent_role_id={{prefix}}authz_roles.id
WHERE {{prefix}}authz_roles.archived_at IS NULL
ORDER BY {{prefix}}authz_role_hierarchy.child_role_id ASC`

const listRolePermissionsMySQL = `SELECT
	{{prefix}}authz_role_permissions.role_id,
	{{prefix}}authz_permissions.id AS permission_id,
	{{prefix}}authz_permissions.name AS permission_name,
	{{prefix}}authz_permissions.description AS permission_description,
	{{prefix}}authz_permissions.created_at AS permission_created_at,
	{{prefix}}authz_permissions.last_updated_at AS permission_last_updated_at,
	{{prefix}}authz_permissions.archived_at AS permission_archived_at
FROM {{prefix}}authz_role_permissions
JOIN {{prefix}}authz_permissions ON {{prefix}}authz_role_permissions.permission_id={{prefix}}authz_permissions.id
WHERE {{prefix}}authz_permissions.archived_at IS NULL
ORDER BY {{prefix}}authz_role_permissions.role_id ASC`

const listRolesMySQL = `SELECT
	{{prefix}}authz_roles.id,
	{{prefix}}authz_roles.name,
	{{prefix}}authz_roles.description,
	{{prefix}}authz_roles.created_at,
	{{prefix}}authz_roles.last_updated_at,
	{{prefix}}authz_roles.archived_at
FROM {{prefix}}authz_roles
WHERE {{prefix}}authz_roles.archived_at IS NULL
ORDER BY {{prefix}}authz_roles.name ASC`

const listRolesByNamesMySQL = `SELECT
	{{prefix}}authz_roles.id,
	{{prefix}}authz_roles.name,
	{{prefix}}authz_roles.description,
	{{prefix}}authz_roles.archived_at
FROM {{prefix}}authz_roles
WHERE {{prefix}}authz_roles.name IN (/*SLICE:names*/?)
ORDER BY {{prefix}}authz_roles.name ASC`

const resolvePermissionsForRolesMySQL = `
WITH RECURSIVE role_closure AS (
	SELECT
		{{prefix}}authz_roles.id
	FROM {{prefix}}authz_roles
	WHERE {{prefix}}authz_roles.archived_at IS NULL
		AND {{prefix}}authz_roles.name IN (/*SLICE:names*/?)
	UNION
	SELECT
		{{prefix}}authz_roles.id
	FROM role_closure
	JOIN {{prefix}}authz_role_hierarchy ON role_closure.id={{prefix}}authz_role_hierarchy.child_role_id
	JOIN {{prefix}}authz_roles ON {{prefix}}authz_role_hierarchy.parent_role_id={{prefix}}authz_roles.id
	WHERE {{prefix}}authz_roles.archived_at IS NULL
)
SELECT DISTINCT
	{{prefix}}authz_permissions.name
FROM role_closure
JOIN {{prefix}}authz_role_permissions ON role_closure.id={{prefix}}authz_role_permissions.role_id
JOIN {{prefix}}authz_permissions ON {{prefix}}authz_role_permissions.permission_id={{prefix}}authz_permissions.id
WHERE {{prefix}}authz_permissions.archived_at IS NULL
ORDER BY {{prefix}}authz_permissions.name`

const upsertPermissionMySQL = `INSERT INTO {{prefix}}authz_permissions (
	id,
	name,
	description
) VALUES (
	?,
	?,
	?
)
ON DUPLICATE KEY UPDATE
	description = VALUES(description),
	archived_at = NULL,
	last_updated_at = CURRENT_TIMESTAMP(6)`

const upsertRoleMySQL = `INSERT INTO {{prefix}}authz_roles (
	id,
	name,
	description
) VALUES (
	?,
	?,
	?
)
ON DUPLICATE KEY UPDATE
	description = VALUES(description),
	archived_at = NULL,
	last_updated_at = CURRENT_TIMESTAMP(6)`

// mysqlQueries answers every query in Querier against mysql.
type mysqlQueries struct {
	archiveRoleByName          string
	createRoleHierarchyEdge    string
	createRolePermission       string
	deleteRoleHierarchy        string
	deleteRolePermissions      string
	getRoleIdbyName            string
	listPermissionsByNames     string
	listRoleHierarchy          string
	listRolePermissions        string
	listRoles                  string
	listRolesByNames           string
	resolvePermissionsForRoles string
	upsertPermission           string
	upsertRole                 string
}

// newMySQL returns the mysql querier with prefix substituted into every
// table name the analyzer identified.
func newMySQL(prefix string) *mysqlQueries {
	return &mysqlQueries{
		archiveRoleByName:          strings.ReplaceAll(archiveRoleByNameMySQL, prefixMarker, prefix),
		createRoleHierarchyEdge:    strings.ReplaceAll(createRoleHierarchyEdgeMySQL, prefixMarker, prefix),
		createRolePermission:       strings.ReplaceAll(createRolePermissionMySQL, prefixMarker, prefix),
		deleteRoleHierarchy:        strings.ReplaceAll(deleteRoleHierarchyMySQL, prefixMarker, prefix),
		deleteRolePermissions:      strings.ReplaceAll(deleteRolePermissionsMySQL, prefixMarker, prefix),
		getRoleIdbyName:            strings.ReplaceAll(getRoleIdbyNameMySQL, prefixMarker, prefix),
		listPermissionsByNames:     strings.ReplaceAll(listPermissionsByNamesMySQL, prefixMarker, prefix),
		listRoleHierarchy:          strings.ReplaceAll(listRoleHierarchyMySQL, prefixMarker, prefix),
		listRolePermissions:        strings.ReplaceAll(listRolePermissionsMySQL, prefixMarker, prefix),
		listRoles:                  strings.ReplaceAll(listRolesMySQL, prefixMarker, prefix),
		listRolesByNames:           strings.ReplaceAll(listRolesByNamesMySQL, prefixMarker, prefix),
		resolvePermissionsForRoles: strings.ReplaceAll(resolvePermissionsForRolesMySQL, prefixMarker, prefix),
		upsertPermission:           strings.ReplaceAll(upsertPermissionMySQL, prefixMarker, prefix),
		upsertRole:                 strings.ReplaceAll(upsertRoleMySQL, prefixMarker, prefix),
	}
}

// ArchiveRoleByName runs the :execrows query against mysql.
func (q *mysqlQueries) ArchiveRoleByName(ctx context.Context, db DBTX, arg ArchiveRoleByNameParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveRoleByName,
		arg.Name,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// CreateRoleHierarchyEdge runs the :execrows query against mysql.
func (q *mysqlQueries) CreateRoleHierarchyEdge(ctx context.Context, db DBTX, arg CreateRoleHierarchyEdgeParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createRoleHierarchyEdge,
		arg.ChildRoleID,
		arg.ParentRoleID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// CreateRolePermission runs the :execrows query against mysql.
func (q *mysqlQueries) CreateRolePermission(ctx context.Context, db DBTX, arg CreateRolePermissionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.createRolePermission,
		arg.RoleID,
		arg.PermissionID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteRoleHierarchy runs the :execrows query against mysql.
func (q *mysqlQueries) DeleteRoleHierarchy(ctx context.Context, db DBTX, arg DeleteRoleHierarchyParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteRoleHierarchy,
		arg.ChildRoleID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteRolePermissions runs the :execrows query against mysql.
func (q *mysqlQueries) DeleteRolePermissions(ctx context.Context, db DBTX, arg DeleteRolePermissionsParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteRolePermissions,
		arg.RoleID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetRoleIDByName runs the :one query against mysql.
func (q *mysqlQueries) GetRoleIDByName(ctx context.Context, db DBTX, arg GetRoleIDByNameParams) (GetRoleIDByNameRow, error) {
	row := db.QueryRowContext(ctx, q.getRoleIdbyName,
		arg.Name,
	)

	var i GetRoleIDByNameRow

	err := row.Scan(
		&i.ID,
		&i.ArchivedAt,
	)

	return i, err
}

// ListPermissionsByNames runs the :many query against mysql.
func (q *mysqlQueries) ListPermissionsByNames(ctx context.Context, db DBTX, arg ListPermissionsByNamesParams) ([]ListPermissionsByNamesRow, error) {
	query := q.listPermissionsByNames

	args := make([]any, 0, len(arg.Names))

	query = strings.Replace(query, "/*SLICE:names*/?", slicePlaceholders("?", len(arg.Names)), 1)

	for _, v := range arg.Names {
		args = append(args, v)
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListPermissionsByNamesRow

	for rows.Next() {
		var i ListPermissionsByNamesRow

		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRoleHierarchy runs the :many query against mysql.
func (q *mysqlQueries) ListRoleHierarchy(ctx context.Context, db DBTX) ([]ListRoleHierarchyRow, error) {
	rows, err := db.QueryContext(ctx, q.listRoleHierarchy)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRoleHierarchyRow

	for rows.Next() {
		var i ListRoleHierarchyRow

		if err := rows.Scan(
			&i.ChildRoleID,
			&i.ParentID,
			&i.ParentName,
			&i.ParentDescription,
			&i.ParentCreatedAt,
			&i.ParentLastUpdatedAt,
			&i.ParentArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRolePermissions runs the :many query against mysql.
func (q *mysqlQueries) ListRolePermissions(ctx context.Context, db DBTX) ([]ListRolePermissionsRow, error) {
	rows, err := db.QueryContext(ctx, q.listRolePermissions)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRolePermissionsRow

	for rows.Next() {
		var i ListRolePermissionsRow

		if err := rows.Scan(
			&i.RoleID,
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionDescription,
			&i.PermissionCreatedAt,
			&i.PermissionLastUpdatedAt,
			&i.PermissionArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRoles runs the :many query against mysql.
func (q *mysqlQueries) ListRoles(ctx context.Context, db DBTX) ([]ListRolesRow, error) {
	rows, err := db.QueryContext(ctx, q.listRoles)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRolesRow

	for rows.Next() {
		var i ListRolesRow

		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListRolesByNames runs the :many query against mysql.
func (q *mysqlQueries) ListRolesByNames(ctx context.Context, db DBTX, arg ListRolesByNamesParams) ([]ListRolesByNamesRow, error) {
	query := q.listRolesByNames

	args := make([]any, 0, len(arg.Names))

	query = strings.Replace(query, "/*SLICE:names*/?", slicePlaceholders("?", len(arg.Names)), 1)

	for _, v := range arg.Names {
		args = append(args, v)
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListRolesByNamesRow

	for rows.Next() {
		var i ListRolesByNamesRow

		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ResolvePermissionsForRoles runs the :many query against mysql.
func (q *mysqlQueries) ResolvePermissionsForRoles(ctx context.Context, db DBTX, arg ResolvePermissionsForRolesParams) ([]ResolvePermissionsForRolesRow, error) {
	query := q.resolvePermissionsForRoles

	args := make([]any, 0, len(arg.Names))

	query = strings.Replace(query, "/*SLICE:names*/?", slicePlaceholders("?", len(arg.Names)), 1)

	for _, v := range arg.Names {
		args = append(args, v)
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ResolvePermissionsForRolesRow

	for rows.Next() {
		var i ResolvePermissionsForRolesRow

		if err := rows.Scan(
			&i.Name,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// UpsertPermission runs the :exec query against mysql.
func (q *mysqlQueries) UpsertPermission(ctx context.Context, db DBTX, arg UpsertPermissionParams) error {
	_, err := db.ExecContext(ctx, q.upsertPermission,
		arg.ID,
		arg.Name,
		arg.Description,
	)

	return err
}

// UpsertRole runs the :exec query against mysql.
func (q *mysqlQueries) UpsertRole(ctx context.Context, db DBTX, arg UpsertRoleParams) error {
	_, err := db.ExecContext(ctx, q.upsertRole,
		arg.ID,
		arg.Name,
		arg.Description,
	)

	return err
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		Name string
	}(ArchiveRoleByNameParams{})
	_ = struct {
		ChildRoleID  string
		ParentRoleID string
	}(CreateRoleHierarchyEdgeParams{})
	_ = struct {
		RoleID       string
		PermissionID string
	}(CreateRolePermissionParams{})
	_ = struct {
		ChildRoleID string
	}(DeleteRoleHierarchyParams{})
	_ = struct {
		RoleID string
	}(DeleteRolePermissionsParams{})
	_ = struct {
		Name string
	}(GetRoleIDByNameParams{})
	_ = struct {
		ID         string
		ArchivedAt *time.Time
	}(GetRoleIDByNameRow{})
	_ = struct {
		Names []string
	}(ListPermissionsByNamesParams{})
	_ = struct {
		ID          string
		Name        string
		Description string
		ArchivedAt  *time.Time
	}(ListPermissionsByNamesRow{})
	_ = struct {
		ChildRoleID         string
		ParentID            string
		ParentName          string
		ParentDescription   string
		ParentCreatedAt     time.Time
		ParentLastUpdatedAt *time.Time
		ParentArchivedAt    *time.Time
	}(ListRoleHierarchyRow{})
	_ = struct {
		RoleID                  string
		PermissionID            string
		PermissionName          string
		PermissionDescription   string
		PermissionCreatedAt     time.Time
		PermissionLastUpdatedAt *time.Time
		PermissionArchivedAt    *time.Time
	}(ListRolePermissionsRow{})
	_ = struct {
		ID            string
		Name          string
		Description   string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(ListRolesRow{})
	_ = struct {
		Names []string
	}(ListRolesByNamesParams{})
	_ = struct {
		ID          string
		Name        string
		Description string
		ArchivedAt  *time.Time
	}(ListRolesByNamesRow{})
	_ = struct {
		Names []string
	}(ResolvePermissionsForRolesParams{})
	_ = struct {
		Name string
	}(ResolvePermissionsForRolesRow{})
	_ = struct {
		ID          string
		Name        string
		Description string
	}(UpsertPermissionParams{})
	_ = struct {
		ID          string
		Name        string
		Description string
	}(UpsertRoleParams{})
)
