// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package passwordresetmock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/platform-go/v14/authentication/passwordreset"

	"github.com/primandproper/primitives-go/database"
	"github.com/primandproper/primitives-go/tenancy"
)

// Ensure, that StoreMock does implement passwordreset.Store.
// If this is not the case, regenerate this file with moq.
var _ passwordreset.Store = &StoreMock{}

// StoreMock is a mock implementation of passwordreset.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked passwordreset.Store
//		mockedStore := &StoreMock{
//			ConsumeFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, secret string) (*passwordreset.Token, error) {
//				panic("mock out the Consume method")
//			},
//			IssueFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, userID string, ttl time.Duration) (*passwordreset.Issuance, error) {
//				panic("mock out the Issue method")
//			},
//			RevokeForUserFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, userID string) (int64, error) {
//				panic("mock out the RevokeForUser method")
//			},
//			VerifyFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, secret string) (*passwordreset.Token, error) {
//				panic("mock out the Verify method")
//			},
//		}
//
//		// use mockedStore in code that requires passwordreset.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// ConsumeFunc mocks the Consume method.
	ConsumeFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, secret string) (*passwordreset.Token, error)

	// IssueFunc mocks the Issue method.
	IssueFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, userID string, ttl time.Duration) (*passwordreset.Issuance, error)

	// RevokeForUserFunc mocks the RevokeForUser method.
	RevokeForUserFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, userID string) (int64, error)

	// VerifyFunc mocks the Verify method.
	VerifyFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, secret string) (*passwordreset.Token, error)

	// calls tracks calls to the methods.
	calls struct {
		// Consume holds details about calls to the Consume method.
		Consume []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Secret is the secret argument value.
			Secret string
		}
		// Issue holds details about calls to the Issue method.
		Issue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// UserID is the userID argument value.
			UserID string
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// RevokeForUser holds details about calls to the RevokeForUser method.
		RevokeForUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// UserID is the userID argument value.
			UserID string
		}
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Secret is the secret argument value.
			Secret string
		}
	}
	lockConsume       sync.RWMutex
	lockIssue         sync.RWMutex
	lockRevokeForUser sync.RWMutex
	lockVerify        sync.RWMutex
}

// Consume calls ConsumeFunc.
func (mock *StoreMock) Consume(ctx context.Context, tx database.Tx, scope tenancy.Scope, secret string) (*passwordreset.Token, error) {
	if mock.ConsumeFunc == nil {
		panic("StoreMock.ConsumeFunc: method is nil but Store.Consume was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Tx     database.Tx
		Scope  tenancy.Scope
		Secret string
	}{
		Ctx:    ctx,
		Tx:     tx,
		Scope:  scope,
		Secret: secret,
	}
	mock.lockConsume.Lock()
	mock.calls.Consume = append(mock.calls.Consume, callInfo)
	mock.lockConsume.Unlock()
	return mock.ConsumeFunc(ctx, tx, scope, secret)
}

// ConsumeCalls gets all the calls that were made to Consume.
// Check the length with:
//
//	len(mockedStore.ConsumeCalls())
func (mock *StoreMock) ConsumeCalls() []struct {
	Ctx    context.Context
	Tx     database.Tx
	Scope  tenancy.Scope
	Secret string
} {
	var calls []struct {
		Ctx    context.Context
		Tx     database.Tx
		Scope  tenancy.Scope
		Secret string
	}
	mock.lockConsume.RLock()
	calls = mock.calls.Consume
	mock.lockConsume.RUnlock()
	return calls
}

// Issue calls IssueFunc.
func (mock *StoreMock) Issue(ctx context.Context, tx database.Tx, scope tenancy.Scope, userID string, ttl time.Duration) (*passwordreset.Issuance, error) {
	if mock.IssueFunc == nil {
		panic("StoreMock.IssueFunc: method is nil but Store.Issue was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Tx     database.Tx
		Scope  tenancy.Scope
		UserID string
		TTL    time.Duration
	}{
		Ctx:    ctx,
		Tx:     tx,
		Scope:  scope,
		UserID: userID,
		TTL:    ttl,
	}
	mock.lockIssue.Lock()
	mock.calls.Issue = append(mock.calls.Issue, callInfo)
	mock.lockIssue.Unlock()
	return mock.IssueFunc(ctx, tx, scope, userID, ttl)
}

// IssueCalls gets all the calls that were made to Issue.
// Check the length with:
//
//	len(mockedStore.IssueCalls())
func (mock *StoreMock) IssueCalls() []struct {
	Ctx    context.Context
	Tx     database.Tx
	Scope  tenancy.Scope
	UserID string
	TTL    time.Duration
} {
	var calls []struct {
		Ctx    context.Context
		Tx     database.Tx
		Scope  tenancy.Scope
		UserID string
		TTL    time.Duration
	}
	mock.lockIssue.RLock()
	calls = mock.calls.Issue
	mock.lockIssue.RUnlock()
	return calls
}

// RevokeForUser calls RevokeForUserFunc.
func (mock *StoreMock) RevokeForUser(ctx context.Context, tx database.Tx, scope tenancy.Scope, userID string) (int64, error) {
	if mock.RevokeForUserFunc == nil {
		panic("StoreMock.RevokeForUserFunc: method is nil but Store.RevokeForUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Tx     database.Tx
		Scope  tenancy.Scope
		UserID string
	}{
		Ctx:    ctx,
		Tx:     tx,
		Scope:  scope,
		UserID: userID,
	}
	mock.lockRevokeForUser.Lock()
	mock.calls.RevokeForUser = append(mock.calls.RevokeForUser, callInfo)
	mock.lockRevokeForUser.Unlock()
	return mock.RevokeForUserFunc(ctx, tx, scope, userID)
}

// RevokeForUserCalls gets all the calls that were made to RevokeForUser.
// Check the length with:
//
//	len(mockedStore.RevokeForUserCalls())
func (mock *StoreMock) RevokeForUserCalls() []struct {
	Ctx    context.Context
	Tx     database.Tx
	Scope  tenancy.Scope
	UserID string
} {
	var calls []struct {
		Ctx    context.Context
		Tx     database.Tx
		Scope  tenancy.Scope
		UserID string
	}
	mock.lockRevokeForUser.RLock()
	calls = mock.calls.RevokeForUser
	mock.lockRevokeForUser.RUnlock()
	return calls
}

// Verify calls VerifyFunc.
func (mock *StoreMock) Verify(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, secret string) (*passwordreset.Token, error) {
	if mock.VerifyFunc == nil {
		panic("StoreMock.VerifyFunc: method is nil but Store.Verify was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Q      database.SQLQueryExecutor
		Scope  tenancy.Scope
		Secret string
	}{
		Ctx:    ctx,
		Q:      q,
		Scope:  scope,
		Secret: secret,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(ctx, q, scope, secret)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedStore.VerifyCalls())
func (mock *StoreMock) VerifyCalls() []struct {
	Ctx    context.Context
	Q      database.SQLQueryExecutor
	Scope  tenancy.Scope
	Secret string
} {
	var calls []struct {
		Ctx    context.Context
		Q      database.SQLQueryExecutor
		Scope  tenancy.Scope
		Secret string
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}
