// Package primandproper.platform.passkeys.v1 is the wire schema for passkeys:
// enrolling one, signing in with one, and the list and archive a settings page
// offers.
//
// This file is shipped inside the published Go module, and it is the file
// itself that is shipped, as signin.proto is. A consumer puts the module's
// proto directories on protoc's path and imports it by its canonical name:
//
//	PLATFORM_PROTO := $(shell go list -m -f '{{.Dir}}' github.com/primandproper/platform-go/v15)
//
//	protoc --proto_path proto/ \
//	    --proto_path $(PLATFORM_PROTO)/authentication/passkeys/proto \
//	    --proto_path $(PLATFORM_PROTO)/authentication/signin/proto \
//	    --proto_path $(PLATFORM_PROTO)/identity/proto \
//	    --proto_path $(PLATFORM_PROTO)/filtering/proto \
//	    --go_opt=Mprimandproper/platform/passkeys/v1/passkeys.proto=github.com/primandproper/platform-go/v15/authentication/passkeys/passkeyspb \
//	    --go_opt=Mprimandproper/platform/signin/v1/signin.proto=github.com/primandproper/platform-go/v15/authentication/signin/signinpb \
//	    $(CONSUMER_PROTO_FILES)
//
// Go links against the bindings in
// github.com/primandproper/platform-go/v15/authentication/passkeys/passkeyspb.
//
// Field numbers are the compatibility promise. Numbers are never reused and
// never repurposed: a field that goes away is reserved.
//
// # The token is sign-in's
//
// FinishLogin answers with signin.v1's IssuedToken, not a message of its own.
// A passkey is another way to prove who somebody is, and what it proves them
// into is the same sign-in a password proves them into: the same lifetimes,
// the same claims, the same refresh token family, the same ExchangeRefreshToken
// and SignOut. A second token message would be a second token stack, which is
// the state this schema exists to end.
//
// # The ceremony travels as JSON
//
// Every begin answers with the options a browser hands to
// navigator.credentials.create or navigator.credentials.get, and every finish
// takes what the browser handed back, both as the JSON the WebAuthn
// specification defines, carried in a bytes field. They are not re-described
// here as messages: the specification owns their shape, it adds fields, and a
// relying party that re-encoded them would be one more place for a field to be
// dropped on the way to a browser that needed it. The options are exactly what
// github.com/go-webauthn/webauthn renders — a publicKey member, base64url for
// every binary value — which is what a browser's parseCreationOptionsFromJSON
// and parseRequestOptionsFromJSON read.
//
// # What is not here, and why
//
// No scope field, anywhere, and the name is reserved so there cannot be one.
// The login half is anonymous, so its scope comes off the connection exactly
// as sign-in's does, and a field would be one an anonymous caller fills in.
//
// No user field on the self-service RPCs. Enrolling, listing and archiving are
// about the caller and nobody else, so the subject comes off the principal,
// and a request that could name somebody would be a request that could add a
// way into their account.
//
// No public key and no sign count on a Passkey. Neither is a secret, and
// neither is anything a settings page renders; the sign count in particular is
// the relying party's clone detection, and a client that could read it would
// be reading the one number an attacker with a cloned key would want.
//
// No separate discoverable RPCs. A login that names no username is the
// discoverable one — the passkey the person chooses names them — and it is the
// same two RPCs with the field empty. A username sent to a deployment that
// offers only the discoverable login is refused as a request to correct.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: primandproper/platform/passkeys/v1/passkeys.proto

package passkeyspb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PasskeysService_BeginRegistration_FullMethodName  = "/primandproper.platform.passkeys.v1.PasskeysService/BeginRegistration"
	PasskeysService_FinishRegistration_FullMethodName = "/primandproper.platform.passkeys.v1.PasskeysService/FinishRegistration"
	PasskeysService_BeginLogin_FullMethodName         = "/primandproper.platform.passkeys.v1.PasskeysService/BeginLogin"
	PasskeysService_FinishLogin_FullMethodName        = "/primandproper.platform.passkeys.v1.PasskeysService/FinishLogin"
	PasskeysService_AdminFinishLogin_FullMethodName   = "/primandproper.platform.passkeys.v1.PasskeysService/AdminFinishLogin"
	PasskeysService_ListPasskeys_FullMethodName       = "/primandproper.platform.passkeys.v1.PasskeysService/ListPasskeys"
	PasskeysService_ArchivePasskey_FullMethodName     = "/primandproper.platform.passkeys.v1.PasskeysService/ArchivePasskey"
)

// PasskeysServiceClient is the client API for PasskeysService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasskeysServiceClient interface {
	// Enrolling a passkey on the caller's own account.
	BeginRegistration(ctx context.Context, in *BeginRegistrationRequest, opts ...grpc.CallOption) (*BeginRegistrationResponse, error)
	FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*FinishRegistrationResponse, error)
	// Signing in with one. Both are anonymous.
	BeginLogin(ctx context.Context, in *BeginLoginRequest, opts ...grpc.CallOption) (*BeginLoginResponse, error)
	FinishLogin(ctx context.Context, in *FinishLoginRequest, opts ...grpc.CallOption) (*FinishLoginResponse, error)
	// Signing an operator in with one: FinishLogin through the administrative
	// door, anonymous like it. The token carries the administrative claim and
	// lifetimes, and a subject who holds no administrative role is refused only
	// after the assertion is proven, so the role is not an oracle.
	AdminFinishLogin(ctx context.Context, in *AdminFinishLoginRequest, opts ...grpc.CallOption) (*AdminFinishLoginResponse, error)
	// The settings page.
	ListPasskeys(ctx context.Context, in *ListPasskeysRequest, opts ...grpc.CallOption) (*ListPasskeysResponse, error)
	ArchivePasskey(ctx context.Context, in *ArchivePasskeyRequest, opts ...grpc.CallOption) (*ArchivePasskeyResponse, error)
}

type passkeysServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPasskeysServiceClient(cc grpc.ClientConnInterface) PasskeysServiceClient {
	return &passkeysServiceClient{cc}
}

func (c *passkeysServiceClient) BeginRegistration(ctx context.Context, in *BeginRegistrationRequest, opts ...grpc.CallOption) (*BeginRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginRegistrationResponse)
	err := c.cc.Invoke(ctx, PasskeysService_BeginRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysServiceClient) FinishRegistration(ctx context.Context, in *FinishRegistrationRequest, opts ...grpc.CallOption) (*FinishRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishRegistrationResponse)
	err := c.cc.Invoke(ctx, PasskeysService_FinishRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysServiceClient) BeginLogin(ctx context.Context, in *BeginLoginRequest, opts ...grpc.CallOption) (*BeginLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginLoginResponse)
	err := c.cc.Invoke(ctx, PasskeysService_BeginLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysServiceClient) FinishLogin(ctx context.Context, in *FinishLoginRequest, opts ...grpc.CallOption) (*FinishLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishLoginResponse)
	err := c.cc.Invoke(ctx, PasskeysService_FinishLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysServiceClient) AdminFinishLogin(ctx context.Context, in *AdminFinishLoginRequest, opts ...grpc.CallOption) (*AdminFinishLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminFinishLoginResponse)
	err := c.cc.Invoke(ctx, PasskeysService_AdminFinishLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysServiceClient) ListPasskeys(ctx context.Context, in *ListPasskeysRequest, opts ...grpc.CallOption) (*ListPasskeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPasskeysResponse)
	err := c.cc.Invoke(ctx, PasskeysService_ListPasskeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passkeysServiceClient) ArchivePasskey(ctx context.Context, in *ArchivePasskeyRequest, opts ...grpc.CallOption) (*ArchivePasskeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchivePasskeyResponse)
	err := c.cc.Invoke(ctx, PasskeysService_ArchivePasskey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasskeysServiceServer is the server API for PasskeysService service.
// All implementations must embed UnimplementedPasskeysServiceServer
// for forward compatibility.
type PasskeysServiceServer interface {
	// Enrolling a passkey on the caller's own account.
	BeginRegistration(context.Context, *BeginRegistrationRequest) (*BeginRegistrationResponse, error)
	FinishRegistration(context.Context, *FinishRegistrationRequest) (*FinishRegistrationResponse, error)
	// Signing in with one. Both are anonymous.
	BeginLogin(context.Context, *BeginLoginRequest) (*BeginLoginResponse, error)
	FinishLogin(context.Context, *FinishLoginRequest) (*FinishLoginResponse, error)
	// Signing an operator in with one: FinishLogin through the administrative
	// door, anonymous like it. The token carries the administrative claim and
	// lifetimes, and a subject who holds no administrative role is refused only
	// after the assertion is proven, so the role is not an oracle.
	AdminFinishLogin(context.Context, *AdminFinishLoginRequest) (*AdminFinishLoginResponse, error)
	// The settings page.
	ListPasskeys(context.Context, *ListPasskeysRequest) (*ListPasskeysResponse, error)
	ArchivePasskey(context.Context, *ArchivePasskeyRequest) (*ArchivePasskeyResponse, error)
	mustEmbedUnimplementedPasskeysServiceServer()
}

// UnimplementedPasskeysServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPasskeysServiceServer struct{}

func (UnimplementedPasskeysServiceServer) BeginRegistration(context.Context, *BeginRegistrationRequest) (*BeginRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginRegistration not implemented")
}
func (UnimplementedPasskeysServiceServer) FinishRegistration(context.Context, *FinishRegistrationRequest) (*FinishRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishRegistration not implemented")
}
func (UnimplementedPasskeysServiceServer) BeginLogin(context.Context, *BeginLoginRequest) (*BeginLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginLogin not implemented")
}
func (UnimplementedPasskeysServiceServer) FinishLogin(context.Context, *FinishLoginRequest) (*FinishLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishLogin not implemented")
}
func (UnimplementedPasskeysServiceServer) AdminFinishLogin(context.Context, *AdminFinishLoginRequest) (*AdminFinishLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminFinishLogin not implemented")
}
func (UnimplementedPasskeysServiceServer) ListPasskeys(context.Context, *ListPasskeysRequest) (*ListPasskeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPasskeys not implemented")
}
func (UnimplementedPasskeysServiceServer) ArchivePasskey(context.Context, *ArchivePasskeyRequest) (*ArchivePasskeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchivePasskey not implemented")
}
func (UnimplementedPasskeysServiceServer) mustEmbedUnimplementedPasskeysServiceServer() {}
func (UnimplementedPasskeysServiceServer) testEmbeddedByValue()                         {}

// UnsafePasskeysServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasskeysServiceServer will
// result in compilation errors.
type UnsafePasskeysServiceServer interface {
	mustEmbedUnimplementedPasskeysServiceServer()
}

func RegisterPasskeysServiceServer(s grpc.ServiceRegistrar, srv PasskeysServiceServer) {
	// If the following call pancis, it indicates UnimplementedPasskeysServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PasskeysService_ServiceDesc, srv)
}

func _PasskeysService_BeginRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServiceServer).BeginRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasskeysService_BeginRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServiceServer).BeginRegistration(ctx, req.(*BeginRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasskeysService_FinishRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServiceServer).FinishRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasskeysService_FinishRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServiceServer).FinishRegistration(ctx, req.(*FinishRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasskeysService_BeginLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServiceServer).BeginLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasskeysService_BeginLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServiceServer).BeginLogin(ctx, req.(*BeginLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasskeysService_FinishLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServiceServer).FinishLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasskeysService_FinishLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServiceServer).FinishLogin(ctx, req.(*FinishLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasskeysService_AdminFinishLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminFinishLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServiceServer).AdminFinishLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasskeysService_AdminFinishLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServiceServer).AdminFinishLogin(ctx, req.(*AdminFinishLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasskeysService_ListPasskeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPasskeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServiceServer).ListPasskeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasskeysService_ListPasskeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServiceServer).ListPasskeys(ctx, req.(*ListPasskeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasskeysService_ArchivePasskey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchivePasskeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasskeysServiceServer).ArchivePasskey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasskeysService_ArchivePasskey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasskeysServiceServer).ArchivePasskey(ctx, req.(*ArchivePasskeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PasskeysService_ServiceDesc is the grpc.ServiceDesc for PasskeysService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PasskeysService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primandproper.platform.passkeys.v1.PasskeysService",
	HandlerType: (*PasskeysServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginRegistration",
			Handler:    _PasskeysService_BeginRegistration_Handler,
		},
		{
			MethodName: "FinishRegistration",
			Handler:    _PasskeysService_FinishRegistration_Handler,
		},
		{
			MethodName: "BeginLogin",
			Handler:    _PasskeysService_BeginLogin_Handler,
		},
		{
			MethodName: "FinishLogin",
			Handler:    _PasskeysService_FinishLogin_Handler,
		},
		{
			MethodName: "AdminFinishLogin",
			Handler:    _PasskeysService_AdminFinishLogin_Handler,
		},
		{
			MethodName: "ListPasskeys",
			Handler:    _PasskeysService_ListPasskeys_Handler,
		},
		{
			MethodName: "ArchivePasskey",
			Handler:    _PasskeysService_ArchivePasskey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "primandproper/platform/passkeys/v1/passkeys.proto",
}
