-- Code generated by github.com/primandproper/platform-go/v14/rbac/internal/queriesgen. DO NOT EDIT.

-- name: ResolvePermissionsForRoles :many
WITH RECURSIVE role_closure AS (
	SELECT
		authz_roles.id
	FROM authz_roles
	WHERE authz_roles.archived_at IS NULL
		AND authz_roles.name = ANY(sqlc.arg(names)::text[])
	UNION
	SELECT
		authz_roles.id
	FROM role_closure
	JOIN authz_role_hierarchy ON role_closure.id=authz_role_hierarchy.child_role_id
	JOIN authz_roles ON authz_role_hierarchy.parent_role_id=authz_roles.id
	WHERE authz_roles.archived_at IS NULL
)
SELECT DISTINCT
	authz_permissions.name
FROM role_closure
JOIN authz_role_permissions ON role_closure.id=authz_role_permissions.role_id
JOIN authz_permissions ON authz_role_permissions.permission_id=authz_permissions.id
WHERE authz_permissions.archived_at IS NULL
ORDER BY authz_permissions.name;

-- name: ListRoles :many
SELECT
	authz_roles.id,
	authz_roles.name,
	authz_roles.description,
	authz_roles.created_at,
	authz_roles.last_updated_at,
	authz_roles.archived_at
FROM authz_roles
WHERE authz_roles.archived_at IS NULL
ORDER BY authz_roles.name ASC;

-- name: ListRolePermissions :many
SELECT
	authz_role_permissions.role_id,
	authz_permissions.id AS permission_id,
	authz_permissions.name AS permission_name,
	authz_permissions.description AS permission_description,
	authz_permissions.created_at AS permission_created_at,
	authz_permissions.last_updated_at AS permission_last_updated_at,
	authz_permissions.archived_at AS permission_archived_at
FROM authz_role_permissions
JOIN authz_permissions ON authz_role_permissions.permission_id=authz_permissions.id
WHERE authz_permissions.archived_at IS NULL
ORDER BY authz_role_permissions.role_id ASC;

-- name: ListRoleHierarchy :many
SELECT
	authz_role_hierarchy.child_role_id,
	authz_roles.id AS parent_id,
	authz_roles.name AS parent_name,
	authz_roles.description AS parent_description,
	authz_roles.created_at AS parent_created_at,
	authz_roles.last_updated_at AS parent_last_updated_at,
	authz_roles.archived_at AS parent_archived_at
FROM authz_role_hierarchy
JOIN authz_roles ON authz_role_hierarchy.parent_role_id=authz_roles.id
WHERE authz_roles.archived_at IS NULL
ORDER BY authz_role_hierarchy.child_role_id ASC;

-- name: ListRolesByNames :many
SELECT
	authz_roles.id,
	authz_roles.name,
	authz_roles.description,
	authz_roles.archived_at
FROM authz_roles
WHERE authz_roles.name = ANY(sqlc.arg(names)::text[])
ORDER BY authz_roles.name ASC;

-- name: ListPermissionsByNames :many
SELECT
	authz_permissions.id,
	authz_permissions.name,
	authz_permissions.description,
	authz_permissions.archived_at
FROM authz_permissions
WHERE authz_permissions.name = ANY(sqlc.arg(names)::text[])
ORDER BY authz_permissions.name ASC;

-- name: GetRoleIDByName :one
SELECT
	authz_roles.id,
	authz_roles.archived_at
FROM authz_roles
WHERE authz_roles.name = sqlc.arg(name);

-- name: UpsertRole :exec
INSERT INTO authz_roles (
	id,
	name,
	description
) VALUES (
	sqlc.arg(id),
	sqlc.arg(name),
	sqlc.arg(description)
)
ON CONFLICT (name) DO UPDATE SET
	description = EXCLUDED.description,
	archived_at = NULL,
	last_updated_at = CURRENT_TIMESTAMP;

-- name: UpsertPermission :exec
INSERT INTO authz_permissions (
	id,
	name,
	description
) VALUES (
	sqlc.arg(id),
	sqlc.arg(name),
	sqlc.arg(description)
)
ON CONFLICT (name) DO UPDATE SET
	description = EXCLUDED.description,
	archived_at = NULL,
	last_updated_at = CURRENT_TIMESTAMP;

-- name: DeleteRolePermissions :execrows
DELETE FROM authz_role_permissions
WHERE role_id = sqlc.arg(role_id);

-- name: CreateRolePermission :execrows
INSERT INTO authz_role_permissions (
	role_id,
	permission_id
) VALUES (
	sqlc.arg(role_id),
	sqlc.arg(permission_id)
)
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- name: DeleteRoleHierarchy :execrows
DELETE FROM authz_role_hierarchy
WHERE child_role_id = sqlc.arg(child_role_id);

-- name: CreateRoleHierarchyEdge :execrows
INSERT INTO authz_role_hierarchy (
	child_role_id,
	parent_role_id
) VALUES (
	sqlc.arg(child_role_id),
	sqlc.arg(parent_role_id)
)
ON CONFLICT (child_role_id, parent_role_id) DO NOTHING;

-- name: ArchiveRoleByName :execrows
UPDATE authz_roles SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND name = sqlc.arg(name);
