-- Code generated by github.com/primandproper/platform-go/v14/dataprivacy/internal/queriesgen. DO NOT EDIT.

-- name: CreateRequest :exec
INSERT INTO dataprivacy_requests (
	id,
	request_type,
	status,
	operation_id,
	subject_id,
	subject_type,
	subject_scope,
	created_at,
	due_at,
	expires_at,
	completed_at,
	artifact_ref,
	artifact_bytes,
	deleted_rows,
	anonymized_rows,
	failures,
	retained,
	last_error,
	key_shredded_at
) VALUES (
	sqlc.arg(id),
	sqlc.arg(request_type),
	sqlc.arg(status),
	sqlc.arg(operation_id),
	sqlc.arg(subject_id),
	sqlc.arg(subject_type),
	sqlc.arg(subject_scope),
	sqlc.arg(created_at),
	sqlc.arg(due_at),
	sqlc.narg(expires_at),
	sqlc.narg(completed_at),
	sqlc.arg(artifact_ref),
	sqlc.arg(artifact_bytes),
	sqlc.arg(deleted_rows),
	sqlc.arg(anonymized_rows),
	sqlc.arg(failures),
	sqlc.arg(retained),
	sqlc.narg(last_error),
	sqlc.narg(key_shredded_at)
);

-- name: GetRequest :one
SELECT
	dataprivacy_requests.id,
	dataprivacy_requests.request_type,
	dataprivacy_requests.status,
	dataprivacy_requests.operation_id,
	dataprivacy_requests.subject_id,
	dataprivacy_requests.subject_type,
	dataprivacy_requests.subject_scope,
	dataprivacy_requests.created_at,
	dataprivacy_requests.last_updated_at,
	dataprivacy_requests.archived_at,
	dataprivacy_requests.due_at,
	dataprivacy_requests.expires_at,
	dataprivacy_requests.completed_at,
	dataprivacy_requests.artifact_ref,
	dataprivacy_requests.artifact_bytes,
	dataprivacy_requests.deleted_rows,
	dataprivacy_requests.anonymized_rows,
	dataprivacy_requests.failures,
	dataprivacy_requests.retained,
	dataprivacy_requests.last_error,
	dataprivacy_requests.key_shredded_at
FROM dataprivacy_requests
WHERE dataprivacy_requests.archived_at IS NULL
	AND dataprivacy_requests.id = sqlc.arg(id);

-- name: GetRequestInScope :one
SELECT
	dataprivacy_requests.id,
	dataprivacy_requests.request_type,
	dataprivacy_requests.status,
	dataprivacy_requests.operation_id,
	dataprivacy_requests.subject_id,
	dataprivacy_requests.subject_type,
	dataprivacy_requests.subject_scope,
	dataprivacy_requests.created_at,
	dataprivacy_requests.last_updated_at,
	dataprivacy_requests.archived_at,
	dataprivacy_requests.due_at,
	dataprivacy_requests.expires_at,
	dataprivacy_requests.completed_at,
	dataprivacy_requests.artifact_ref,
	dataprivacy_requests.artifact_bytes,
	dataprivacy_requests.deleted_rows,
	dataprivacy_requests.anonymized_rows,
	dataprivacy_requests.failures,
	dataprivacy_requests.retained,
	dataprivacy_requests.last_error,
	dataprivacy_requests.key_shredded_at
FROM dataprivacy_requests
WHERE dataprivacy_requests.archived_at IS NULL
	AND dataprivacy_requests.id = sqlc.arg(id)
	AND dataprivacy_requests.subject_scope = sqlc.arg(subject_scope);

-- name: ListRequestsForSubject :many
SELECT
	dataprivacy_requests.id,
	dataprivacy_requests.request_type,
	dataprivacy_requests.status,
	dataprivacy_requests.operation_id,
	dataprivacy_requests.subject_id,
	dataprivacy_requests.subject_type,
	dataprivacy_requests.subject_scope,
	dataprivacy_requests.created_at,
	dataprivacy_requests.last_updated_at,
	dataprivacy_requests.archived_at,
	dataprivacy_requests.due_at,
	dataprivacy_requests.expires_at,
	dataprivacy_requests.completed_at,
	dataprivacy_requests.artifact_ref,
	dataprivacy_requests.artifact_bytes,
	dataprivacy_requests.deleted_rows,
	dataprivacy_requests.anonymized_rows,
	dataprivacy_requests.failures,
	dataprivacy_requests.retained,
	dataprivacy_requests.last_error,
	dataprivacy_requests.key_shredded_at,
	(
		SELECT COUNT(dataprivacy_requests.id)
		FROM dataprivacy_requests
		WHERE dataprivacy_requests.created_at > COALESCE(sqlc.narg(created_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND dataprivacy_requests.created_at < COALESCE(sqlc.narg(created_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				dataprivacy_requests.last_updated_at IS NULL
				OR dataprivacy_requests.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				dataprivacy_requests.last_updated_at IS NULL
				OR dataprivacy_requests.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
			AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
			AND dataprivacy_requests.subject_scope = sqlc.arg(subject_scope)
	) AS filtered_count,
	(
		SELECT COUNT(dataprivacy_requests.id)
		FROM dataprivacy_requests
		WHERE (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
			AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
			AND dataprivacy_requests.subject_scope = sqlc.arg(subject_scope)
	) AS total_count
FROM dataprivacy_requests
WHERE dataprivacy_requests.created_at > COALESCE(sqlc.narg(created_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND dataprivacy_requests.created_at < COALESCE(sqlc.narg(created_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		dataprivacy_requests.last_updated_at IS NULL
		OR dataprivacy_requests.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		dataprivacy_requests.last_updated_at IS NULL
		OR dataprivacy_requests.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
	AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
	AND dataprivacy_requests.subject_scope = sqlc.arg(subject_scope)
	AND dataprivacy_requests.id > COALESCE(sqlc.narg(page_cursor), '')
ORDER BY dataprivacy_requests.id ASC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: ListRequestsForSubjectDescending :many
SELECT
	dataprivacy_requests.id,
	dataprivacy_requests.request_type,
	dataprivacy_requests.status,
	dataprivacy_requests.operation_id,
	dataprivacy_requests.subject_id,
	dataprivacy_requests.subject_type,
	dataprivacy_requests.subject_scope,
	dataprivacy_requests.created_at,
	dataprivacy_requests.last_updated_at,
	dataprivacy_requests.archived_at,
	dataprivacy_requests.due_at,
	dataprivacy_requests.expires_at,
	dataprivacy_requests.completed_at,
	dataprivacy_requests.artifact_ref,
	dataprivacy_requests.artifact_bytes,
	dataprivacy_requests.deleted_rows,
	dataprivacy_requests.anonymized_rows,
	dataprivacy_requests.failures,
	dataprivacy_requests.retained,
	dataprivacy_requests.last_error,
	dataprivacy_requests.key_shredded_at,
	(
		SELECT COUNT(dataprivacy_requests.id)
		FROM dataprivacy_requests
		WHERE dataprivacy_requests.created_at > COALESCE(sqlc.narg(created_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND dataprivacy_requests.created_at < COALESCE(sqlc.narg(created_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				dataprivacy_requests.last_updated_at IS NULL
				OR dataprivacy_requests.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				dataprivacy_requests.last_updated_at IS NULL
				OR dataprivacy_requests.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
			AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
			AND dataprivacy_requests.subject_scope = sqlc.arg(subject_scope)
	) AS filtered_count,
	(
		SELECT COUNT(dataprivacy_requests.id)
		FROM dataprivacy_requests
		WHERE (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
			AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
			AND dataprivacy_requests.subject_scope = sqlc.arg(subject_scope)
	) AS total_count
FROM dataprivacy_requests
WHERE dataprivacy_requests.created_at > COALESCE(sqlc.narg(created_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND dataprivacy_requests.created_at < COALESCE(sqlc.narg(created_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		dataprivacy_requests.last_updated_at IS NULL
		OR dataprivacy_requests.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		dataprivacy_requests.last_updated_at IS NULL
		OR dataprivacy_requests.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
	AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
	AND dataprivacy_requests.subject_scope = sqlc.arg(subject_scope)
	AND (dataprivacy_requests.id <= COALESCE(sqlc.narg(page_cursor), dataprivacy_requests.id) AND dataprivacy_requests.id <> COALESCE(sqlc.narg(page_cursor), ''))
ORDER BY dataprivacy_requests.id DESC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: ListRequestsForSubjectInAnyScope :many
SELECT
	dataprivacy_requests.id,
	dataprivacy_requests.request_type,
	dataprivacy_requests.status,
	dataprivacy_requests.operation_id,
	dataprivacy_requests.subject_id,
	dataprivacy_requests.subject_type,
	dataprivacy_requests.subject_scope,
	dataprivacy_requests.created_at,
	dataprivacy_requests.last_updated_at,
	dataprivacy_requests.archived_at,
	dataprivacy_requests.due_at,
	dataprivacy_requests.expires_at,
	dataprivacy_requests.completed_at,
	dataprivacy_requests.artifact_ref,
	dataprivacy_requests.artifact_bytes,
	dataprivacy_requests.deleted_rows,
	dataprivacy_requests.anonymized_rows,
	dataprivacy_requests.failures,
	dataprivacy_requests.retained,
	dataprivacy_requests.last_error,
	dataprivacy_requests.key_shredded_at,
	(
		SELECT COUNT(dataprivacy_requests.id)
		FROM dataprivacy_requests
		WHERE dataprivacy_requests.created_at > COALESCE(sqlc.narg(created_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND dataprivacy_requests.created_at < COALESCE(sqlc.narg(created_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				dataprivacy_requests.last_updated_at IS NULL
				OR dataprivacy_requests.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				dataprivacy_requests.last_updated_at IS NULL
				OR dataprivacy_requests.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
			AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
	) AS filtered_count,
	(
		SELECT COUNT(dataprivacy_requests.id)
		FROM dataprivacy_requests
		WHERE (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
			AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
	) AS total_count
FROM dataprivacy_requests
WHERE dataprivacy_requests.created_at > COALESCE(sqlc.narg(created_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND dataprivacy_requests.created_at < COALESCE(sqlc.narg(created_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		dataprivacy_requests.last_updated_at IS NULL
		OR dataprivacy_requests.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		dataprivacy_requests.last_updated_at IS NULL
		OR dataprivacy_requests.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
	AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
	AND dataprivacy_requests.id > COALESCE(sqlc.narg(page_cursor), '')
ORDER BY dataprivacy_requests.id ASC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: ListRequestsForSubjectInAnyScopeDescending :many
SELECT
	dataprivacy_requests.id,
	dataprivacy_requests.request_type,
	dataprivacy_requests.status,
	dataprivacy_requests.operation_id,
	dataprivacy_requests.subject_id,
	dataprivacy_requests.subject_type,
	dataprivacy_requests.subject_scope,
	dataprivacy_requests.created_at,
	dataprivacy_requests.last_updated_at,
	dataprivacy_requests.archived_at,
	dataprivacy_requests.due_at,
	dataprivacy_requests.expires_at,
	dataprivacy_requests.completed_at,
	dataprivacy_requests.artifact_ref,
	dataprivacy_requests.artifact_bytes,
	dataprivacy_requests.deleted_rows,
	dataprivacy_requests.anonymized_rows,
	dataprivacy_requests.failures,
	dataprivacy_requests.retained,
	dataprivacy_requests.last_error,
	dataprivacy_requests.key_shredded_at,
	(
		SELECT COUNT(dataprivacy_requests.id)
		FROM dataprivacy_requests
		WHERE dataprivacy_requests.created_at > COALESCE(sqlc.narg(created_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND dataprivacy_requests.created_at < COALESCE(sqlc.narg(created_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				dataprivacy_requests.last_updated_at IS NULL
				OR dataprivacy_requests.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				dataprivacy_requests.last_updated_at IS NULL
				OR dataprivacy_requests.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
			AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
	) AS filtered_count,
	(
		SELECT COUNT(dataprivacy_requests.id)
		FROM dataprivacy_requests
		WHERE (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
			AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
	) AS total_count
FROM dataprivacy_requests
WHERE dataprivacy_requests.created_at > COALESCE(sqlc.narg(created_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND dataprivacy_requests.created_at < COALESCE(sqlc.narg(created_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		dataprivacy_requests.last_updated_at IS NULL
		OR dataprivacy_requests.last_updated_at > COALESCE(sqlc.narg(updated_after), (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		dataprivacy_requests.last_updated_at IS NULL
		OR dataprivacy_requests.last_updated_at < COALESCE(sqlc.narg(updated_before), (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE(sqlc.narg(include_archived), false)::boolean OR dataprivacy_requests.archived_at IS NULL)
	AND dataprivacy_requests.subject_id = sqlc.arg(subject_id)
	AND (dataprivacy_requests.id <= COALESCE(sqlc.narg(page_cursor), dataprivacy_requests.id) AND dataprivacy_requests.id <> COALESCE(sqlc.narg(page_cursor), ''))
ORDER BY dataprivacy_requests.id DESC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: ConfirmRequest :execrows
UPDATE dataprivacy_requests SET
	status = sqlc.arg(status),
	operation_id = sqlc.arg(operation_id),
	expires_at = sqlc.narg(expires_at),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND status = sqlc.arg(current_status);

-- name: CancelRequest :execrows
UPDATE dataprivacy_requests SET
	status = sqlc.arg(status),
	completed_at = sqlc.narg(completed_at),
	expires_at = sqlc.narg(expires_at),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND status = sqlc.arg(current_status);

-- name: MarkKeyShredded :execrows
UPDATE dataprivacy_requests SET
	key_shredded_at = sqlc.narg(key_shredded_at),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND key_shredded_at IS NULL;

-- name: CompleteExport :execrows
UPDATE dataprivacy_requests SET
	status = sqlc.arg(status),
	completed_at = sqlc.narg(completed_at),
	expires_at = sqlc.narg(expires_at),
	artifact_ref = sqlc.arg(artifact_ref),
	artifact_bytes = sqlc.arg(artifact_bytes),
	failures = sqlc.arg(failures),
	last_error = sqlc.narg(last_error),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND status = sqlc.arg(current_status);

-- name: CompleteErasure :execrows
UPDATE dataprivacy_requests SET
	status = sqlc.arg(status),
	completed_at = sqlc.narg(completed_at),
	expires_at = sqlc.narg(expires_at),
	deleted_rows = sqlc.arg(deleted_rows),
	anonymized_rows = sqlc.arg(anonymized_rows),
	failures = sqlc.arg(failures),
	retained = sqlc.arg(retained),
	key_shredded_at = sqlc.narg(key_shredded_at),
	last_error = sqlc.narg(last_error),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND status = sqlc.arg(current_status);

-- name: FailRequest :execrows
UPDATE dataprivacy_requests SET
	status = sqlc.arg(status),
	last_error = sqlc.narg(last_error),
	completed_at = sqlc.narg(completed_at),
	expires_at = sqlc.narg(expires_at),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND status = sqlc.arg(current_status);

-- name: ExpireArtifact :execrows
UPDATE dataprivacy_requests SET
	status = sqlc.arg(status),
	artifact_ref = sqlc.arg(artifact_ref),
	expires_at = sqlc.narg(expires_at),
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = sqlc.arg(id)
	AND status = sqlc.arg(current_status);

-- name: ListExpiringArtifacts :many
SELECT
	dataprivacy_requests.id,
	dataprivacy_requests.request_type,
	dataprivacy_requests.status,
	dataprivacy_requests.operation_id,
	dataprivacy_requests.subject_id,
	dataprivacy_requests.subject_type,
	dataprivacy_requests.subject_scope,
	dataprivacy_requests.created_at,
	dataprivacy_requests.last_updated_at,
	dataprivacy_requests.archived_at,
	dataprivacy_requests.due_at,
	dataprivacy_requests.expires_at,
	dataprivacy_requests.completed_at,
	dataprivacy_requests.artifact_ref,
	dataprivacy_requests.artifact_bytes,
	dataprivacy_requests.deleted_rows,
	dataprivacy_requests.anonymized_rows,
	dataprivacy_requests.failures,
	dataprivacy_requests.retained,
	dataprivacy_requests.last_error,
	dataprivacy_requests.key_shredded_at
FROM dataprivacy_requests
WHERE dataprivacy_requests.archived_at IS NULL
	AND dataprivacy_requests.status = sqlc.arg(status)
	AND dataprivacy_requests.artifact_ref <> ''
	AND dataprivacy_requests.expires_at IS NOT NULL
	AND dataprivacy_requests.expires_at <= sqlc.arg(expires_before)
ORDER BY dataprivacy_requests.expires_at ASC, dataprivacy_requests.id ASC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: LapseUnconfirmedRequests :execrows
UPDATE dataprivacy_requests SET
	status = sqlc.arg(status),
	completed_at = sqlc.narg(completed_at),
	expires_at = sqlc.narg(expires_at),
	last_updated_at = CURRENT_TIMESTAMP
WHERE dataprivacy_requests.id IN (
	SELECT
		dataprivacy_requests.id
	FROM dataprivacy_requests
	WHERE dataprivacy_requests.archived_at IS NULL
		AND dataprivacy_requests.status = sqlc.arg(current_status)
		AND dataprivacy_requests.expires_at IS NOT NULL
		AND dataprivacy_requests.expires_at <= sqlc.arg(expires_before)
	ORDER BY dataprivacy_requests.expires_at ASC, dataprivacy_requests.id ASC
	LIMIT COALESCE(sqlc.narg(result_limit), 50)
);

-- name: CountOverdueRequests :one
SELECT COUNT(*)
FROM dataprivacy_requests
WHERE dataprivacy_requests.archived_at IS NULL
	AND dataprivacy_requests.request_type = sqlc.arg(request_type)
	AND dataprivacy_requests.completed_at IS NULL
	AND dataprivacy_requests.due_at <= sqlc.arg(due_before);

-- name: ReapRequests :execrows
DELETE FROM dataprivacy_requests
WHERE dataprivacy_requests.id IN (
	SELECT
		dataprivacy_requests.id
	FROM dataprivacy_requests
	WHERE dataprivacy_requests.artifact_ref = ''
		AND dataprivacy_requests.completed_at IS NOT NULL
		AND dataprivacy_requests.completed_at <= sqlc.arg(completed_before)
	ORDER BY dataprivacy_requests.completed_at ASC, dataprivacy_requests.id ASC
	LIMIT COALESCE(sqlc.narg(result_limit), 50)
);
