// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package webhooksmock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/platform-go/v14/webhooks"

	"github.com/primandproper/primitives-go/database"
	"github.com/primandproper/primitives-go/filtering"
	"github.com/primandproper/primitives-go/tenancy"
)

// Ensure, that StoreMock does implement webhooks.Store.
// If this is not the case, regenerate this file with moq.
var _ webhooks.Store = &StoreMock{}

// StoreMock is a mock implementation of webhooks.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked webhooks.Store
//		mockedStore := &StoreMock{
//			AddSubscriptionFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string, eventType webhooks.EventType) (*webhooks.Subscription, error) {
//				panic("mock out the AddSubscription method")
//			},
//			ArchiveEndpointFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string) error {
//				panic("mock out the ArchiveEndpoint method")
//			},
//			ArchiveSubscriptionFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, subscriptionID string) error {
//				panic("mock out the ArchiveSubscription method")
//			},
//			BacklogFunc: func(ctx context.Context) (int64, time.Time, error) {
//				panic("mock out the Backlog method")
//			},
//			ClaimFunc: func(ctx context.Context, now time.Time, limit int, leaseUntil time.Time) ([]webhooks.ClaimedDispatch, error) {
//				panic("mock out the Claim method")
//			},
//			EndpointsForEventFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, eventType webhooks.EventType) ([]*webhooks.Endpoint, error) {
//				panic("mock out the EndpointsForEvent method")
//			},
//			EnqueueFunc: func(ctx context.Context, tx database.Tx, delivery *webhooks.Delivery, endpointIDs []string, now time.Time) error {
//				panic("mock out the Enqueue method")
//			},
//			GetEndpointFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, endpointID string) (*webhooks.Endpoint, error) {
//				panic("mock out the GetEndpoint method")
//			},
//			GetSubscriptionFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subscriptionID string) (*webhooks.Subscription, error) {
//				panic("mock out the GetSubscription method")
//			},
//			ListAttemptsFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, deliveryID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Attempt], error) {
//				panic("mock out the ListAttempts method")
//			},
//			ListEndpointsFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Endpoint], error) {
//				panic("mock out the ListEndpoints method")
//			},
//			ListSubscriptionsFunc: func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, endpointID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Subscription], error) {
//				panic("mock out the ListSubscriptions method")
//			},
//			MarkDeliveredFunc: func(ctx context.Context, dispatchID string, at time.Time) error {
//				panic("mock out the MarkDelivered method")
//			},
//			ReapFunc: func(ctx context.Context, before time.Time, limit int) (int64, error) {
//				panic("mock out the Reap method")
//			},
//			RecordAttemptFunc: func(ctx context.Context, attempt *webhooks.Attempt) error {
//				panic("mock out the RecordAttempt method")
//			},
//			RecordFailureFunc: func(ctx context.Context, dispatchID string, attempts int, nextAttempt time.Time, lastErr string, dead bool) error {
//				panic("mock out the RecordFailure method")
//			},
//			RequeueFunc: func(ctx context.Context, deliveryID string, endpointID string, at time.Time) error {
//				panic("mock out the Requeue method")
//			},
//			SaveEndpointFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpoint *webhooks.Endpoint) error {
//				panic("mock out the SaveEndpoint method")
//			},
//		}
//
//		// use mockedStore in code that requires webhooks.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// AddSubscriptionFunc mocks the AddSubscription method.
	AddSubscriptionFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string, eventType webhooks.EventType) (*webhooks.Subscription, error)

	// ArchiveEndpointFunc mocks the ArchiveEndpoint method.
	ArchiveEndpointFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string) error

	// ArchiveSubscriptionFunc mocks the ArchiveSubscription method.
	ArchiveSubscriptionFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, subscriptionID string) error

	// BacklogFunc mocks the Backlog method.
	BacklogFunc func(ctx context.Context) (int64, time.Time, error)

	// ClaimFunc mocks the Claim method.
	ClaimFunc func(ctx context.Context, now time.Time, limit int, leaseUntil time.Time) ([]webhooks.ClaimedDispatch, error)

	// EndpointsForEventFunc mocks the EndpointsForEvent method.
	EndpointsForEventFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, eventType webhooks.EventType) ([]*webhooks.Endpoint, error)

	// EnqueueFunc mocks the Enqueue method.
	EnqueueFunc func(ctx context.Context, tx database.Tx, delivery *webhooks.Delivery, endpointIDs []string, now time.Time) error

	// GetEndpointFunc mocks the GetEndpoint method.
	GetEndpointFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, endpointID string) (*webhooks.Endpoint, error)

	// GetSubscriptionFunc mocks the GetSubscription method.
	GetSubscriptionFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subscriptionID string) (*webhooks.Subscription, error)

	// ListAttemptsFunc mocks the ListAttempts method.
	ListAttemptsFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, deliveryID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Attempt], error)

	// ListEndpointsFunc mocks the ListEndpoints method.
	ListEndpointsFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Endpoint], error)

	// ListSubscriptionsFunc mocks the ListSubscriptions method.
	ListSubscriptionsFunc func(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, endpointID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Subscription], error)

	// MarkDeliveredFunc mocks the MarkDelivered method.
	MarkDeliveredFunc func(ctx context.Context, dispatchID string, at time.Time) error

	// ReapFunc mocks the Reap method.
	ReapFunc func(ctx context.Context, before time.Time, limit int) (int64, error)

	// RecordAttemptFunc mocks the RecordAttempt method.
	RecordAttemptFunc func(ctx context.Context, attempt *webhooks.Attempt) error

	// RecordFailureFunc mocks the RecordFailure method.
	RecordFailureFunc func(ctx context.Context, dispatchID string, attempts int, nextAttempt time.Time, lastErr string, dead bool) error

	// RequeueFunc mocks the Requeue method.
	RequeueFunc func(ctx context.Context, deliveryID string, endpointID string, at time.Time) error

	// SaveEndpointFunc mocks the SaveEndpoint method.
	SaveEndpointFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpoint *webhooks.Endpoint) error

	// calls tracks calls to the methods.
	calls struct {
		// AddSubscription holds details about calls to the AddSubscription method.
		AddSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// EndpointID is the endpointID argument value.
			EndpointID string
			// EventType is the eventType argument value.
			EventType webhooks.EventType
		}
		// ArchiveEndpoint holds details about calls to the ArchiveEndpoint method.
		ArchiveEndpoint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// EndpointID is the endpointID argument value.
			EndpointID string
		}
		// ArchiveSubscription holds details about calls to the ArchiveSubscription method.
		ArchiveSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// SubscriptionID is the subscriptionID argument value.
			SubscriptionID string
		}
		// Backlog holds details about calls to the Backlog method.
		Backlog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Claim holds details about calls to the Claim method.
		Claim []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Now is the now argument value.
			Now time.Time
			// Limit is the limit argument value.
			Limit int
			// LeaseUntil is the leaseUntil argument value.
			LeaseUntil time.Time
		}
		// EndpointsForEvent holds details about calls to the EndpointsForEvent method.
		EndpointsForEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// EventType is the eventType argument value.
			EventType webhooks.EventType
		}
		// Enqueue holds details about calls to the Enqueue method.
		Enqueue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Delivery is the delivery argument value.
			Delivery *webhooks.Delivery
			// EndpointIDs is the endpointIDs argument value.
			EndpointIDs []string
			// Now is the now argument value.
			Now time.Time
		}
		// GetEndpoint holds details about calls to the GetEndpoint method.
		GetEndpoint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// EndpointID is the endpointID argument value.
			EndpointID string
		}
		// GetSubscription holds details about calls to the GetSubscription method.
		GetSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// SubscriptionID is the subscriptionID argument value.
			SubscriptionID string
		}
		// ListAttempts holds details about calls to the ListAttempts method.
		ListAttempts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// DeliveryID is the deliveryID argument value.
			DeliveryID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// ListEndpoints holds details about calls to the ListEndpoints method.
		ListEndpoints []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// ListSubscriptions holds details about calls to the ListSubscriptions method.
		ListSubscriptions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q database.SQLQueryExecutor
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// EndpointID is the endpointID argument value.
			EndpointID string
			// Filter is the filter argument value.
			Filter *filtering.QueryFilter
		}
		// MarkDelivered holds details about calls to the MarkDelivered method.
		MarkDelivered []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DispatchID is the dispatchID argument value.
			DispatchID string
			// At is the at argument value.
			At time.Time
		}
		// Reap holds details about calls to the Reap method.
		Reap []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Before is the before argument value.
			Before time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// RecordAttempt holds details about calls to the RecordAttempt method.
		RecordAttempt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Attempt is the attempt argument value.
			Attempt *webhooks.Attempt
		}
		// RecordFailure holds details about calls to the RecordFailure method.
		RecordFailure []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DispatchID is the dispatchID argument value.
			DispatchID string
			// Attempts is the attempts argument value.
			Attempts int
			// NextAttempt is the nextAttempt argument value.
			NextAttempt time.Time
			// LastErr is the lastErr argument value.
			LastErr string
			// Dead is the dead argument value.
			Dead bool
		}
		// Requeue holds details about calls to the Requeue method.
		Requeue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeliveryID is the deliveryID argument value.
			DeliveryID string
			// EndpointID is the endpointID argument value.
			EndpointID string
			// At is the at argument value.
			At time.Time
		}
		// SaveEndpoint holds details about calls to the SaveEndpoint method.
		SaveEndpoint []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Endpoint is the endpoint argument value.
			Endpoint *webhooks.Endpoint
		}
	}
	lockAddSubscription     sync.RWMutex
	lockArchiveEndpoint     sync.RWMutex
	lockArchiveSubscription sync.RWMutex
	lockBacklog             sync.RWMutex
	lockClaim               sync.RWMutex
	lockEndpointsForEvent   sync.RWMutex
	lockEnqueue             sync.RWMutex
	lockGetEndpoint         sync.RWMutex
	lockGetSubscription     sync.RWMutex
	lockListAttempts        sync.RWMutex
	lockListEndpoints       sync.RWMutex
	lockListSubscriptions   sync.RWMutex
	lockMarkDelivered       sync.RWMutex
	lockReap                sync.RWMutex
	lockRecordAttempt       sync.RWMutex
	lockRecordFailure       sync.RWMutex
	lockRequeue             sync.RWMutex
	lockSaveEndpoint        sync.RWMutex
}

// AddSubscription calls AddSubscriptionFunc.
func (mock *StoreMock) AddSubscription(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string, eventType webhooks.EventType) (*webhooks.Subscription, error) {
	if mock.AddSubscriptionFunc == nil {
		panic("StoreMock.AddSubscriptionFunc: method is nil but Store.AddSubscription was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         database.Tx
		Scope      tenancy.Scope
		EndpointID string
		EventType  webhooks.EventType
	}{
		Ctx:        ctx,
		Tx:         tx,
		Scope:      scope,
		EndpointID: endpointID,
		EventType:  eventType,
	}
	mock.lockAddSubscription.Lock()
	mock.calls.AddSubscription = append(mock.calls.AddSubscription, callInfo)
	mock.lockAddSubscription.Unlock()
	return mock.AddSubscriptionFunc(ctx, tx, scope, endpointID, eventType)
}

// AddSubscriptionCalls gets all the calls that were made to AddSubscription.
// Check the length with:
//
//	len(mockedStore.AddSubscriptionCalls())
func (mock *StoreMock) AddSubscriptionCalls() []struct {
	Ctx        context.Context
	Tx         database.Tx
	Scope      tenancy.Scope
	EndpointID string
	EventType  webhooks.EventType
} {
	var calls []struct {
		Ctx        context.Context
		Tx         database.Tx
		Scope      tenancy.Scope
		EndpointID string
		EventType  webhooks.EventType
	}
	mock.lockAddSubscription.RLock()
	calls = mock.calls.AddSubscription
	mock.lockAddSubscription.RUnlock()
	return calls
}

// ArchiveEndpoint calls ArchiveEndpointFunc.
func (mock *StoreMock) ArchiveEndpoint(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string) error {
	if mock.ArchiveEndpointFunc == nil {
		panic("StoreMock.ArchiveEndpointFunc: method is nil but Store.ArchiveEndpoint was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         database.Tx
		Scope      tenancy.Scope
		EndpointID string
	}{
		Ctx:        ctx,
		Tx:         tx,
		Scope:      scope,
		EndpointID: endpointID,
	}
	mock.lockArchiveEndpoint.Lock()
	mock.calls.ArchiveEndpoint = append(mock.calls.ArchiveEndpoint, callInfo)
	mock.lockArchiveEndpoint.Unlock()
	return mock.ArchiveEndpointFunc(ctx, tx, scope, endpointID)
}

// ArchiveEndpointCalls gets all the calls that were made to ArchiveEndpoint.
// Check the length with:
//
//	len(mockedStore.ArchiveEndpointCalls())
func (mock *StoreMock) ArchiveEndpointCalls() []struct {
	Ctx        context.Context
	Tx         database.Tx
	Scope      tenancy.Scope
	EndpointID string
} {
	var calls []struct {
		Ctx        context.Context
		Tx         database.Tx
		Scope      tenancy.Scope
		EndpointID string
	}
	mock.lockArchiveEndpoint.RLock()
	calls = mock.calls.ArchiveEndpoint
	mock.lockArchiveEndpoint.RUnlock()
	return calls
}

// ArchiveSubscription calls ArchiveSubscriptionFunc.
func (mock *StoreMock) ArchiveSubscription(ctx context.Context, tx database.Tx, scope tenancy.Scope, subscriptionID string) error {
	if mock.ArchiveSubscriptionFunc == nil {
		panic("StoreMock.ArchiveSubscriptionFunc: method is nil but Store.ArchiveSubscription was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Tx             database.Tx
		Scope          tenancy.Scope
		SubscriptionID string
	}{
		Ctx:            ctx,
		Tx:             tx,
		Scope:          scope,
		SubscriptionID: subscriptionID,
	}
	mock.lockArchiveSubscription.Lock()
	mock.calls.ArchiveSubscription = append(mock.calls.ArchiveSubscription, callInfo)
	mock.lockArchiveSubscription.Unlock()
	return mock.ArchiveSubscriptionFunc(ctx, tx, scope, subscriptionID)
}

// ArchiveSubscriptionCalls gets all the calls that were made to ArchiveSubscription.
// Check the length with:
//
//	len(mockedStore.ArchiveSubscriptionCalls())
func (mock *StoreMock) ArchiveSubscriptionCalls() []struct {
	Ctx            context.Context
	Tx             database.Tx
	Scope          tenancy.Scope
	SubscriptionID string
} {
	var calls []struct {
		Ctx            context.Context
		Tx             database.Tx
		Scope          tenancy.Scope
		SubscriptionID string
	}
	mock.lockArchiveSubscription.RLock()
	calls = mock.calls.ArchiveSubscription
	mock.lockArchiveSubscription.RUnlock()
	return calls
}

// Backlog calls BacklogFunc.
func (mock *StoreMock) Backlog(ctx context.Context) (int64, time.Time, error) {
	if mock.BacklogFunc == nil {
		panic("StoreMock.BacklogFunc: method is nil but Store.Backlog was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockBacklog.Lock()
	mock.calls.Backlog = append(mock.calls.Backlog, callInfo)
	mock.lockBacklog.Unlock()
	return mock.BacklogFunc(ctx)
}

// BacklogCalls gets all the calls that were made to Backlog.
// Check the length with:
//
//	len(mockedStore.BacklogCalls())
func (mock *StoreMock) BacklogCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockBacklog.RLock()
	calls = mock.calls.Backlog
	mock.lockBacklog.RUnlock()
	return calls
}

// Claim calls ClaimFunc.
func (mock *StoreMock) Claim(ctx context.Context, now time.Time, limit int, leaseUntil time.Time) ([]webhooks.ClaimedDispatch, error) {
	if mock.ClaimFunc == nil {
		panic("StoreMock.ClaimFunc: method is nil but Store.Claim was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Now        time.Time
		Limit      int
		LeaseUntil time.Time
	}{
		Ctx:        ctx,
		Now:        now,
		Limit:      limit,
		LeaseUntil: leaseUntil,
	}
	mock.lockClaim.Lock()
	mock.calls.Claim = append(mock.calls.Claim, callInfo)
	mock.lockClaim.Unlock()
	return mock.ClaimFunc(ctx, now, limit, leaseUntil)
}

// ClaimCalls gets all the calls that were made to Claim.
// Check the length with:
//
//	len(mockedStore.ClaimCalls())
func (mock *StoreMock) ClaimCalls() []struct {
	Ctx        context.Context
	Now        time.Time
	Limit      int
	LeaseUntil time.Time
} {
	var calls []struct {
		Ctx        context.Context
		Now        time.Time
		Limit      int
		LeaseUntil time.Time
	}
	mock.lockClaim.RLock()
	calls = mock.calls.Claim
	mock.lockClaim.RUnlock()
	return calls
}

// EndpointsForEvent calls EndpointsForEventFunc.
func (mock *StoreMock) EndpointsForEvent(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, eventType webhooks.EventType) ([]*webhooks.Endpoint, error) {
	if mock.EndpointsForEventFunc == nil {
		panic("StoreMock.EndpointsForEventFunc: method is nil but Store.EndpointsForEvent was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Q         database.SQLQueryExecutor
		Scope     tenancy.Scope
		EventType webhooks.EventType
	}{
		Ctx:       ctx,
		Q:         q,
		Scope:     scope,
		EventType: eventType,
	}
	mock.lockEndpointsForEvent.Lock()
	mock.calls.EndpointsForEvent = append(mock.calls.EndpointsForEvent, callInfo)
	mock.lockEndpointsForEvent.Unlock()
	return mock.EndpointsForEventFunc(ctx, q, scope, eventType)
}

// EndpointsForEventCalls gets all the calls that were made to EndpointsForEvent.
// Check the length with:
//
//	len(mockedStore.EndpointsForEventCalls())
func (mock *StoreMock) EndpointsForEventCalls() []struct {
	Ctx       context.Context
	Q         database.SQLQueryExecutor
	Scope     tenancy.Scope
	EventType webhooks.EventType
} {
	var calls []struct {
		Ctx       context.Context
		Q         database.SQLQueryExecutor
		Scope     tenancy.Scope
		EventType webhooks.EventType
	}
	mock.lockEndpointsForEvent.RLock()
	calls = mock.calls.EndpointsForEvent
	mock.lockEndpointsForEvent.RUnlock()
	return calls
}

// Enqueue calls EnqueueFunc.
func (mock *StoreMock) Enqueue(ctx context.Context, tx database.Tx, delivery *webhooks.Delivery, endpointIDs []string, now time.Time) error {
	if mock.EnqueueFunc == nil {
		panic("StoreMock.EnqueueFunc: method is nil but Store.Enqueue was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Tx          database.Tx
		Delivery    *webhooks.Delivery
		EndpointIDs []string
		Now         time.Time
	}{
		Ctx:         ctx,
		Tx:          tx,
		Delivery:    delivery,
		EndpointIDs: endpointIDs,
		Now:         now,
	}
	mock.lockEnqueue.Lock()
	mock.calls.Enqueue = append(mock.calls.Enqueue, callInfo)
	mock.lockEnqueue.Unlock()
	return mock.EnqueueFunc(ctx, tx, delivery, endpointIDs, now)
}

// EnqueueCalls gets all the calls that were made to Enqueue.
// Check the length with:
//
//	len(mockedStore.EnqueueCalls())
func (mock *StoreMock) EnqueueCalls() []struct {
	Ctx         context.Context
	Tx          database.Tx
	Delivery    *webhooks.Delivery
	EndpointIDs []string
	Now         time.Time
} {
	var calls []struct {
		Ctx         context.Context
		Tx          database.Tx
		Delivery    *webhooks.Delivery
		EndpointIDs []string
		Now         time.Time
	}
	mock.lockEnqueue.RLock()
	calls = mock.calls.Enqueue
	mock.lockEnqueue.RUnlock()
	return calls
}

// GetEndpoint calls GetEndpointFunc.
func (mock *StoreMock) GetEndpoint(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, endpointID string) (*webhooks.Endpoint, error) {
	if mock.GetEndpointFunc == nil {
		panic("StoreMock.GetEndpointFunc: method is nil but Store.GetEndpoint was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Q          database.SQLQueryExecutor
		Scope      tenancy.Scope
		EndpointID string
	}{
		Ctx:        ctx,
		Q:          q,
		Scope:      scope,
		EndpointID: endpointID,
	}
	mock.lockGetEndpoint.Lock()
	mock.calls.GetEndpoint = append(mock.calls.GetEndpoint, callInfo)
	mock.lockGetEndpoint.Unlock()
	return mock.GetEndpointFunc(ctx, q, scope, endpointID)
}

// GetEndpointCalls gets all the calls that were made to GetEndpoint.
// Check the length with:
//
//	len(mockedStore.GetEndpointCalls())
func (mock *StoreMock) GetEndpointCalls() []struct {
	Ctx        context.Context
	Q          database.SQLQueryExecutor
	Scope      tenancy.Scope
	EndpointID string
} {
	var calls []struct {
		Ctx        context.Context
		Q          database.SQLQueryExecutor
		Scope      tenancy.Scope
		EndpointID string
	}
	mock.lockGetEndpoint.RLock()
	calls = mock.calls.GetEndpoint
	mock.lockGetEndpoint.RUnlock()
	return calls
}

// GetSubscription calls GetSubscriptionFunc.
func (mock *StoreMock) GetSubscription(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, subscriptionID string) (*webhooks.Subscription, error) {
	if mock.GetSubscriptionFunc == nil {
		panic("StoreMock.GetSubscriptionFunc: method is nil but Store.GetSubscription was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Q              database.SQLQueryExecutor
		Scope          tenancy.Scope
		SubscriptionID string
	}{
		Ctx:            ctx,
		Q:              q,
		Scope:          scope,
		SubscriptionID: subscriptionID,
	}
	mock.lockGetSubscription.Lock()
	mock.calls.GetSubscription = append(mock.calls.GetSubscription, callInfo)
	mock.lockGetSubscription.Unlock()
	return mock.GetSubscriptionFunc(ctx, q, scope, subscriptionID)
}

// GetSubscriptionCalls gets all the calls that were made to GetSubscription.
// Check the length with:
//
//	len(mockedStore.GetSubscriptionCalls())
func (mock *StoreMock) GetSubscriptionCalls() []struct {
	Ctx            context.Context
	Q              database.SQLQueryExecutor
	Scope          tenancy.Scope
	SubscriptionID string
} {
	var calls []struct {
		Ctx            context.Context
		Q              database.SQLQueryExecutor
		Scope          tenancy.Scope
		SubscriptionID string
	}
	mock.lockGetSubscription.RLock()
	calls = mock.calls.GetSubscription
	mock.lockGetSubscription.RUnlock()
	return calls
}

// ListAttempts calls ListAttemptsFunc.
func (mock *StoreMock) ListAttempts(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, deliveryID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Attempt], error) {
	if mock.ListAttemptsFunc == nil {
		panic("StoreMock.ListAttemptsFunc: method is nil but Store.ListAttempts was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Q          database.SQLQueryExecutor
		Scope      tenancy.Scope
		DeliveryID string
		Filter     *filtering.QueryFilter
	}{
		Ctx:        ctx,
		Q:          q,
		Scope:      scope,
		DeliveryID: deliveryID,
		Filter:     filter,
	}
	mock.lockListAttempts.Lock()
	mock.calls.ListAttempts = append(mock.calls.ListAttempts, callInfo)
	mock.lockListAttempts.Unlock()
	return mock.ListAttemptsFunc(ctx, q, scope, deliveryID, filter)
}

// ListAttemptsCalls gets all the calls that were made to ListAttempts.
// Check the length with:
//
//	len(mockedStore.ListAttemptsCalls())
func (mock *StoreMock) ListAttemptsCalls() []struct {
	Ctx        context.Context
	Q          database.SQLQueryExecutor
	Scope      tenancy.Scope
	DeliveryID string
	Filter     *filtering.QueryFilter
} {
	var calls []struct {
		Ctx        context.Context
		Q          database.SQLQueryExecutor
		Scope      tenancy.Scope
		DeliveryID string
		Filter     *filtering.QueryFilter
	}
	mock.lockListAttempts.RLock()
	calls = mock.calls.ListAttempts
	mock.lockListAttempts.RUnlock()
	return calls
}

// ListEndpoints calls ListEndpointsFunc.
func (mock *StoreMock) ListEndpoints(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Endpoint], error) {
	if mock.ListEndpointsFunc == nil {
		panic("StoreMock.ListEndpointsFunc: method is nil but Store.ListEndpoints was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Q      database.SQLQueryExecutor
		Scope  tenancy.Scope
		Filter *filtering.QueryFilter
	}{
		Ctx:    ctx,
		Q:      q,
		Scope:  scope,
		Filter: filter,
	}
	mock.lockListEndpoints.Lock()
	mock.calls.ListEndpoints = append(mock.calls.ListEndpoints, callInfo)
	mock.lockListEndpoints.Unlock()
	return mock.ListEndpointsFunc(ctx, q, scope, filter)
}

// ListEndpointsCalls gets all the calls that were made to ListEndpoints.
// Check the length with:
//
//	len(mockedStore.ListEndpointsCalls())
func (mock *StoreMock) ListEndpointsCalls() []struct {
	Ctx    context.Context
	Q      database.SQLQueryExecutor
	Scope  tenancy.Scope
	Filter *filtering.QueryFilter
} {
	var calls []struct {
		Ctx    context.Context
		Q      database.SQLQueryExecutor
		Scope  tenancy.Scope
		Filter *filtering.QueryFilter
	}
	mock.lockListEndpoints.RLock()
	calls = mock.calls.ListEndpoints
	mock.lockListEndpoints.RUnlock()
	return calls
}

// ListSubscriptions calls ListSubscriptionsFunc.
func (mock *StoreMock) ListSubscriptions(ctx context.Context, q database.SQLQueryExecutor, scope tenancy.Scope, endpointID string, filter *filtering.QueryFilter) (*filtering.QueryFilteredResult[webhooks.Subscription], error) {
	if mock.ListSubscriptionsFunc == nil {
		panic("StoreMock.ListSubscriptionsFunc: method is nil but Store.ListSubscriptions was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Q          database.SQLQueryExecutor
		Scope      tenancy.Scope
		EndpointID string
		Filter     *filtering.QueryFilter
	}{
		Ctx:        ctx,
		Q:          q,
		Scope:      scope,
		EndpointID: endpointID,
		Filter:     filter,
	}
	mock.lockListSubscriptions.Lock()
	mock.calls.ListSubscriptions = append(mock.calls.ListSubscriptions, callInfo)
	mock.lockListSubscriptions.Unlock()
	return mock.ListSubscriptionsFunc(ctx, q, scope, endpointID, filter)
}

// ListSubscriptionsCalls gets all the calls that were made to ListSubscriptions.
// Check the length with:
//
//	len(mockedStore.ListSubscriptionsCalls())
func (mock *StoreMock) ListSubscriptionsCalls() []struct {
	Ctx        context.Context
	Q          database.SQLQueryExecutor
	Scope      tenancy.Scope
	EndpointID string
	Filter     *filtering.QueryFilter
} {
	var calls []struct {
		Ctx        context.Context
		Q          database.SQLQueryExecutor
		Scope      tenancy.Scope
		EndpointID string
		Filter     *filtering.QueryFilter
	}
	mock.lockListSubscriptions.RLock()
	calls = mock.calls.ListSubscriptions
	mock.lockListSubscriptions.RUnlock()
	return calls
}

// MarkDelivered calls MarkDeliveredFunc.
func (mock *StoreMock) MarkDelivered(ctx context.Context, dispatchID string, at time.Time) error {
	if mock.MarkDeliveredFunc == nil {
		panic("StoreMock.MarkDeliveredFunc: method is nil but Store.MarkDelivered was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DispatchID string
		At         time.Time
	}{
		Ctx:        ctx,
		DispatchID: dispatchID,
		At:         at,
	}
	mock.lockMarkDelivered.Lock()
	mock.calls.MarkDelivered = append(mock.calls.MarkDelivered, callInfo)
	mock.lockMarkDelivered.Unlock()
	return mock.MarkDeliveredFunc(ctx, dispatchID, at)
}

// MarkDeliveredCalls gets all the calls that were made to MarkDelivered.
// Check the length with:
//
//	len(mockedStore.MarkDeliveredCalls())
func (mock *StoreMock) MarkDeliveredCalls() []struct {
	Ctx        context.Context
	DispatchID string
	At         time.Time
} {
	var calls []struct {
		Ctx        context.Context
		DispatchID string
		At         time.Time
	}
	mock.lockMarkDelivered.RLock()
	calls = mock.calls.MarkDelivered
	mock.lockMarkDelivered.RUnlock()
	return calls
}

// Reap calls ReapFunc.
func (mock *StoreMock) Reap(ctx context.Context, before time.Time, limit int) (int64, error) {
	if mock.ReapFunc == nil {
		panic("StoreMock.ReapFunc: method is nil but Store.Reap was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Before time.Time
		Limit  int
	}{
		Ctx:    ctx,
		Before: before,
		Limit:  limit,
	}
	mock.lockReap.Lock()
	mock.calls.Reap = append(mock.calls.Reap, callInfo)
	mock.lockReap.Unlock()
	return mock.ReapFunc(ctx, before, limit)
}

// ReapCalls gets all the calls that were made to Reap.
// Check the length with:
//
//	len(mockedStore.ReapCalls())
func (mock *StoreMock) ReapCalls() []struct {
	Ctx    context.Context
	Before time.Time
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Before time.Time
		Limit  int
	}
	mock.lockReap.RLock()
	calls = mock.calls.Reap
	mock.lockReap.RUnlock()
	return calls
}

// RecordAttempt calls RecordAttemptFunc.
func (mock *StoreMock) RecordAttempt(ctx context.Context, attempt *webhooks.Attempt) error {
	if mock.RecordAttemptFunc == nil {
		panic("StoreMock.RecordAttemptFunc: method is nil but Store.RecordAttempt was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Attempt *webhooks.Attempt
	}{
		Ctx:     ctx,
		Attempt: attempt,
	}
	mock.lockRecordAttempt.Lock()
	mock.calls.RecordAttempt = append(mock.calls.RecordAttempt, callInfo)
	mock.lockRecordAttempt.Unlock()
	return mock.RecordAttemptFunc(ctx, attempt)
}

// RecordAttemptCalls gets all the calls that were made to RecordAttempt.
// Check the length with:
//
//	len(mockedStore.RecordAttemptCalls())
func (mock *StoreMock) RecordAttemptCalls() []struct {
	Ctx     context.Context
	Attempt *webhooks.Attempt
} {
	var calls []struct {
		Ctx     context.Context
		Attempt *webhooks.Attempt
	}
	mock.lockRecordAttempt.RLock()
	calls = mock.calls.RecordAttempt
	mock.lockRecordAttempt.RUnlock()
	return calls
}

// RecordFailure calls RecordFailureFunc.
func (mock *StoreMock) RecordFailure(ctx context.Context, dispatchID string, attempts int, nextAttempt time.Time, lastErr string, dead bool) error {
	if mock.RecordFailureFunc == nil {
		panic("StoreMock.RecordFailureFunc: method is nil but Store.RecordFailure was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		DispatchID  string
		Attempts    int
		NextAttempt time.Time
		LastErr     string
		Dead        bool
	}{
		Ctx:         ctx,
		DispatchID:  dispatchID,
		Attempts:    attempts,
		NextAttempt: nextAttempt,
		LastErr:     lastErr,
		Dead:        dead,
	}
	mock.lockRecordFailure.Lock()
	mock.calls.RecordFailure = append(mock.calls.RecordFailure, callInfo)
	mock.lockRecordFailure.Unlock()
	return mock.RecordFailureFunc(ctx, dispatchID, attempts, nextAttempt, lastErr, dead)
}

// RecordFailureCalls gets all the calls that were made to RecordFailure.
// Check the length with:
//
//	len(mockedStore.RecordFailureCalls())
func (mock *StoreMock) RecordFailureCalls() []struct {
	Ctx         context.Context
	DispatchID  string
	Attempts    int
	NextAttempt time.Time
	LastErr     string
	Dead        bool
} {
	var calls []struct {
		Ctx         context.Context
		DispatchID  string
		Attempts    int
		NextAttempt time.Time
		LastErr     string
		Dead        bool
	}
	mock.lockRecordFailure.RLock()
	calls = mock.calls.RecordFailure
	mock.lockRecordFailure.RUnlock()
	return calls
}

// Requeue calls RequeueFunc.
func (mock *StoreMock) Requeue(ctx context.Context, deliveryID string, endpointID string, at time.Time) error {
	if mock.RequeueFunc == nil {
		panic("StoreMock.RequeueFunc: method is nil but Store.Requeue was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		DeliveryID string
		EndpointID string
		At         time.Time
	}{
		Ctx:        ctx,
		DeliveryID: deliveryID,
		EndpointID: endpointID,
		At:         at,
	}
	mock.lockRequeue.Lock()
	mock.calls.Requeue = append(mock.calls.Requeue, callInfo)
	mock.lockRequeue.Unlock()
	return mock.RequeueFunc(ctx, deliveryID, endpointID, at)
}

// RequeueCalls gets all the calls that were made to Requeue.
// Check the length with:
//
//	len(mockedStore.RequeueCalls())
func (mock *StoreMock) RequeueCalls() []struct {
	Ctx        context.Context
	DeliveryID string
	EndpointID string
	At         time.Time
} {
	var calls []struct {
		Ctx        context.Context
		DeliveryID string
		EndpointID string
		At         time.Time
	}
	mock.lockRequeue.RLock()
	calls = mock.calls.Requeue
	mock.lockRequeue.RUnlock()
	return calls
}

// SaveEndpoint calls SaveEndpointFunc.
func (mock *StoreMock) SaveEndpoint(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpoint *webhooks.Endpoint) error {
	if mock.SaveEndpointFunc == nil {
		panic("StoreMock.SaveEndpointFunc: method is nil but Store.SaveEndpoint was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Tx       database.Tx
		Scope    tenancy.Scope
		Endpoint *webhooks.Endpoint
	}{
		Ctx:      ctx,
		Tx:       tx,
		Scope:    scope,
		Endpoint: endpoint,
	}
	mock.lockSaveEndpoint.Lock()
	mock.calls.SaveEndpoint = append(mock.calls.SaveEndpoint, callInfo)
	mock.lockSaveEndpoint.Unlock()
	return mock.SaveEndpointFunc(ctx, tx, scope, endpoint)
}

// SaveEndpointCalls gets all the calls that were made to SaveEndpoint.
// Check the length with:
//
//	len(mockedStore.SaveEndpointCalls())
func (mock *StoreMock) SaveEndpointCalls() []struct {
	Ctx      context.Context
	Tx       database.Tx
	Scope    tenancy.Scope
	Endpoint *webhooks.Endpoint
} {
	var calls []struct {
		Ctx      context.Context
		Tx       database.Tx
		Scope    tenancy.Scope
		Endpoint *webhooks.Endpoint
	}
	mock.lockSaveEndpoint.RLock()
	calls = mock.calls.SaveEndpoint
	mock.lockSaveEndpoint.RUnlock()
	return calls
}

// Ensure, that DispatcherMock does implement webhooks.Dispatcher.
// If this is not the case, regenerate this file with moq.
var _ webhooks.Dispatcher = &DispatcherMock{}

// DispatcherMock is a mock implementation of webhooks.Dispatcher.
//
//	func TestSomethingThatUsesDispatcher(t *testing.T) {
//
//		// make and configure a mocked webhooks.Dispatcher
//		mockedDispatcher := &DispatcherMock{
//			DispatchFunc: func(ctx context.Context, tx database.Tx, delivery *webhooks.Delivery) error {
//				panic("mock out the Dispatch method")
//			},
//			RegisterFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpoint *webhooks.Endpoint) error {
//				panic("mock out the Register method")
//			},
//			ReplayFunc: func(ctx context.Context, scope tenancy.Scope, deliveryID string, endpointID string) error {
//				panic("mock out the Replay method")
//			},
//			SubscribeFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string, eventType webhooks.EventType) (*webhooks.Subscription, error) {
//				panic("mock out the Subscribe method")
//			},
//			UnsubscribeFunc: func(ctx context.Context, tx database.Tx, scope tenancy.Scope, subscriptionID string) error {
//				panic("mock out the Unsubscribe method")
//			},
//		}
//
//		// use mockedDispatcher in code that requires webhooks.Dispatcher
//		// and then make assertions.
//
//	}
type DispatcherMock struct {
	// DispatchFunc mocks the Dispatch method.
	DispatchFunc func(ctx context.Context, tx database.Tx, delivery *webhooks.Delivery) error

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpoint *webhooks.Endpoint) error

	// ReplayFunc mocks the Replay method.
	ReplayFunc func(ctx context.Context, scope tenancy.Scope, deliveryID string, endpointID string) error

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string, eventType webhooks.EventType) (*webhooks.Subscription, error)

	// UnsubscribeFunc mocks the Unsubscribe method.
	UnsubscribeFunc func(ctx context.Context, tx database.Tx, scope tenancy.Scope, subscriptionID string) error

	// calls tracks calls to the methods.
	calls struct {
		// Dispatch holds details about calls to the Dispatch method.
		Dispatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Delivery is the delivery argument value.
			Delivery *webhooks.Delivery
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// Endpoint is the endpoint argument value.
			Endpoint *webhooks.Endpoint
		}
		// Replay holds details about calls to the Replay method.
		Replay []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// DeliveryID is the deliveryID argument value.
			DeliveryID string
			// EndpointID is the endpointID argument value.
			EndpointID string
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// EndpointID is the endpointID argument value.
			EndpointID string
			// EventType is the eventType argument value.
			EventType webhooks.EventType
		}
		// Unsubscribe holds details about calls to the Unsubscribe method.
		Unsubscribe []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Tx is the tx argument value.
			Tx database.Tx
			// Scope is the scope argument value.
			Scope tenancy.Scope
			// SubscriptionID is the subscriptionID argument value.
			SubscriptionID string
		}
	}
	lockDispatch    sync.RWMutex
	lockRegister    sync.RWMutex
	lockReplay      sync.RWMutex
	lockSubscribe   sync.RWMutex
	lockUnsubscribe sync.RWMutex
}

// Dispatch calls DispatchFunc.
func (mock *DispatcherMock) Dispatch(ctx context.Context, tx database.Tx, delivery *webhooks.Delivery) error {
	if mock.DispatchFunc == nil {
		panic("DispatcherMock.DispatchFunc: method is nil but Dispatcher.Dispatch was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Tx       database.Tx
		Delivery *webhooks.Delivery
	}{
		Ctx:      ctx,
		Tx:       tx,
		Delivery: delivery,
	}
	mock.lockDispatch.Lock()
	mock.calls.Dispatch = append(mock.calls.Dispatch, callInfo)
	mock.lockDispatch.Unlock()
	return mock.DispatchFunc(ctx, tx, delivery)
}

// DispatchCalls gets all the calls that were made to Dispatch.
// Check the length with:
//
//	len(mockedDispatcher.DispatchCalls())
func (mock *DispatcherMock) DispatchCalls() []struct {
	Ctx      context.Context
	Tx       database.Tx
	Delivery *webhooks.Delivery
} {
	var calls []struct {
		Ctx      context.Context
		Tx       database.Tx
		Delivery *webhooks.Delivery
	}
	mock.lockDispatch.RLock()
	calls = mock.calls.Dispatch
	mock.lockDispatch.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *DispatcherMock) Register(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpoint *webhooks.Endpoint) error {
	if mock.RegisterFunc == nil {
		panic("DispatcherMock.RegisterFunc: method is nil but Dispatcher.Register was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Tx       database.Tx
		Scope    tenancy.Scope
		Endpoint *webhooks.Endpoint
	}{
		Ctx:      ctx,
		Tx:       tx,
		Scope:    scope,
		Endpoint: endpoint,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, tx, scope, endpoint)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedDispatcher.RegisterCalls())
func (mock *DispatcherMock) RegisterCalls() []struct {
	Ctx      context.Context
	Tx       database.Tx
	Scope    tenancy.Scope
	Endpoint *webhooks.Endpoint
} {
	var calls []struct {
		Ctx      context.Context
		Tx       database.Tx
		Scope    tenancy.Scope
		Endpoint *webhooks.Endpoint
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// Replay calls ReplayFunc.
func (mock *DispatcherMock) Replay(ctx context.Context, scope tenancy.Scope, deliveryID string, endpointID string) error {
	if mock.ReplayFunc == nil {
		panic("DispatcherMock.ReplayFunc: method is nil but Dispatcher.Replay was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Scope      tenancy.Scope
		DeliveryID string
		EndpointID string
	}{
		Ctx:        ctx,
		Scope:      scope,
		DeliveryID: deliveryID,
		EndpointID: endpointID,
	}
	mock.lockReplay.Lock()
	mock.calls.Replay = append(mock.calls.Replay, callInfo)
	mock.lockReplay.Unlock()
	return mock.ReplayFunc(ctx, scope, deliveryID, endpointID)
}

// ReplayCalls gets all the calls that were made to Replay.
// Check the length with:
//
//	len(mockedDispatcher.ReplayCalls())
func (mock *DispatcherMock) ReplayCalls() []struct {
	Ctx        context.Context
	Scope      tenancy.Scope
	DeliveryID string
	EndpointID string
} {
	var calls []struct {
		Ctx        context.Context
		Scope      tenancy.Scope
		DeliveryID string
		EndpointID string
	}
	mock.lockReplay.RLock()
	calls = mock.calls.Replay
	mock.lockReplay.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *DispatcherMock) Subscribe(ctx context.Context, tx database.Tx, scope tenancy.Scope, endpointID string, eventType webhooks.EventType) (*webhooks.Subscription, error) {
	if mock.SubscribeFunc == nil {
		panic("DispatcherMock.SubscribeFunc: method is nil but Dispatcher.Subscribe was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Tx         database.Tx
		Scope      tenancy.Scope
		EndpointID string
		EventType  webhooks.EventType
	}{
		Ctx:        ctx,
		Tx:         tx,
		Scope:      scope,
		EndpointID: endpointID,
		EventType:  eventType,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(ctx, tx, scope, endpointID, eventType)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedDispatcher.SubscribeCalls())
func (mock *DispatcherMock) SubscribeCalls() []struct {
	Ctx        context.Context
	Tx         database.Tx
	Scope      tenancy.Scope
	EndpointID string
	EventType  webhooks.EventType
} {
	var calls []struct {
		Ctx        context.Context
		Tx         database.Tx
		Scope      tenancy.Scope
		EndpointID string
		EventType  webhooks.EventType
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}

// Unsubscribe calls UnsubscribeFunc.
func (mock *DispatcherMock) Unsubscribe(ctx context.Context, tx database.Tx, scope tenancy.Scope, subscriptionID string) error {
	if mock.UnsubscribeFunc == nil {
		panic("DispatcherMock.UnsubscribeFunc: method is nil but Dispatcher.Unsubscribe was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Tx             database.Tx
		Scope          tenancy.Scope
		SubscriptionID string
	}{
		Ctx:            ctx,
		Tx:             tx,
		Scope:          scope,
		SubscriptionID: subscriptionID,
	}
	mock.lockUnsubscribe.Lock()
	mock.calls.Unsubscribe = append(mock.calls.Unsubscribe, callInfo)
	mock.lockUnsubscribe.Unlock()
	return mock.UnsubscribeFunc(ctx, tx, scope, subscriptionID)
}

// UnsubscribeCalls gets all the calls that were made to Unsubscribe.
// Check the length with:
//
//	len(mockedDispatcher.UnsubscribeCalls())
func (mock *DispatcherMock) UnsubscribeCalls() []struct {
	Ctx            context.Context
	Tx             database.Tx
	Scope          tenancy.Scope
	SubscriptionID string
} {
	var calls []struct {
		Ctx            context.Context
		Tx             database.Tx
		Scope          tenancy.Scope
		SubscriptionID string
	}
	mock.lockUnsubscribe.RLock()
	calls = mock.calls.Unsubscribe
	mock.lockUnsubscribe.RUnlock()
	return calls
}
