// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package phonecodesdb

import (
	"context"
	"strings"
	"time"

	"github.com/primandproper/primitives-go/v2/tenancy"
)

const countPhoneCodeAttemptMySQL = `UPDATE {{prefix}}phone_codes SET
	attempts = ?
WHERE id = ?
	AND scope = ?
	AND redeemed_at IS NULL
	AND revoked_at IS NULL
	AND expires_at > ?
	AND attempts = ?`

const deletePhoneCodesForSubjectMySQL = `DELETE FROM {{prefix}}phone_codes
WHERE scope = ?
	AND subject_id = ?`

const getPhoneCodeMySQL = `SELECT
	{{prefix}}phone_codes.id,
	{{prefix}}phone_codes.scope,
	{{prefix}}phone_codes.subject_id,
	{{prefix}}phone_codes.phone_number,
	{{prefix}}phone_codes.attempts,
	{{prefix}}phone_codes.max_attempts,
	{{prefix}}phone_codes.issued_at,
	{{prefix}}phone_codes.expires_at,
	{{prefix}}phone_codes.purge_after,
	{{prefix}}phone_codes.redeemed_at,
	{{prefix}}phone_codes.revoked_at
FROM {{prefix}}phone_codes
WHERE {{prefix}}phone_codes.scope = ?
	AND {{prefix}}phone_codes.phone_number = ?`

const issuePhoneCodeMySQL = `
INSERT INTO {{prefix}}phone_codes (
	id,
	scope,
	subject_id,
	phone_number,
	code_hash,
	attempts,
	max_attempts,
	issued_at,
	expires_at,
	purge_after,
	redeemed_at,
	revoked_at
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?,
	?
)
ON DUPLICATE KEY UPDATE
	id = VALUES(id),
	subject_id = VALUES(subject_id),
	code_hash = VALUES(code_hash),
	attempts = VALUES(attempts),
	max_attempts = VALUES(max_attempts),
	issued_at = VALUES(issued_at),
	expires_at = VALUES(expires_at),
	purge_after = VALUES(purge_after),
	redeemed_at = VALUES(redeemed_at),
	revoked_at = VALUES(revoked_at)`

const listPhoneCodesForSubjectMySQL = `SELECT
	{{prefix}}phone_codes.id,
	{{prefix}}phone_codes.scope,
	{{prefix}}phone_codes.subject_id,
	{{prefix}}phone_codes.phone_number,
	{{prefix}}phone_codes.attempts,
	{{prefix}}phone_codes.max_attempts,
	{{prefix}}phone_codes.issued_at,
	{{prefix}}phone_codes.expires_at,
	{{prefix}}phone_codes.purge_after,
	{{prefix}}phone_codes.redeemed_at,
	{{prefix}}phone_codes.revoked_at
FROM {{prefix}}phone_codes
WHERE {{prefix}}phone_codes.scope = ?
	AND {{prefix}}phone_codes.subject_id = ?
ORDER BY {{prefix}}phone_codes.issued_at ASC`

const revokePhoneCodesForSubjectMySQL = `UPDATE {{prefix}}phone_codes SET
	revoked_at = ?
WHERE scope = ?
	AND subject_id = ?
	AND redeemed_at IS NULL
	AND revoked_at IS NULL`

const spendPhoneCodeMySQL = `UPDATE {{prefix}}phone_codes SET
	redeemed_at = ?
WHERE id = ?
	AND scope = ?
	AND code_hash = ?
	AND redeemed_at IS NULL
	AND revoked_at IS NULL
	AND expires_at > ?
	AND attempts = ?`

const sweepPhoneCodesMySQL = `DELETE FROM {{prefix}}phone_codes
WHERE purge_after <= ?`

// mysqlQueries answers every query in Querier against mysql.
type mysqlQueries struct {
	countPhoneCodeAttempt      string
	deletePhoneCodesForSubject string
	getPhoneCode               string
	issuePhoneCode             string
	listPhoneCodesForSubject   string
	revokePhoneCodesForSubject string
	spendPhoneCode             string
	sweepPhoneCodes            string
}

// newMySQL returns the mysql querier with prefix substituted into every
// table name the analyzer identified.
func newMySQL(prefix string) *mysqlQueries {
	return &mysqlQueries{
		countPhoneCodeAttempt:      strings.ReplaceAll(countPhoneCodeAttemptMySQL, prefixMarker, prefix),
		deletePhoneCodesForSubject: strings.ReplaceAll(deletePhoneCodesForSubjectMySQL, prefixMarker, prefix),
		getPhoneCode:               strings.ReplaceAll(getPhoneCodeMySQL, prefixMarker, prefix),
		issuePhoneCode:             strings.ReplaceAll(issuePhoneCodeMySQL, prefixMarker, prefix),
		listPhoneCodesForSubject:   strings.ReplaceAll(listPhoneCodesForSubjectMySQL, prefixMarker, prefix),
		revokePhoneCodesForSubject: strings.ReplaceAll(revokePhoneCodesForSubjectMySQL, prefixMarker, prefix),
		spendPhoneCode:             strings.ReplaceAll(spendPhoneCodeMySQL, prefixMarker, prefix),
		sweepPhoneCodes:            strings.ReplaceAll(sweepPhoneCodesMySQL, prefixMarker, prefix),
	}
}

// CountPhoneCodeAttempt runs the :execrows query against mysql.
func (q *mysqlQueries) CountPhoneCodeAttempt(ctx context.Context, db DBTX, arg CountPhoneCodeAttemptParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.countPhoneCodeAttempt,
		arg.Attempts,
		arg.ID,
		arg.Scope,
		arg.Now,
		arg.ExpectedAttempts,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeletePhoneCodesForSubject runs the :execrows query against mysql.
func (q *mysqlQueries) DeletePhoneCodesForSubject(ctx context.Context, db DBTX, arg DeletePhoneCodesForSubjectParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deletePhoneCodesForSubject,
		arg.Scope,
		arg.SubjectID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetPhoneCode runs the :one query against mysql.
func (q *mysqlQueries) GetPhoneCode(ctx context.Context, db DBTX, arg GetPhoneCodeParams) (GetPhoneCodeRow, error) {
	row := db.QueryRowContext(ctx, q.getPhoneCode,
		arg.Scope,
		arg.PhoneNumber,
	)

	var i GetPhoneCodeRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.SubjectID,
		&i.PhoneNumber,
		&i.Attempts,
		&i.MaxAttempts,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.PurgeAfter,
		&i.RedeemedAt,
		&i.RevokedAt,
	)

	return i, err
}

// IssuePhoneCode runs the :exec query against mysql.
func (q *mysqlQueries) IssuePhoneCode(ctx context.Context, db DBTX, arg IssuePhoneCodeParams) error {
	_, err := db.ExecContext(ctx, q.issuePhoneCode,
		arg.ID,
		arg.Scope,
		arg.SubjectID,
		arg.PhoneNumber,
		arg.CodeHash,
		arg.Attempts,
		arg.MaxAttempts,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.PurgeAfter,
		arg.RedeemedAt,
		arg.RevokedAt,
	)

	return err
}

// ListPhoneCodesForSubject runs the :many query against mysql.
func (q *mysqlQueries) ListPhoneCodesForSubject(ctx context.Context, db DBTX, arg ListPhoneCodesForSubjectParams) ([]ListPhoneCodesForSubjectRow, error) {
	rows, err := db.QueryContext(ctx, q.listPhoneCodesForSubject,
		arg.Scope,
		arg.SubjectID,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListPhoneCodesForSubjectRow

	for rows.Next() {
		var i ListPhoneCodesForSubjectRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.SubjectID,
			&i.PhoneNumber,
			&i.Attempts,
			&i.MaxAttempts,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.PurgeAfter,
			&i.RedeemedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// RevokePhoneCodesForSubject runs the :execrows query against mysql.
func (q *mysqlQueries) RevokePhoneCodesForSubject(ctx context.Context, db DBTX, arg RevokePhoneCodesForSubjectParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.revokePhoneCodesForSubject,
		arg.RevokedAt,
		arg.Scope,
		arg.SubjectID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SpendPhoneCode runs the :execrows query against mysql.
func (q *mysqlQueries) SpendPhoneCode(ctx context.Context, db DBTX, arg SpendPhoneCodeParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.spendPhoneCode,
		arg.RedeemedAt,
		arg.ID,
		arg.Scope,
		arg.CodeHash,
		arg.Now,
		arg.ExpectedAttempts,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SweepPhoneCodes runs the :execrows query against mysql.
func (q *mysqlQueries) SweepPhoneCodes(ctx context.Context, db DBTX, arg SweepPhoneCodesParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepPhoneCodes,
		arg.PurgeBefore,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		Attempts         int64
		ID               string
		Scope            tenancy.Scope
		Now              time.Time
		ExpectedAttempts int64
	}(CountPhoneCodeAttemptParams{})
	_ = struct {
		Scope     tenancy.Scope
		SubjectID string
	}(DeletePhoneCodesForSubjectParams{})
	_ = struct {
		Scope       tenancy.Scope
		PhoneNumber string
	}(GetPhoneCodeParams{})
	_ = struct {
		ID          string
		Scope       tenancy.Scope
		SubjectID   string
		PhoneNumber string
		Attempts    int64
		MaxAttempts int64
		IssuedAt    time.Time
		ExpiresAt   time.Time
		PurgeAfter  time.Time
		RedeemedAt  *time.Time
		RevokedAt   *time.Time
	}(GetPhoneCodeRow{})
	_ = struct {
		ID          string
		Scope       tenancy.Scope
		SubjectID   string
		PhoneNumber string
		CodeHash    string
		Attempts    int64
		MaxAttempts int64
		IssuedAt    time.Time
		ExpiresAt   time.Time
		PurgeAfter  time.Time
		RedeemedAt  *time.Time
		RevokedAt   *time.Time
	}(IssuePhoneCodeParams{})
	_ = struct {
		Scope     tenancy.Scope
		SubjectID string
	}(ListPhoneCodesForSubjectParams{})
	_ = struct {
		ID          string
		Scope       tenancy.Scope
		SubjectID   string
		PhoneNumber string
		Attempts    int64
		MaxAttempts int64
		IssuedAt    time.Time
		ExpiresAt   time.Time
		PurgeAfter  time.Time
		RedeemedAt  *time.Time
		RevokedAt   *time.Time
	}(ListPhoneCodesForSubjectRow{})
	_ = struct {
		RevokedAt *time.Time
		Scope     tenancy.Scope
		SubjectID string
	}(RevokePhoneCodesForSubjectParams{})
	_ = struct {
		RedeemedAt       *time.Time
		ID               string
		Scope            tenancy.Scope
		CodeHash         string
		Now              time.Time
		ExpectedAttempts int64
	}(SpendPhoneCodeParams{})
	_ = struct {
		PurgeBefore time.Time
	}(SweepPhoneCodesParams{})
)
