-- Code generated by github.com/primandproper/platform-go/v14/timers/internal/queriesgen. DO NOT EDIT.

-- name: ScheduleTimer :exec
INSERT INTO scheduled_timers (
	timer_set,
	timer_key,
	run_at,
	payload,
	attempts,
	lease_until,
	created_at
) VALUES (
	sqlc.arg(timer_set),
	sqlc.arg(timer_key),
	(CAST('1970-01-01 00:00:00' AS DATETIME(6)) + INTERVAL sqlc.arg(run_at_microseconds) MICROSECOND),
	sqlc.narg(payload),
	0,
	'1970-01-01 00:00:00',
	(UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
)
ON DUPLICATE KEY UPDATE
	lease_until = CASE
		WHEN scheduled_timers.run_at <> VALUES(run_at) THEN '1970-01-01 00:00:00'
		ELSE scheduled_timers.lease_until
	END,
	leased_by = CASE
		WHEN scheduled_timers.run_at <> VALUES(run_at) THEN NULL
		ELSE scheduled_timers.leased_by
	END,
	run_at = VALUES(run_at),
	payload = VALUES(payload),
	attempts = 0,
	last_error = NULL,
	fired_at = NULL,
	last_updated_at = (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND);

-- name: SelectDueTimers :many
SELECT scheduled_timers.timer_key
FROM scheduled_timers
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NULL
	AND scheduled_timers.lease_until <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND scheduled_timers.run_at <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR scheduled_timers.attempts < sqlc.arg(attempt_ceiling))
ORDER BY scheduled_timers.run_at, scheduled_timers.timer_key
LIMIT ?, ?;

-- name: LockDueTimers :many
SELECT
	scheduled_timers.timer_key,
	(scheduled_timers.lease_until > '1970-01-01 00:00:00') AS reclaimed
FROM scheduled_timers FORCE INDEX (PRIMARY)
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NULL
	AND scheduled_timers.lease_until <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND scheduled_timers.run_at <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR scheduled_timers.attempts < sqlc.arg(attempt_ceiling))
	AND scheduled_timers.timer_key IN (sqlc.slice(timer_keys))
FOR UPDATE SKIP LOCKED;

-- name: LeaseTimers :execrows
UPDATE scheduled_timers FORCE INDEX (PRIMARY) SET
	lease_until = ((UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND) + INTERVAL sqlc.arg(lease_microseconds) MICROSECOND),
	leased_by = sqlc.arg(leased_by),
	attempts = scheduled_timers.attempts + 1
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NULL
	AND scheduled_timers.lease_until <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND scheduled_timers.run_at <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR scheduled_timers.attempts < sqlc.arg(attempt_ceiling))
	AND scheduled_timers.timer_key IN (sqlc.slice(timer_keys))
ORDER BY scheduled_timers.timer_key;

-- name: FetchLeasedTimers :many
SELECT
	scheduled_timers.timer_key,
	scheduled_timers.payload,
	(scheduled_timers.payload IS NOT NULL) AS has_payload,
	scheduled_timers.run_at,
	CAST(TIMESTAMPDIFF(MICROSECOND, scheduled_timers.run_at, (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)) AS SIGNED) AS late_microseconds,
	scheduled_timers.attempts
FROM scheduled_timers FORCE INDEX (PRIMARY)
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.leased_by = sqlc.arg(leased_by)
	AND scheduled_timers.timer_key IN (sqlc.slice(timer_keys))
ORDER BY scheduled_timers.run_at, scheduled_timers.timer_key;

-- name: ReadNextDueTimer :one
SELECT
	COUNT(*) AS outstanding,
	CAST(COALESCE(-TIMESTAMPDIFF(MICROSECOND, MIN(GREATEST(scheduled_timers.run_at, scheduled_timers.lease_until)), (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)), 0) AS SIGNED) AS next_due_microseconds
FROM scheduled_timers
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NULL
	AND (sqlc.arg(attempt_ceiling) <= 0 OR scheduled_timers.attempts < sqlc.arg(attempt_ceiling));

-- name: CompleteTimers :execrows
UPDATE scheduled_timers FORCE INDEX (PRIMARY) SET
	fired_at = (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND),
	lease_until = '1970-01-01 00:00:00',
	leased_by = NULL,
	last_error = NULL
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.leased_by = sqlc.arg(leased_by)
	AND scheduled_timers.timer_key IN (sqlc.slice(timer_keys))
ORDER BY scheduled_timers.timer_key;

-- name: ReleaseTimers :execrows
UPDATE scheduled_timers FORCE INDEX (PRIMARY) SET
	lease_until = '1970-01-01 00:00:00',
	leased_by = NULL,
	run_at = ((UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND) + INTERVAL sqlc.arg(delay_microseconds) MICROSECOND),
	last_error = sqlc.narg(last_error)
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NULL
	AND scheduled_timers.leased_by = sqlc.arg(leased_by)
	AND scheduled_timers.timer_key IN (sqlc.slice(timer_keys))
ORDER BY scheduled_timers.timer_key;

-- name: CancelTimers :execrows
DELETE /*+ INDEX(scheduled_timers PRIMARY) */ FROM scheduled_timers
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.timer_key IN (sqlc.slice(timer_keys))
ORDER BY scheduled_timers.timer_key;

-- name: SelectReapableTimers :many
SELECT scheduled_timers.timer_key
FROM scheduled_timers
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NOT NULL
	AND scheduled_timers.fired_at < ((UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND) - INTERVAL sqlc.arg(retention_microseconds) MICROSECOND)
ORDER BY scheduled_timers.fired_at
LIMIT ?;

-- name: DeleteReapedTimers :execrows
DELETE /*+ INDEX(scheduled_timers PRIMARY) */ FROM scheduled_timers
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NOT NULL
	AND scheduled_timers.fired_at < ((UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND) - INTERVAL sqlc.arg(retention_microseconds) MICROSECOND)
	AND scheduled_timers.timer_key IN (sqlc.slice(timer_keys))
ORDER BY scheduled_timers.timer_key;

-- name: ReadTimerStats :one
SELECT
	CAST(COALESCE(SUM(CASE WHEN scheduled_timers.fired_at IS NULL THEN 1 ELSE 0 END), 0) AS SIGNED) AS outstanding,
	CAST(COALESCE(SUM(CASE WHEN scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NULL
	AND scheduled_timers.lease_until <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND scheduled_timers.run_at <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR scheduled_timers.attempts < sqlc.arg(attempt_ceiling)) THEN 1 ELSE 0 END), 0) AS SIGNED) AS due,
	CAST(COALESCE(SUM(CASE WHEN scheduled_timers.fired_at IS NULL AND scheduled_timers.lease_until > (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND) THEN 1 ELSE 0 END), 0) AS SIGNED) AS leased,
	CAST(COALESCE(SUM(CASE WHEN scheduled_timers.fired_at IS NULL AND sqlc.arg(attempt_ceiling) > 0
		AND scheduled_timers.attempts >= sqlc.arg(attempt_ceiling) THEN 1 ELSE 0 END), 0) AS SIGNED) AS stalled,
	CAST(COALESCE(SUM(CASE WHEN scheduled_timers.fired_at IS NOT NULL THEN 1 ELSE 0 END), 0) AS SIGNED) AS fired,
	CAST(COALESCE(TIMESTAMPDIFF(MICROSECOND, MIN(CASE WHEN scheduled_timers.timer_set = sqlc.arg(timer_set)
	AND scheduled_timers.fired_at IS NULL
	AND scheduled_timers.lease_until <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND scheduled_timers.run_at <= (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)
	AND (sqlc.arg(attempt_ceiling) <= 0 OR scheduled_timers.attempts < sqlc.arg(attempt_ceiling)) THEN scheduled_timers.run_at END), (UTC_TIMESTAMP() + INTERVAL MICROSECOND(CURRENT_TIMESTAMP(6)) MICROSECOND)), 0) AS SIGNED) AS oldest_due_microseconds
FROM scheduled_timers
WHERE scheduled_timers.timer_set = sqlc.arg(timer_set);
