// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package settingsdb

import (
	"context"
	"strings"
	"time"

	"github.com/primandproper/primitives-go/tenancy"
)

const archiveDefinitionPostgreSQL = `UPDATE {{prefix}}settings_definitions SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = $1
	AND scope = $2`

const archiveValuePostgreSQL = `UPDATE {{prefix}}settings_values SET
	archived_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND scope = $1
	AND subject_type = $2
	AND subject_id = $3
	AND definition_id = $4`

const createDefinitionPostgreSQL = `
INSERT INTO {{prefix}}settings_definitions (
	id,
	scope,
	name,
	description,
	kind,
	default_value,
	admin_only
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)`

const deleteDefinitionOptionsPostgreSQL = `DELETE FROM {{prefix}}settings_definition_options
WHERE definition_id = $1`

const deleteValuesForSubjectPostgreSQL = `DELETE FROM {{prefix}}settings_values
WHERE scope = $1
	AND subject_type = $2
	AND subject_id = $3`

const getArchivedDefinitionPostgreSQL = `SELECT
	{{prefix}}settings_definitions.id,
	{{prefix}}settings_definitions.scope,
	{{prefix}}settings_definitions.name,
	{{prefix}}settings_definitions.description,
	{{prefix}}settings_definitions.kind,
	{{prefix}}settings_definitions.default_value,
	{{prefix}}settings_definitions.admin_only,
	{{prefix}}settings_definitions.created_at,
	{{prefix}}settings_definitions.last_updated_at,
	{{prefix}}settings_definitions.archived_at
FROM {{prefix}}settings_definitions
WHERE {{prefix}}settings_definitions.id = $1
	AND {{prefix}}settings_definitions.scope = $2
	AND {{prefix}}settings_definitions.archived_at IS NOT NULL`

const getArchivedValuePostgreSQL = `SELECT
	{{prefix}}settings_values.id,
	{{prefix}}settings_values.scope,
	{{prefix}}settings_values.definition_id,
	{{prefix}}settings_values.subject_type,
	{{prefix}}settings_values.subject_id,
	{{prefix}}settings_values.value,
	{{prefix}}settings_values.created_at,
	{{prefix}}settings_values.last_updated_at,
	{{prefix}}settings_values.archived_at
FROM {{prefix}}settings_values
WHERE {{prefix}}settings_values.scope = $1
	AND {{prefix}}settings_values.subject_type = $2
	AND {{prefix}}settings_values.subject_id = $3
	AND {{prefix}}settings_values.definition_id = $4
	AND {{prefix}}settings_values.archived_at IS NOT NULL`

const getDefinitionPostgreSQL = `SELECT
	{{prefix}}settings_definitions.id,
	{{prefix}}settings_definitions.scope,
	{{prefix}}settings_definitions.name,
	{{prefix}}settings_definitions.description,
	{{prefix}}settings_definitions.kind,
	{{prefix}}settings_definitions.default_value,
	{{prefix}}settings_definitions.admin_only,
	{{prefix}}settings_definitions.created_at,
	{{prefix}}settings_definitions.last_updated_at,
	{{prefix}}settings_definitions.archived_at
FROM {{prefix}}settings_definitions
WHERE {{prefix}}settings_definitions.archived_at IS NULL
	AND {{prefix}}settings_definitions.id = $1
	AND {{prefix}}settings_definitions.scope = $2`

const getDefinitionByNamePostgreSQL = `SELECT
	{{prefix}}settings_definitions.id,
	{{prefix}}settings_definitions.scope,
	{{prefix}}settings_definitions.name,
	{{prefix}}settings_definitions.description,
	{{prefix}}settings_definitions.kind,
	{{prefix}}settings_definitions.default_value,
	{{prefix}}settings_definitions.admin_only,
	{{prefix}}settings_definitions.created_at,
	{{prefix}}settings_definitions.last_updated_at,
	{{prefix}}settings_definitions.archived_at
FROM {{prefix}}settings_definitions
WHERE {{prefix}}settings_definitions.archived_at IS NULL
	AND {{prefix}}settings_definitions.name = $1
	AND {{prefix}}settings_definitions.scope = $2`

const getDefinitionCreatedAtPostgreSQL = `SELECT
	{{prefix}}settings_definitions.created_at
FROM {{prefix}}settings_definitions
WHERE {{prefix}}settings_definitions.id = $1`

const getDefinitionIdbyNamePostgreSQL = `SELECT
	{{prefix}}settings_definitions.id
FROM {{prefix}}settings_definitions
WHERE {{prefix}}settings_definitions.name = $1
	AND {{prefix}}settings_definitions.scope = $2
	AND {{prefix}}settings_definitions.id <> COALESCE($3, '')`

const getValuePostgreSQL = `SELECT
	{{prefix}}settings_values.id,
	{{prefix}}settings_values.scope,
	{{prefix}}settings_values.definition_id,
	{{prefix}}settings_values.subject_type,
	{{prefix}}settings_values.subject_id,
	{{prefix}}settings_values.value,
	{{prefix}}settings_values.created_at,
	{{prefix}}settings_values.last_updated_at,
	{{prefix}}settings_values.archived_at
FROM {{prefix}}settings_values
WHERE {{prefix}}settings_values.archived_at IS NULL
	AND {{prefix}}settings_values.scope = $1
	AND {{prefix}}settings_values.subject_type = $2
	AND {{prefix}}settings_values.subject_id = $3
	AND {{prefix}}settings_values.definition_id = $4`

const insertDefinitionOptionPostgreSQL = `INSERT INTO {{prefix}}settings_definition_options (
	definition_id,
	value
) VALUES (
	$1,
	$2
)`

const listDefinitionOptionsByDefinitionIDsPostgreSQL = `SELECT
	{{prefix}}settings_definition_options.definition_id,
	{{prefix}}settings_definition_options.value
FROM {{prefix}}settings_definition_options
WHERE {{prefix}}settings_definition_options.definition_id = ANY($1::text[])
ORDER BY {{prefix}}settings_definition_options.definition_id ASC, {{prefix}}settings_definition_options.value ASC`

const listDefinitionsPostgreSQL = `SELECT
	{{prefix}}settings_definitions.id,
	{{prefix}}settings_definitions.scope,
	{{prefix}}settings_definitions.name,
	{{prefix}}settings_definitions.description,
	{{prefix}}settings_definitions.kind,
	{{prefix}}settings_definitions.default_value,
	{{prefix}}settings_definitions.admin_only,
	{{prefix}}settings_definitions.created_at,
	{{prefix}}settings_definitions.last_updated_at,
	{{prefix}}settings_definitions.archived_at,
	(
		SELECT COUNT({{prefix}}settings_definitions.id)
		FROM {{prefix}}settings_definitions
		WHERE {{prefix}}settings_definitions.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}settings_definitions.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}settings_definitions.last_updated_at IS NULL
				OR {{prefix}}settings_definitions.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}settings_definitions.last_updated_at IS NULL
				OR {{prefix}}settings_definitions.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}settings_definitions.archived_at IS NULL)
			AND {{prefix}}settings_definitions.scope = $6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}settings_definitions.id)
		FROM {{prefix}}settings_definitions
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}settings_definitions.archived_at IS NULL)
			AND {{prefix}}settings_definitions.scope = $6
	) AS total_count
FROM {{prefix}}settings_definitions
WHERE {{prefix}}settings_definitions.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}settings_definitions.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}settings_definitions.last_updated_at IS NULL
		OR {{prefix}}settings_definitions.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}settings_definitions.last_updated_at IS NULL
		OR {{prefix}}settings_definitions.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}settings_definitions.archived_at IS NULL)
	AND {{prefix}}settings_definitions.scope = $6
	AND {{prefix}}settings_definitions.id > COALESCE($7, '')
ORDER BY {{prefix}}settings_definitions.id ASC
LIMIT COALESCE($8, 50)`

const listDefinitionsDescendingPostgreSQL = `SELECT
	{{prefix}}settings_definitions.id,
	{{prefix}}settings_definitions.scope,
	{{prefix}}settings_definitions.name,
	{{prefix}}settings_definitions.description,
	{{prefix}}settings_definitions.kind,
	{{prefix}}settings_definitions.default_value,
	{{prefix}}settings_definitions.admin_only,
	{{prefix}}settings_definitions.created_at,
	{{prefix}}settings_definitions.last_updated_at,
	{{prefix}}settings_definitions.archived_at,
	(
		SELECT COUNT({{prefix}}settings_definitions.id)
		FROM {{prefix}}settings_definitions
		WHERE {{prefix}}settings_definitions.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}settings_definitions.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}settings_definitions.last_updated_at IS NULL
				OR {{prefix}}settings_definitions.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}settings_definitions.last_updated_at IS NULL
				OR {{prefix}}settings_definitions.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}settings_definitions.archived_at IS NULL)
			AND {{prefix}}settings_definitions.scope = $6
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}settings_definitions.id)
		FROM {{prefix}}settings_definitions
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}settings_definitions.archived_at IS NULL)
			AND {{prefix}}settings_definitions.scope = $6
	) AS total_count
FROM {{prefix}}settings_definitions
WHERE {{prefix}}settings_definitions.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}settings_definitions.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}settings_definitions.last_updated_at IS NULL
		OR {{prefix}}settings_definitions.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}settings_definitions.last_updated_at IS NULL
		OR {{prefix}}settings_definitions.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}settings_definitions.archived_at IS NULL)
	AND {{prefix}}settings_definitions.scope = $6
	AND ({{prefix}}settings_definitions.id <= COALESCE($7, {{prefix}}settings_definitions.id) AND {{prefix}}settings_definitions.id <> COALESCE($7, ''))
ORDER BY {{prefix}}settings_definitions.id DESC
LIMIT COALESCE($8, 50)`

const listValuesForDefinitionPostgreSQL = `SELECT
	{{prefix}}settings_values.id,
	{{prefix}}settings_values.scope,
	{{prefix}}settings_values.definition_id,
	{{prefix}}settings_values.subject_type,
	{{prefix}}settings_values.subject_id,
	{{prefix}}settings_values.value,
	{{prefix}}settings_values.created_at,
	{{prefix}}settings_values.last_updated_at,
	{{prefix}}settings_values.archived_at,
	(
		SELECT COUNT({{prefix}}settings_values.id)
		FROM {{prefix}}settings_values
		WHERE {{prefix}}settings_values.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}settings_values.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}settings_values.last_updated_at IS NULL
				OR {{prefix}}settings_values.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}settings_values.last_updated_at IS NULL
				OR {{prefix}}settings_values.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
			AND {{prefix}}settings_values.scope = $6
			AND {{prefix}}settings_values.definition_id = $7
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}settings_values.id)
		FROM {{prefix}}settings_values
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
			AND {{prefix}}settings_values.scope = $6
			AND {{prefix}}settings_values.definition_id = $7
	) AS total_count
FROM {{prefix}}settings_values
WHERE {{prefix}}settings_values.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}settings_values.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}settings_values.last_updated_at IS NULL
		OR {{prefix}}settings_values.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}settings_values.last_updated_at IS NULL
		OR {{prefix}}settings_values.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
	AND {{prefix}}settings_values.scope = $6
	AND {{prefix}}settings_values.definition_id = $7
	AND {{prefix}}settings_values.id > COALESCE($8, '')
ORDER BY {{prefix}}settings_values.id ASC
LIMIT COALESCE($9, 50)`

const listValuesForDefinitionDescendingPostgreSQL = `SELECT
	{{prefix}}settings_values.id,
	{{prefix}}settings_values.scope,
	{{prefix}}settings_values.definition_id,
	{{prefix}}settings_values.subject_type,
	{{prefix}}settings_values.subject_id,
	{{prefix}}settings_values.value,
	{{prefix}}settings_values.created_at,
	{{prefix}}settings_values.last_updated_at,
	{{prefix}}settings_values.archived_at,
	(
		SELECT COUNT({{prefix}}settings_values.id)
		FROM {{prefix}}settings_values
		WHERE {{prefix}}settings_values.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}settings_values.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}settings_values.last_updated_at IS NULL
				OR {{prefix}}settings_values.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}settings_values.last_updated_at IS NULL
				OR {{prefix}}settings_values.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
			AND {{prefix}}settings_values.scope = $6
			AND {{prefix}}settings_values.definition_id = $7
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}settings_values.id)
		FROM {{prefix}}settings_values
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
			AND {{prefix}}settings_values.scope = $6
			AND {{prefix}}settings_values.definition_id = $7
	) AS total_count
FROM {{prefix}}settings_values
WHERE {{prefix}}settings_values.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}settings_values.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}settings_values.last_updated_at IS NULL
		OR {{prefix}}settings_values.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}settings_values.last_updated_at IS NULL
		OR {{prefix}}settings_values.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
	AND {{prefix}}settings_values.scope = $6
	AND {{prefix}}settings_values.definition_id = $7
	AND ({{prefix}}settings_values.id <= COALESCE($8, {{prefix}}settings_values.id) AND {{prefix}}settings_values.id <> COALESCE($8, ''))
ORDER BY {{prefix}}settings_values.id DESC
LIMIT COALESCE($9, 50)`

const listValuesForSubjectPostgreSQL = `SELECT
	{{prefix}}settings_values.id,
	{{prefix}}settings_values.scope,
	{{prefix}}settings_values.definition_id,
	{{prefix}}settings_values.subject_type,
	{{prefix}}settings_values.subject_id,
	{{prefix}}settings_values.value,
	{{prefix}}settings_values.created_at,
	{{prefix}}settings_values.last_updated_at,
	{{prefix}}settings_values.archived_at,
	(
		SELECT COUNT({{prefix}}settings_values.id)
		FROM {{prefix}}settings_values
		WHERE {{prefix}}settings_values.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}settings_values.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}settings_values.last_updated_at IS NULL
				OR {{prefix}}settings_values.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}settings_values.last_updated_at IS NULL
				OR {{prefix}}settings_values.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
			AND {{prefix}}settings_values.scope = $6
			AND {{prefix}}settings_values.subject_type = $7
			AND {{prefix}}settings_values.subject_id = $8
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}settings_values.id)
		FROM {{prefix}}settings_values
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
			AND {{prefix}}settings_values.scope = $6
			AND {{prefix}}settings_values.subject_type = $7
			AND {{prefix}}settings_values.subject_id = $8
	) AS total_count
FROM {{prefix}}settings_values
WHERE {{prefix}}settings_values.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}settings_values.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}settings_values.last_updated_at IS NULL
		OR {{prefix}}settings_values.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}settings_values.last_updated_at IS NULL
		OR {{prefix}}settings_values.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
	AND {{prefix}}settings_values.scope = $6
	AND {{prefix}}settings_values.subject_type = $7
	AND {{prefix}}settings_values.subject_id = $8
	AND {{prefix}}settings_values.id > COALESCE($9, '')
ORDER BY {{prefix}}settings_values.id ASC
LIMIT COALESCE($10, 50)`

const listValuesForSubjectDescendingPostgreSQL = `SELECT
	{{prefix}}settings_values.id,
	{{prefix}}settings_values.scope,
	{{prefix}}settings_values.definition_id,
	{{prefix}}settings_values.subject_type,
	{{prefix}}settings_values.subject_id,
	{{prefix}}settings_values.value,
	{{prefix}}settings_values.created_at,
	{{prefix}}settings_values.last_updated_at,
	{{prefix}}settings_values.archived_at,
	(
		SELECT COUNT({{prefix}}settings_values.id)
		FROM {{prefix}}settings_values
		WHERE {{prefix}}settings_values.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			AND {{prefix}}settings_values.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			AND (
				{{prefix}}settings_values.last_updated_at IS NULL
				OR {{prefix}}settings_values.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
			)
			AND (
				{{prefix}}settings_values.last_updated_at IS NULL
				OR {{prefix}}settings_values.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
			)
			AND (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
			AND {{prefix}}settings_values.scope = $6
			AND {{prefix}}settings_values.subject_type = $7
			AND {{prefix}}settings_values.subject_id = $8
	) AS filtered_count,
	(
		SELECT COUNT({{prefix}}settings_values.id)
		FROM {{prefix}}settings_values
		WHERE (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
			AND {{prefix}}settings_values.scope = $6
			AND {{prefix}}settings_values.subject_type = $7
			AND {{prefix}}settings_values.subject_id = $8
	) AS total_count
FROM {{prefix}}settings_values
WHERE {{prefix}}settings_values.created_at > COALESCE($1, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	AND {{prefix}}settings_values.created_at < COALESCE($2, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	AND (
		{{prefix}}settings_values.last_updated_at IS NULL
		OR {{prefix}}settings_values.last_updated_at > COALESCE($3, (SELECT CURRENT_TIMESTAMP - '999 years'::INTERVAL))
	)
	AND (
		{{prefix}}settings_values.last_updated_at IS NULL
		OR {{prefix}}settings_values.last_updated_at < COALESCE($4, (SELECT CURRENT_TIMESTAMP + '999 years'::INTERVAL))
	)
	AND (COALESCE($5, false)::boolean OR {{prefix}}settings_values.archived_at IS NULL)
	AND {{prefix}}settings_values.scope = $6
	AND {{prefix}}settings_values.subject_type = $7
	AND {{prefix}}settings_values.subject_id = $8
	AND ({{prefix}}settings_values.id <= COALESCE($9, {{prefix}}settings_values.id) AND {{prefix}}settings_values.id <> COALESCE($9, ''))
ORDER BY {{prefix}}settings_values.id DESC
LIMIT COALESCE($10, 50)`

const updateDefinitionPostgreSQL = `UPDATE {{prefix}}settings_definitions SET
	name = $1,
	description = $2,
	kind = $3,
	default_value = $4,
	admin_only = $5,
	last_updated_at = CURRENT_TIMESTAMP
WHERE archived_at IS NULL
	AND id = $6
	AND scope = $7`

const upsertValuePostgreSQL = `INSERT INTO {{prefix}}settings_values (
	id,
	scope,
	definition_id,
	subject_type,
	subject_id,
	value
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
)
ON CONFLICT (scope, subject_type, subject_id, definition_id) DO UPDATE SET
	value = EXCLUDED.value,
	archived_at = NULL,
	last_updated_at = CURRENT_TIMESTAMP`

// postgresqlQueries answers every query in Querier against postgresql.
type postgresqlQueries struct {
	archiveDefinition                    string
	archiveValue                         string
	createDefinition                     string
	deleteDefinitionOptions              string
	deleteValuesForSubject               string
	getArchivedDefinition                string
	getArchivedValue                     string
	getDefinition                        string
	getDefinitionByName                  string
	getDefinitionCreatedAt               string
	getDefinitionIdbyName                string
	getValue                             string
	insertDefinitionOption               string
	listDefinitionOptionsByDefinitionIDs string
	listDefinitions                      string
	listDefinitionsDescending            string
	listValuesForDefinition              string
	listValuesForDefinitionDescending    string
	listValuesForSubject                 string
	listValuesForSubjectDescending       string
	updateDefinition                     string
	upsertValue                          string
}

// newPostgreSQL returns the postgresql querier with prefix substituted into every
// table name the analyzer identified.
func newPostgreSQL(prefix string) *postgresqlQueries {
	return &postgresqlQueries{
		archiveDefinition:                    strings.ReplaceAll(archiveDefinitionPostgreSQL, prefixMarker, prefix),
		archiveValue:                         strings.ReplaceAll(archiveValuePostgreSQL, prefixMarker, prefix),
		createDefinition:                     strings.ReplaceAll(createDefinitionPostgreSQL, prefixMarker, prefix),
		deleteDefinitionOptions:              strings.ReplaceAll(deleteDefinitionOptionsPostgreSQL, prefixMarker, prefix),
		deleteValuesForSubject:               strings.ReplaceAll(deleteValuesForSubjectPostgreSQL, prefixMarker, prefix),
		getArchivedDefinition:                strings.ReplaceAll(getArchivedDefinitionPostgreSQL, prefixMarker, prefix),
		getArchivedValue:                     strings.ReplaceAll(getArchivedValuePostgreSQL, prefixMarker, prefix),
		getDefinition:                        strings.ReplaceAll(getDefinitionPostgreSQL, prefixMarker, prefix),
		getDefinitionByName:                  strings.ReplaceAll(getDefinitionByNamePostgreSQL, prefixMarker, prefix),
		getDefinitionCreatedAt:               strings.ReplaceAll(getDefinitionCreatedAtPostgreSQL, prefixMarker, prefix),
		getDefinitionIdbyName:                strings.ReplaceAll(getDefinitionIdbyNamePostgreSQL, prefixMarker, prefix),
		getValue:                             strings.ReplaceAll(getValuePostgreSQL, prefixMarker, prefix),
		insertDefinitionOption:               strings.ReplaceAll(insertDefinitionOptionPostgreSQL, prefixMarker, prefix),
		listDefinitionOptionsByDefinitionIDs: strings.ReplaceAll(listDefinitionOptionsByDefinitionIDsPostgreSQL, prefixMarker, prefix),
		listDefinitions:                      strings.ReplaceAll(listDefinitionsPostgreSQL, prefixMarker, prefix),
		listDefinitionsDescending:            strings.ReplaceAll(listDefinitionsDescendingPostgreSQL, prefixMarker, prefix),
		listValuesForDefinition:              strings.ReplaceAll(listValuesForDefinitionPostgreSQL, prefixMarker, prefix),
		listValuesForDefinitionDescending:    strings.ReplaceAll(listValuesForDefinitionDescendingPostgreSQL, prefixMarker, prefix),
		listValuesForSubject:                 strings.ReplaceAll(listValuesForSubjectPostgreSQL, prefixMarker, prefix),
		listValuesForSubjectDescending:       strings.ReplaceAll(listValuesForSubjectDescendingPostgreSQL, prefixMarker, prefix),
		updateDefinition:                     strings.ReplaceAll(updateDefinitionPostgreSQL, prefixMarker, prefix),
		upsertValue:                          strings.ReplaceAll(upsertValuePostgreSQL, prefixMarker, prefix),
	}
}

// ArchiveDefinition runs the :execrows query against postgresql.
func (q *postgresqlQueries) ArchiveDefinition(ctx context.Context, db DBTX, arg ArchiveDefinitionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveDefinition,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// ArchiveValue runs the :execrows query against postgresql.
func (q *postgresqlQueries) ArchiveValue(ctx context.Context, db DBTX, arg ArchiveValueParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.archiveValue,
		arg.Scope,
		arg.SubjectType,
		arg.SubjectID,
		arg.DefinitionID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// CreateDefinition runs the :exec query against postgresql.
func (q *postgresqlQueries) CreateDefinition(ctx context.Context, db DBTX, arg CreateDefinitionParams) error {
	_, err := db.ExecContext(ctx, q.createDefinition,
		arg.ID,
		arg.Scope,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.DefaultValue,
		arg.AdminOnly,
	)

	return err
}

// DeleteDefinitionOptions runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteDefinitionOptions(ctx context.Context, db DBTX, arg DeleteDefinitionOptionsParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteDefinitionOptions,
		arg.DefinitionID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// DeleteValuesForSubject runs the :execrows query against postgresql.
func (q *postgresqlQueries) DeleteValuesForSubject(ctx context.Context, db DBTX, arg DeleteValuesForSubjectParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteValuesForSubject,
		arg.Scope,
		arg.SubjectType,
		arg.SubjectID,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetArchivedDefinition runs the :one query against postgresql.
func (q *postgresqlQueries) GetArchivedDefinition(ctx context.Context, db DBTX, arg GetArchivedDefinitionParams) (GetArchivedDefinitionRow, error) {
	row := db.QueryRowContext(ctx, q.getArchivedDefinition,
		arg.ID,
		arg.Scope,
	)

	var i GetArchivedDefinitionRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.DefaultValue,
		&i.AdminOnly,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetArchivedValue runs the :one query against postgresql.
func (q *postgresqlQueries) GetArchivedValue(ctx context.Context, db DBTX, arg GetArchivedValueParams) (GetArchivedValueRow, error) {
	row := db.QueryRowContext(ctx, q.getArchivedValue,
		arg.Scope,
		arg.SubjectType,
		arg.SubjectID,
		arg.DefinitionID,
	)

	var i GetArchivedValueRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.DefinitionID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Value,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetDefinition runs the :one query against postgresql.
func (q *postgresqlQueries) GetDefinition(ctx context.Context, db DBTX, arg GetDefinitionParams) (GetDefinitionRow, error) {
	row := db.QueryRowContext(ctx, q.getDefinition,
		arg.ID,
		arg.Scope,
	)

	var i GetDefinitionRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.DefaultValue,
		&i.AdminOnly,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetDefinitionByName runs the :one query against postgresql.
func (q *postgresqlQueries) GetDefinitionByName(ctx context.Context, db DBTX, arg GetDefinitionByNameParams) (GetDefinitionByNameRow, error) {
	row := db.QueryRowContext(ctx, q.getDefinitionByName,
		arg.Name,
		arg.Scope,
	)

	var i GetDefinitionByNameRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.DefaultValue,
		&i.AdminOnly,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// GetDefinitionCreatedAt runs the :one query against postgresql.
func (q *postgresqlQueries) GetDefinitionCreatedAt(ctx context.Context, db DBTX, arg GetDefinitionCreatedAtParams) (GetDefinitionCreatedAtRow, error) {
	row := db.QueryRowContext(ctx, q.getDefinitionCreatedAt,
		arg.ID,
	)

	var i GetDefinitionCreatedAtRow

	err := row.Scan(
		&i.CreatedAt,
	)

	return i, err
}

// GetDefinitionIDByName runs the :one query against postgresql.
func (q *postgresqlQueries) GetDefinitionIDByName(ctx context.Context, db DBTX, arg GetDefinitionIDByNameParams) (GetDefinitionIDByNameRow, error) {
	row := db.QueryRowContext(ctx, q.getDefinitionIdbyName,
		arg.Name,
		arg.Scope,
		arg.ExceptDefinitionID,
	)

	var i GetDefinitionIDByNameRow

	err := row.Scan(
		&i.ID,
	)

	return i, err
}

// GetValue runs the :one query against postgresql.
func (q *postgresqlQueries) GetValue(ctx context.Context, db DBTX, arg GetValueParams) (GetValueRow, error) {
	row := db.QueryRowContext(ctx, q.getValue,
		arg.Scope,
		arg.SubjectType,
		arg.SubjectID,
		arg.DefinitionID,
	)

	var i GetValueRow

	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.DefinitionID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Value,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.ArchivedAt,
	)

	return i, err
}

// InsertDefinitionOption runs the :exec query against postgresql.
func (q *postgresqlQueries) InsertDefinitionOption(ctx context.Context, db DBTX, arg InsertDefinitionOptionParams) error {
	_, err := db.ExecContext(ctx, q.insertDefinitionOption,
		arg.DefinitionID,
		arg.Value,
	)

	return err
}

// ListDefinitionOptionsByDefinitionIDs runs the :many query against postgresql.
func (q *postgresqlQueries) ListDefinitionOptionsByDefinitionIDs(ctx context.Context, db DBTX, arg ListDefinitionOptionsByDefinitionIDsParams) ([]ListDefinitionOptionsByDefinitionIDsRow, error) {
	rows, err := db.QueryContext(ctx, q.listDefinitionOptionsByDefinitionIDs,
		arg.IDs,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListDefinitionOptionsByDefinitionIDsRow

	for rows.Next() {
		var i ListDefinitionOptionsByDefinitionIDsRow

		if err := rows.Scan(
			&i.DefinitionID,
			&i.Value,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListDefinitions runs the :many query against postgresql.
func (q *postgresqlQueries) ListDefinitions(ctx context.Context, db DBTX, arg ListDefinitionsParams) ([]ListDefinitionsRow, error) {
	rows, err := db.QueryContext(ctx, q.listDefinitions,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListDefinitionsRow

	for rows.Next() {
		var i ListDefinitionsRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.DefaultValue,
			&i.AdminOnly,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListDefinitionsDescending runs the :many query against postgresql.
func (q *postgresqlQueries) ListDefinitionsDescending(ctx context.Context, db DBTX, arg ListDefinitionsDescendingParams) ([]ListDefinitionsDescendingRow, error) {
	rows, err := db.QueryContext(ctx, q.listDefinitionsDescending,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListDefinitionsDescendingRow

	for rows.Next() {
		var i ListDefinitionsDescendingRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.DefaultValue,
			&i.AdminOnly,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListValuesForDefinition runs the :many query against postgresql.
func (q *postgresqlQueries) ListValuesForDefinition(ctx context.Context, db DBTX, arg ListValuesForDefinitionParams) ([]ListValuesForDefinitionRow, error) {
	rows, err := db.QueryContext(ctx, q.listValuesForDefinition,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.DefinitionID,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListValuesForDefinitionRow

	for rows.Next() {
		var i ListValuesForDefinitionRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.DefinitionID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Value,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListValuesForDefinitionDescending runs the :many query against postgresql.
func (q *postgresqlQueries) ListValuesForDefinitionDescending(ctx context.Context, db DBTX, arg ListValuesForDefinitionDescendingParams) ([]ListValuesForDefinitionDescendingRow, error) {
	rows, err := db.QueryContext(ctx, q.listValuesForDefinitionDescending,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.DefinitionID,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListValuesForDefinitionDescendingRow

	for rows.Next() {
		var i ListValuesForDefinitionDescendingRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.DefinitionID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Value,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListValuesForSubject runs the :many query against postgresql.
func (q *postgresqlQueries) ListValuesForSubject(ctx context.Context, db DBTX, arg ListValuesForSubjectParams) ([]ListValuesForSubjectRow, error) {
	rows, err := db.QueryContext(ctx, q.listValuesForSubject,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.SubjectType,
		arg.SubjectID,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListValuesForSubjectRow

	for rows.Next() {
		var i ListValuesForSubjectRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.DefinitionID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Value,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// ListValuesForSubjectDescending runs the :many query against postgresql.
func (q *postgresqlQueries) ListValuesForSubjectDescending(ctx context.Context, db DBTX, arg ListValuesForSubjectDescendingParams) ([]ListValuesForSubjectDescendingRow, error) {
	rows, err := db.QueryContext(ctx, q.listValuesForSubjectDescending,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.IncludeArchived,
		arg.Scope,
		arg.SubjectType,
		arg.SubjectID,
		arg.PageCursor,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []ListValuesForSubjectDescendingRow

	for rows.Next() {
		var i ListValuesForSubjectDescendingRow

		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.DefinitionID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Value,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.ArchivedAt,
			&i.FilteredCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// UpdateDefinition runs the :execrows query against postgresql.
func (q *postgresqlQueries) UpdateDefinition(ctx context.Context, db DBTX, arg UpdateDefinitionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.updateDefinition,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.DefaultValue,
		arg.AdminOnly,
		arg.ID,
		arg.Scope,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpsertValue runs the :exec query against postgresql.
func (q *postgresqlQueries) UpsertValue(ctx context.Context, db DBTX, arg UpsertValueParams) error {
	_, err := db.ExecContext(ctx, q.upsertValue,
		arg.ID,
		arg.Scope,
		arg.DefinitionID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Value,
	)

	return err
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(ArchiveDefinitionParams{})
	_ = struct {
		Scope        tenancy.Scope
		SubjectType  string
		SubjectID    string
		DefinitionID string
	}(ArchiveValueParams{})
	_ = struct {
		ID           string
		Scope        tenancy.Scope
		Name         string
		Description  string
		Kind         string
		DefaultValue *string
		AdminOnly    bool
	}(CreateDefinitionParams{})
	_ = struct {
		DefinitionID string
	}(DeleteDefinitionOptionsParams{})
	_ = struct {
		Scope       tenancy.Scope
		SubjectType string
		SubjectID   string
	}(DeleteValuesForSubjectParams{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetArchivedDefinitionParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		Name          string
		Description   string
		Kind          string
		DefaultValue  *string
		AdminOnly     bool
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetArchivedDefinitionRow{})
	_ = struct {
		Scope        tenancy.Scope
		SubjectType  string
		SubjectID    string
		DefinitionID string
	}(GetArchivedValueParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		DefinitionID  string
		SubjectType   string
		SubjectID     string
		Value         string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetArchivedValueRow{})
	_ = struct {
		ID    string
		Scope tenancy.Scope
	}(GetDefinitionParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		Name          string
		Description   string
		Kind          string
		DefaultValue  *string
		AdminOnly     bool
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetDefinitionRow{})
	_ = struct {
		Name  string
		Scope tenancy.Scope
	}(GetDefinitionByNameParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		Name          string
		Description   string
		Kind          string
		DefaultValue  *string
		AdminOnly     bool
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetDefinitionByNameRow{})
	_ = struct {
		ID string
	}(GetDefinitionCreatedAtParams{})
	_ = struct {
		CreatedAt time.Time
	}(GetDefinitionCreatedAtRow{})
	_ = struct {
		Name               string
		Scope              tenancy.Scope
		ExceptDefinitionID *string
	}(GetDefinitionIDByNameParams{})
	_ = struct {
		ID string
	}(GetDefinitionIDByNameRow{})
	_ = struct {
		Scope        tenancy.Scope
		SubjectType  string
		SubjectID    string
		DefinitionID string
	}(GetValueParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		DefinitionID  string
		SubjectType   string
		SubjectID     string
		Value         string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
	}(GetValueRow{})
	_ = struct {
		DefinitionID string
		Value        string
	}(InsertDefinitionOptionParams{})
	_ = struct {
		IDs []string
	}(ListDefinitionOptionsByDefinitionIDsParams{})
	_ = struct {
		DefinitionID string
		Value        string
	}(ListDefinitionOptionsByDefinitionIDsRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListDefinitionsParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		Name          string
		Description   string
		Kind          string
		DefaultValue  *string
		AdminOnly     bool
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListDefinitionsRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		PageCursor      *string
		ResultLimit     int64
	}(ListDefinitionsDescendingParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		Name          string
		Description   string
		Kind          string
		DefaultValue  *string
		AdminOnly     bool
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListDefinitionsDescendingRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		DefinitionID    string
		PageCursor      *string
		ResultLimit     int64
	}(ListValuesForDefinitionParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		DefinitionID  string
		SubjectType   string
		SubjectID     string
		Value         string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListValuesForDefinitionRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		DefinitionID    string
		PageCursor      *string
		ResultLimit     int64
	}(ListValuesForDefinitionDescendingParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		DefinitionID  string
		SubjectType   string
		SubjectID     string
		Value         string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListValuesForDefinitionDescendingRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		SubjectType     string
		SubjectID       string
		PageCursor      *string
		ResultLimit     int64
	}(ListValuesForSubjectParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		DefinitionID  string
		SubjectType   string
		SubjectID     string
		Value         string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListValuesForSubjectRow{})
	_ = struct {
		CreatedAfter    *time.Time
		CreatedBefore   *time.Time
		UpdatedAfter    *time.Time
		UpdatedBefore   *time.Time
		IncludeArchived bool
		Scope           tenancy.Scope
		SubjectType     string
		SubjectID       string
		PageCursor      *string
		ResultLimit     int64
	}(ListValuesForSubjectDescendingParams{})
	_ = struct {
		ID            string
		Scope         tenancy.Scope
		DefinitionID  string
		SubjectType   string
		SubjectID     string
		Value         string
		CreatedAt     time.Time
		LastUpdatedAt *time.Time
		ArchivedAt    *time.Time
		FilteredCount int64
		TotalCount    int64
	}(ListValuesForSubjectDescendingRow{})
	_ = struct {
		Name         string
		Description  string
		Kind         string
		DefaultValue *string
		AdminOnly    bool
		ID           string
		Scope        tenancy.Scope
	}(UpdateDefinitionParams{})
	_ = struct {
		ID           string
		Scope        tenancy.Scope
		DefinitionID string
		SubjectType  string
		SubjectID    string
		Value        string
	}(UpsertValueParams{})
)
