// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package settingsdb

import (
	"context"
)

// Querier is every query in this package, with one signature per query
// regardless of which dialect answers it.
//
// That is the point of this package: the params type, the row type, and the
// method signature are the same on every dialect, so nothing above this line
// knows or cares which database is underneath.
//
// # A note on the :execrows count
//
// MySQL reports rows *changed*: an UPDATE that sets a column to the value it
// already held affects zero rows there. Postgres and SQLite report rows
// *matched*, and count that same UPDATE as one.
//
// So a statement that gates on the count — treating zero as "not found" — is
// correct on two engines and wrong on the third. Either give it a predicate
// that discriminates, or set clientFoundRows=true in the MySQL DSN, which
// switches MySQL to matched semantics.
//
// # A note on empty lists
//
// A list parameter that is empty matches nothing, on every dialect: Postgres
// binds an empty array to `= ANY`, and the other two expand to `IN (NULL)` because
// `IN ()` is a syntax error there. Asking for the rows whose key is in an empty
// set gets no rows back, which is what the empty set says, so a caller does not
// have to guard the call.
//
// The negation is where they part company, and nothing below can warn you. An
// empty list makes `NOT IN (NULL)` never true, so it matches nothing, while
// Postgres's empty `<> ALL` is true and matches everything. Both readings are
// defensible and no shared signature can say which was meant — so test
// membership rather than its negation, and let the caller decide what an empty
// set means before it calls.
type Querier interface {
	// ArchiveDefinition runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ArchiveDefinition(ctx context.Context, db DBTX, arg ArchiveDefinitionParams) (int64, error)
	// ArchiveValue runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	ArchiveValue(ctx context.Context, db DBTX, arg ArchiveValueParams) (int64, error)
	// CreateDefinition runs the :exec query.
	CreateDefinition(ctx context.Context, db DBTX, arg CreateDefinitionParams) error
	// DeleteDefinitionOptions runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	DeleteDefinitionOptions(ctx context.Context, db DBTX, arg DeleteDefinitionOptionsParams) (int64, error)
	// DeleteValuesForSubject runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	DeleteValuesForSubject(ctx context.Context, db DBTX, arg DeleteValuesForSubjectParams) (int64, error)
	// GetArchivedValue runs the :one query.
	GetArchivedValue(ctx context.Context, db DBTX, arg GetArchivedValueParams) (GetArchivedValueRow, error)
	// GetDefinition runs the :one query.
	GetDefinition(ctx context.Context, db DBTX, arg GetDefinitionParams) (GetDefinitionRow, error)
	// GetDefinitionByName runs the :one query.
	GetDefinitionByName(ctx context.Context, db DBTX, arg GetDefinitionByNameParams) (GetDefinitionByNameRow, error)
	// GetDefinitionCreatedAt runs the :one query.
	GetDefinitionCreatedAt(ctx context.Context, db DBTX, arg GetDefinitionCreatedAtParams) (GetDefinitionCreatedAtRow, error)
	// GetDefinitionIDByName runs the :one query.
	GetDefinitionIDByName(ctx context.Context, db DBTX, arg GetDefinitionIDByNameParams) (GetDefinitionIDByNameRow, error)
	// GetValue runs the :one query.
	GetValue(ctx context.Context, db DBTX, arg GetValueParams) (GetValueRow, error)
	// InsertDefinitionOption runs the :exec query.
	InsertDefinitionOption(ctx context.Context, db DBTX, arg InsertDefinitionOptionParams) error
	// ListDefinitionOptionsByDefinitionIDs runs the :many query.
	ListDefinitionOptionsByDefinitionIDs(ctx context.Context, db DBTX, arg ListDefinitionOptionsByDefinitionIDsParams) ([]ListDefinitionOptionsByDefinitionIDsRow, error)
	// ListDefinitions runs the :many query.
	ListDefinitions(ctx context.Context, db DBTX, arg ListDefinitionsParams) ([]ListDefinitionsRow, error)
	// ListDefinitionsDescending runs the :many query.
	ListDefinitionsDescending(ctx context.Context, db DBTX, arg ListDefinitionsDescendingParams) ([]ListDefinitionsDescendingRow, error)
	// ListValuesForDefinition runs the :many query.
	ListValuesForDefinition(ctx context.Context, db DBTX, arg ListValuesForDefinitionParams) ([]ListValuesForDefinitionRow, error)
	// ListValuesForDefinitionDescending runs the :many query.
	ListValuesForDefinitionDescending(ctx context.Context, db DBTX, arg ListValuesForDefinitionDescendingParams) ([]ListValuesForDefinitionDescendingRow, error)
	// ListValuesForSubject runs the :many query.
	ListValuesForSubject(ctx context.Context, db DBTX, arg ListValuesForSubjectParams) ([]ListValuesForSubjectRow, error)
	// ListValuesForSubjectDescending runs the :many query.
	ListValuesForSubjectDescending(ctx context.Context, db DBTX, arg ListValuesForSubjectDescendingParams) ([]ListValuesForSubjectDescendingRow, error)
	// UpdateDefinition runs the :execrows query.
	//
	// The count means different things on different engines; see the note
	// on Querier.
	UpdateDefinition(ctx context.Context, db DBTX, arg UpdateDefinitionParams) (int64, error)
	// UpsertValue runs the :exec query.
	UpsertValue(ctx context.Context, db DBTX, arg UpsertValueParams) error
}
