// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package webauthndb

import (
	"context"
	"strings"
	"time"
)

const deleteSessionSQLite = `DELETE FROM {{prefix}}webauthn_sessions
WHERE challenge = ?1`

const getSessionSQLite = `SELECT
	{{prefix}}webauthn_sessions.session_data,
	{{prefix}}webauthn_sessions.expires_at
FROM {{prefix}}webauthn_sessions
WHERE {{prefix}}webauthn_sessions.challenge = ?1`

const sweepExpiredSessionsSQLite = `DELETE FROM {{prefix}}webauthn_sessions
WHERE expires_at <= CURRENT_TIMESTAMP`

const upsertSessionSQLite = `
INSERT INTO {{prefix}}webauthn_sessions (
	challenge,
	session_data,
	expires_at
) VALUES (
	?1,
	?2,
	?3
)
ON CONFLICT (challenge) DO UPDATE SET
	session_data = EXCLUDED.session_data,
	expires_at = EXCLUDED.expires_at`

// sqliteQueries answers every query in Querier against sqlite.
type sqliteQueries struct {
	deleteSession        string
	getSession           string
	sweepExpiredSessions string
	upsertSession        string
}

// newSQLite returns the sqlite querier with prefix substituted into every
// table name the analyzer identified.
func newSQLite(prefix string) *sqliteQueries {
	return &sqliteQueries{
		deleteSession:        strings.ReplaceAll(deleteSessionSQLite, prefixMarker, prefix),
		getSession:           strings.ReplaceAll(getSessionSQLite, prefixMarker, prefix),
		sweepExpiredSessions: strings.ReplaceAll(sweepExpiredSessionsSQLite, prefixMarker, prefix),
		upsertSession:        strings.ReplaceAll(upsertSessionSQLite, prefixMarker, prefix),
	}
}

// timeText renders a time argument as the text this engine stores timestamps as.
//
// This engine has no date type: a DATETIME column holds text, and a comparison
// between two of them compares two strings. What a driver writes for a bound
// time.Time is Go's own rendering of it, whose leading characters happen to be
// the stored shape — but only while the value is UTC. A time carrying any other
// zone puts its own wall clock in those leading characters, so every window
// comparison is off by that offset, silently, and only for the callers whose
// clock is not UTC.
//
// Converting here is what makes the bound text the stored shape by
// construction rather than by accident, whatever zone the caller's time
// carries. The layout is whole seconds, which is what CURRENT_TIMESTAMP writes,
// so a bound value and a stored one are one shape rather than two that sort
// alike — which does mean a sub-second time bound here is stored truncated to
// the second on this engine.
func timeText(t time.Time) string {
	return t.UTC().Format("2006-01-02 15:04:05")
}

// DeleteSession runs the :execrows query against sqlite.
func (q *sqliteQueries) DeleteSession(ctx context.Context, db DBTX, arg DeleteSessionParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.deleteSession,
		arg.Challenge,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// GetSession runs the :one query against sqlite.
func (q *sqliteQueries) GetSession(ctx context.Context, db DBTX, arg GetSessionParams) (GetSessionRow, error) {
	row := db.QueryRowContext(ctx, q.getSession,
		arg.Challenge,
	)

	var i GetSessionRow

	err := row.Scan(
		&i.SessionData,
		&i.ExpiresAt,
	)

	return i, err
}

// SweepExpiredSessions runs the :execrows query against sqlite.
func (q *sqliteQueries) SweepExpiredSessions(ctx context.Context, db DBTX) (int64, error) {
	result, err := db.ExecContext(ctx, q.sweepExpiredSessions)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// UpsertSession runs the :exec query against sqlite.
func (q *sqliteQueries) UpsertSession(ctx context.Context, db DBTX, arg UpsertSessionParams) error {
	_, err := db.ExecContext(ctx, q.upsertSession,
		arg.Challenge,
		arg.SessionData,
		timeText(arg.ExpiresAt),
	)

	return err
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		Challenge string
	}(DeleteSessionParams{})
	_ = struct {
		Challenge string
	}(GetSessionParams{})
	_ = struct {
		SessionData []byte
		ExpiresAt   time.Time
	}(GetSessionRow{})
	_ = struct {
		Challenge   string
		SessionData []byte
		ExpiresAt   time.Time
	}(UpsertSessionParams{})
)
