-- Code generated by github.com/primandproper/platform-go/v14/outbox/internal/queriesgen. DO NOT EDIT.

-- name: InsertOutboxMessage :exec
INSERT INTO outbox_messages (
	id,
	topic,
	partition_key,
	payload,
	created_at,
	next_attempt
) VALUES (
	sqlc.arg(id),
	sqlc.arg(topic),
	sqlc.arg(partition_key),
	sqlc.arg(payload),
	sqlc.arg(created_at),
	sqlc.arg(created_at)
);

-- name: SelectClaimableOutboxMessages :many
SELECT m.id
FROM outbox_messages AS m
WHERE m.published_at IS NULL
	AND m.quarantined_at IS NULL
	AND m.next_attempt <= sqlc.arg(now)
	AND (m.claimed_until IS NULL OR m.claimed_until <= sqlc.arg(lease_expired_by))
	AND (m.partition_key = '' OR NOT EXISTS (
		SELECT 1
		FROM outbox_messages AS prior
		WHERE prior.partition_key = m.partition_key
			AND prior.published_at IS NULL
			AND prior.quarantined_at IS NULL
			AND (prior.created_at < m.created_at
				OR (prior.created_at = m.created_at AND prior.id < m.id))
	))
ORDER BY m.created_at, m.id
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: SelectClaimableOutboxMessagesSkipLocked :many
SELECT m.id
FROM outbox_messages AS m
WHERE m.published_at IS NULL
	AND m.quarantined_at IS NULL
	AND m.next_attempt <= sqlc.arg(now)
	AND (m.claimed_until IS NULL OR m.claimed_until <= sqlc.arg(lease_expired_by))
	AND (m.partition_key = '' OR NOT EXISTS (
		SELECT 1
		FROM outbox_messages AS prior
		WHERE prior.partition_key = m.partition_key
			AND prior.published_at IS NULL
			AND prior.quarantined_at IS NULL
			AND (prior.created_at < m.created_at
				OR (prior.created_at = m.created_at AND prior.id < m.id))
	))
ORDER BY m.created_at, m.id
LIMIT COALESCE(sqlc.narg(result_limit), 50)
FOR UPDATE SKIP LOCKED;

-- name: ClaimOutboxMessages :exec
UPDATE outbox_messages SET
	claimed_until = sqlc.arg(claimed_until),
	claimed_by = sqlc.arg(claimed_by),
	attempts = attempts + 1
WHERE published_at IS NULL
	AND quarantined_at IS NULL
	AND next_attempt <= sqlc.arg(now)
	AND (claimed_until IS NULL OR claimed_until <= sqlc.arg(lease_expired_by))
	AND id = ANY(sqlc.arg(ids)::text[]);

-- name: FetchClaimedOutboxMessages :many
SELECT
	id,
	topic,
	partition_key,
	payload,
	attempts
FROM outbox_messages
WHERE claimed_by = sqlc.arg(claimed_by)
	AND id = ANY(sqlc.arg(ids)::text[])
ORDER BY created_at, id;

-- name: MarkOutboxMessagesPublished :execrows
UPDATE outbox_messages SET
	published_at = sqlc.arg(published_at),
	claimed_until = NULL,
	claimed_by = NULL,
	last_error = NULL
WHERE claimed_by = sqlc.arg(held_by)
	AND id = ANY(sqlc.arg(ids)::text[]);

-- name: RecordOutboxMessageFailure :execrows
UPDATE outbox_messages SET
	claimed_until = sqlc.narg(claimed_until),
	claimed_by = sqlc.narg(claimed_by),
	next_attempt = sqlc.arg(next_attempt),
	last_error = sqlc.narg(last_error),
	quarantined_at = sqlc.narg(quarantined_at)
WHERE id = sqlc.arg(id)
	AND claimed_by = sqlc.arg(held_by);

-- name: SelectQuarantinedOutboxMessages :many
SELECT
	outbox_messages.id,
	outbox_messages.topic,
	outbox_messages.partition_key,
	outbox_messages.created_at,
	outbox_messages.quarantined_at,
	outbox_messages.attempts,
	outbox_messages.last_error
FROM outbox_messages
WHERE outbox_messages.quarantined_at IS NOT NULL
ORDER BY outbox_messages.quarantined_at ASC, outbox_messages.id ASC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: ReleaseQuarantinedOutboxMessages :execrows
UPDATE outbox_messages SET
	quarantined_at = NULL,
	next_attempt = sqlc.arg(next_attempt)
WHERE quarantined_at IS NOT NULL
	AND id = ANY(sqlc.arg(ids)::text[]);

-- name: OutboxBacklog :one
SELECT
	COUNT(*) AS depth,
	(
		SELECT queued.created_at
		FROM outbox_messages AS queued
		WHERE queued.published_at IS NULL
			AND queued.quarantined_at IS NULL
		ORDER BY queued.created_at ASC
		LIMIT 1
	) AS oldest
FROM outbox_messages
WHERE outbox_messages.published_at IS NULL
	AND outbox_messages.quarantined_at IS NULL
GROUP BY outbox_messages.quarantined_at;

-- name: ReapPublishedOutboxMessages :execrows
DELETE FROM outbox_messages
WHERE id IN (
	SELECT doomed.id
	FROM outbox_messages AS doomed
	WHERE doomed.published_at IS NOT NULL
		AND doomed.published_at <= sqlc.arg(before)
	ORDER BY doomed.published_at ASC
	LIMIT sqlc.arg(result_limit)
	FOR UPDATE SKIP LOCKED
);

-- name: SelectReapableQuarantinedOutboxMessages :many
SELECT
	outbox_messages.id,
	outbox_messages.last_error
FROM outbox_messages
WHERE outbox_messages.quarantined_at IS NOT NULL
	AND outbox_messages.quarantined_at <= sqlc.arg(before)
ORDER BY outbox_messages.quarantined_at ASC, outbox_messages.id ASC
LIMIT COALESCE(sqlc.narg(result_limit), 50);

-- name: ReapQuarantinedOutboxMessages :execrows
DELETE FROM outbox_messages
WHERE id IN (
	SELECT doomed.id
	FROM outbox_messages AS doomed
	WHERE doomed.quarantined_at IS NOT NULL
		AND doomed.quarantined_at <= sqlc.arg(before)
	ORDER BY doomed.quarantined_at ASC, doomed.id ASC
	LIMIT sqlc.arg(result_limit)
	FOR UPDATE SKIP LOCKED
);
