CREATE TABLE IF NOT EXISTS operations (
    id               VARBINARY(512) NOT NULL PRIMARY KEY,
    kind             VARBINARY(128) NOT NULL,
    state            VARCHAR(16)    NOT NULL,
    scope            VARCHAR(255)   NOT NULL,
    request          MEDIUMBLOB,
    units_total      INT,
    units_done       INT            NOT NULL DEFAULT 0,
    progress_unit    VARCHAR(1024)  NOT NULL DEFAULT '',
    progress_count   BIGINT         NOT NULL DEFAULT 0,
    count_label      TEXT           NOT NULL,
    progress_message VARCHAR(1024)  NOT NULL DEFAULT '',
    result_uri       TEXT           NOT NULL,
    result_detail    BLOB,
    error_code       TEXT           NOT NULL,
    error_message    VARCHAR(1024)  NOT NULL DEFAULT '',
    error_retryable  BOOLEAN        NOT NULL DEFAULT FALSE,
    revision         BIGINT         NOT NULL DEFAULT 1,
    attempts         INT            NOT NULL DEFAULT 0,
    cancel_requested BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at       DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_updated_at  DATETIME(6),
    archived_at      DATETIME(6),
    started_at       DATETIME(6),
    finished_at      DATETIME(6),
    claimed_until    DATETIME(6)    NOT NULL DEFAULT '1970-01-01 00:00:00',
    KEY operations_active_idx (state, created_at, claimed_until),
    KEY operations_scope_idx (scope, kind, state, id),
    KEY operations_reap_idx (state, finished_at)
);

