// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package outboxdb

import (
	"context"
	"strings"
	"time"
)

const claimOutboxMessagesPostgreSQL = `UPDATE {{prefix}}outbox_messages SET
	claimed_until = $1,
	claimed_by = $2,
	attempts = attempts + 1
WHERE published_at IS NULL
	AND quarantined_at IS NULL
	AND next_attempt <= $3
	AND (claimed_until IS NULL OR claimed_until <= $4)
	AND id = ANY($5::text[])`

const fetchClaimedOutboxMessagesPostgreSQL = `SELECT
	id,
	topic,
	partition_key,
	payload,
	attempts
FROM {{prefix}}outbox_messages
WHERE claimed_by = $1
	AND id = ANY($2::text[])
ORDER BY created_at, id`

const insertOutboxMessagePostgreSQL = `
INSERT INTO {{prefix}}outbox_messages (
	id,
	topic,
	partition_key,
	payload,
	created_at,
	next_attempt
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$5
)`

const markOutboxMessagesPublishedPostgreSQL = `UPDATE {{prefix}}outbox_messages SET
	published_at = $1,
	claimed_until = NULL,
	claimed_by = NULL,
	last_error = NULL
WHERE claimed_by = $2
	AND id = ANY($3::text[])`

const outboxBacklogPostgreSQL = `SELECT
	COUNT(*) AS depth,
	(
		SELECT queued.created_at
		FROM {{prefix}}outbox_messages AS queued
		WHERE queued.published_at IS NULL
			AND queued.quarantined_at IS NULL
		ORDER BY queued.created_at ASC
		LIMIT 1
	) AS oldest
FROM {{prefix}}outbox_messages
WHERE {{prefix}}outbox_messages.published_at IS NULL
	AND {{prefix}}outbox_messages.quarantined_at IS NULL
GROUP BY {{prefix}}outbox_messages.quarantined_at`

const reapPublishedOutboxMessagesPostgreSQL = `DELETE FROM {{prefix}}outbox_messages
WHERE id IN (
	SELECT doomed.id
	FROM {{prefix}}outbox_messages AS doomed
	WHERE doomed.published_at IS NOT NULL
		AND doomed.published_at <= $1
	ORDER BY doomed.published_at ASC
	LIMIT $2
	FOR UPDATE SKIP LOCKED
)`

const reapQuarantinedOutboxMessagesPostgreSQL = `DELETE FROM {{prefix}}outbox_messages
WHERE id IN (
	SELECT doomed.id
	FROM {{prefix}}outbox_messages AS doomed
	WHERE doomed.quarantined_at IS NOT NULL
		AND doomed.quarantined_at <= $1
	ORDER BY doomed.quarantined_at ASC, doomed.id ASC
	LIMIT $2
	FOR UPDATE SKIP LOCKED
)`

const recordOutboxMessageFailurePostgreSQL = `UPDATE {{prefix}}outbox_messages SET
	claimed_until = $1,
	claimed_by = $2,
	next_attempt = $3,
	last_error = $4,
	quarantined_at = $5
WHERE id = $6
	AND claimed_by = $7`

const releaseQuarantinedOutboxMessagesPostgreSQL = `UPDATE {{prefix}}outbox_messages SET
	quarantined_at = NULL,
	next_attempt = $1
WHERE quarantined_at IS NOT NULL
	AND id = ANY($2::text[])`

const selectClaimableOutboxMessagesPostgreSQL = `SELECT m.id
FROM {{prefix}}outbox_messages AS m
WHERE m.published_at IS NULL
	AND m.quarantined_at IS NULL
	AND m.next_attempt <= $1
	AND (m.claimed_until IS NULL OR m.claimed_until <= $2)
	AND (m.partition_key = '' OR NOT EXISTS (
		SELECT 1
		FROM {{prefix}}outbox_messages AS prior
		WHERE prior.partition_key = m.partition_key
			AND prior.published_at IS NULL
			AND prior.quarantined_at IS NULL
			AND (prior.created_at < m.created_at
				OR (prior.created_at = m.created_at AND prior.id < m.id))
	))
ORDER BY m.created_at, m.id
LIMIT COALESCE($3, 50)`

const selectClaimableOutboxMessagesSkipLockedPostgreSQL = `SELECT m.id
FROM {{prefix}}outbox_messages AS m
WHERE m.published_at IS NULL
	AND m.quarantined_at IS NULL
	AND m.next_attempt <= $1
	AND (m.claimed_until IS NULL OR m.claimed_until <= $2)
	AND (m.partition_key = '' OR NOT EXISTS (
		SELECT 1
		FROM {{prefix}}outbox_messages AS prior
		WHERE prior.partition_key = m.partition_key
			AND prior.published_at IS NULL
			AND prior.quarantined_at IS NULL
			AND (prior.created_at < m.created_at
				OR (prior.created_at = m.created_at AND prior.id < m.id))
	))
ORDER BY m.created_at, m.id
LIMIT COALESCE($3, 50)
FOR UPDATE SKIP LOCKED`

const selectQuarantinedOutboxMessagesPostgreSQL = `SELECT
	{{prefix}}outbox_messages.id,
	{{prefix}}outbox_messages.topic,
	{{prefix}}outbox_messages.partition_key,
	{{prefix}}outbox_messages.created_at,
	{{prefix}}outbox_messages.quarantined_at,
	{{prefix}}outbox_messages.attempts,
	{{prefix}}outbox_messages.last_error
FROM {{prefix}}outbox_messages
WHERE {{prefix}}outbox_messages.quarantined_at IS NOT NULL
ORDER BY {{prefix}}outbox_messages.quarantined_at ASC, {{prefix}}outbox_messages.id ASC
LIMIT COALESCE($1, 50)`

const selectReapableQuarantinedOutboxMessagesPostgreSQL = `SELECT
	{{prefix}}outbox_messages.id,
	{{prefix}}outbox_messages.last_error
FROM {{prefix}}outbox_messages
WHERE {{prefix}}outbox_messages.quarantined_at IS NOT NULL
	AND {{prefix}}outbox_messages.quarantined_at <= $1
ORDER BY {{prefix}}outbox_messages.quarantined_at ASC, {{prefix}}outbox_messages.id ASC
LIMIT COALESCE($2, 50)`

// postgresqlQueries answers every query in Querier against postgresql.
type postgresqlQueries struct {
	claimOutboxMessages                     string
	fetchClaimedOutboxMessages              string
	insertOutboxMessage                     string
	markOutboxMessagesPublished             string
	outboxBacklog                           string
	reapPublishedOutboxMessages             string
	reapQuarantinedOutboxMessages           string
	recordOutboxMessageFailure              string
	releaseQuarantinedOutboxMessages        string
	selectClaimableOutboxMessages           string
	selectClaimableOutboxMessagesSkipLocked string
	selectQuarantinedOutboxMessages         string
	selectReapableQuarantinedOutboxMessages string
}

// newPostgreSQL returns the postgresql querier with prefix substituted into every
// table name the analyzer identified.
func newPostgreSQL(prefix string) *postgresqlQueries {
	return &postgresqlQueries{
		claimOutboxMessages:                     strings.ReplaceAll(claimOutboxMessagesPostgreSQL, prefixMarker, prefix),
		fetchClaimedOutboxMessages:              strings.ReplaceAll(fetchClaimedOutboxMessagesPostgreSQL, prefixMarker, prefix),
		insertOutboxMessage:                     strings.ReplaceAll(insertOutboxMessagePostgreSQL, prefixMarker, prefix),
		markOutboxMessagesPublished:             strings.ReplaceAll(markOutboxMessagesPublishedPostgreSQL, prefixMarker, prefix),
		outboxBacklog:                           strings.ReplaceAll(outboxBacklogPostgreSQL, prefixMarker, prefix),
		reapPublishedOutboxMessages:             strings.ReplaceAll(reapPublishedOutboxMessagesPostgreSQL, prefixMarker, prefix),
		reapQuarantinedOutboxMessages:           strings.ReplaceAll(reapQuarantinedOutboxMessagesPostgreSQL, prefixMarker, prefix),
		recordOutboxMessageFailure:              strings.ReplaceAll(recordOutboxMessageFailurePostgreSQL, prefixMarker, prefix),
		releaseQuarantinedOutboxMessages:        strings.ReplaceAll(releaseQuarantinedOutboxMessagesPostgreSQL, prefixMarker, prefix),
		selectClaimableOutboxMessages:           strings.ReplaceAll(selectClaimableOutboxMessagesPostgreSQL, prefixMarker, prefix),
		selectClaimableOutboxMessagesSkipLocked: strings.ReplaceAll(selectClaimableOutboxMessagesSkipLockedPostgreSQL, prefixMarker, prefix),
		selectQuarantinedOutboxMessages:         strings.ReplaceAll(selectQuarantinedOutboxMessagesPostgreSQL, prefixMarker, prefix),
		selectReapableQuarantinedOutboxMessages: strings.ReplaceAll(selectReapableQuarantinedOutboxMessagesPostgreSQL, prefixMarker, prefix),
	}
}

// ClaimOutboxMessages runs the :exec query against postgresql.
func (q *postgresqlQueries) ClaimOutboxMessages(ctx context.Context, db DBTX, arg ClaimOutboxMessagesParams) error {
	_, err := db.ExecContext(ctx, q.claimOutboxMessages,
		arg.ClaimedUntil,
		arg.ClaimedBy,
		arg.Now,
		arg.LeaseExpiredBy,
		arg.IDs,
	)

	return err
}

// FetchClaimedOutboxMessages runs the :many query against postgresql.
func (q *postgresqlQueries) FetchClaimedOutboxMessages(ctx context.Context, db DBTX, arg FetchClaimedOutboxMessagesParams) ([]FetchClaimedOutboxMessagesRow, error) {
	rows, err := db.QueryContext(ctx, q.fetchClaimedOutboxMessages,
		arg.ClaimedBy,
		arg.IDs,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []FetchClaimedOutboxMessagesRow

	for rows.Next() {
		var i FetchClaimedOutboxMessagesRow

		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.PartitionKey,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// InsertOutboxMessage runs the :exec query against postgresql.
func (q *postgresqlQueries) InsertOutboxMessage(ctx context.Context, db DBTX, arg InsertOutboxMessageParams) error {
	_, err := db.ExecContext(ctx, q.insertOutboxMessage,
		arg.ID,
		arg.Topic,
		arg.PartitionKey,
		arg.Payload,
		arg.CreatedAt,
	)

	return err
}

// MarkOutboxMessagesPublished runs the :execrows query against postgresql.
func (q *postgresqlQueries) MarkOutboxMessagesPublished(ctx context.Context, db DBTX, arg MarkOutboxMessagesPublishedParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.markOutboxMessagesPublished,
		arg.PublishedAt,
		arg.HeldBy,
		arg.IDs,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// OutboxBacklog runs the :one query against postgresql.
func (q *postgresqlQueries) OutboxBacklog(ctx context.Context, db DBTX) (OutboxBacklogRow, error) {
	row := db.QueryRowContext(ctx, q.outboxBacklog)

	var i OutboxBacklogRow

	err := row.Scan(
		&i.Depth,
		&i.Oldest,
	)

	return i, err
}

// ReapPublishedOutboxMessages runs the :execrows query against postgresql.
func (q *postgresqlQueries) ReapPublishedOutboxMessages(ctx context.Context, db DBTX, arg ReapPublishedOutboxMessagesParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.reapPublishedOutboxMessages,
		arg.Before,
		arg.ResultLimit,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// ReapQuarantinedOutboxMessages runs the :execrows query against postgresql.
func (q *postgresqlQueries) ReapQuarantinedOutboxMessages(ctx context.Context, db DBTX, arg ReapQuarantinedOutboxMessagesParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.reapQuarantinedOutboxMessages,
		arg.Before,
		arg.ResultLimit,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// RecordOutboxMessageFailure runs the :execrows query against postgresql.
func (q *postgresqlQueries) RecordOutboxMessageFailure(ctx context.Context, db DBTX, arg RecordOutboxMessageFailureParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.recordOutboxMessageFailure,
		arg.ClaimedUntil,
		arg.ClaimedBy,
		arg.NextAttempt,
		arg.LastError,
		arg.QuarantinedAt,
		arg.ID,
		arg.HeldBy,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// ReleaseQuarantinedOutboxMessages runs the :execrows query against postgresql.
func (q *postgresqlQueries) ReleaseQuarantinedOutboxMessages(ctx context.Context, db DBTX, arg ReleaseQuarantinedOutboxMessagesParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.releaseQuarantinedOutboxMessages,
		arg.NextAttempt,
		arg.IDs,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SelectClaimableOutboxMessages runs the :many query against postgresql.
func (q *postgresqlQueries) SelectClaimableOutboxMessages(ctx context.Context, db DBTX, arg SelectClaimableOutboxMessagesParams) ([]SelectClaimableOutboxMessagesRow, error) {
	rows, err := db.QueryContext(ctx, q.selectClaimableOutboxMessages,
		arg.Now,
		arg.LeaseExpiredBy,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []SelectClaimableOutboxMessagesRow

	for rows.Next() {
		var i SelectClaimableOutboxMessagesRow

		if err := rows.Scan(
			&i.ID,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SelectClaimableOutboxMessagesSkipLocked runs the :many query against postgresql.
func (q *postgresqlQueries) SelectClaimableOutboxMessagesSkipLocked(ctx context.Context, db DBTX, arg SelectClaimableOutboxMessagesSkipLockedParams) ([]SelectClaimableOutboxMessagesSkipLockedRow, error) {
	rows, err := db.QueryContext(ctx, q.selectClaimableOutboxMessagesSkipLocked,
		arg.Now,
		arg.LeaseExpiredBy,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []SelectClaimableOutboxMessagesSkipLockedRow

	for rows.Next() {
		var i SelectClaimableOutboxMessagesSkipLockedRow

		if err := rows.Scan(
			&i.ID,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SelectQuarantinedOutboxMessages runs the :many query against postgresql.
func (q *postgresqlQueries) SelectQuarantinedOutboxMessages(ctx context.Context, db DBTX, arg SelectQuarantinedOutboxMessagesParams) ([]SelectQuarantinedOutboxMessagesRow, error) {
	rows, err := db.QueryContext(ctx, q.selectQuarantinedOutboxMessages,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []SelectQuarantinedOutboxMessagesRow

	for rows.Next() {
		var i SelectQuarantinedOutboxMessagesRow

		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.PartitionKey,
			&i.CreatedAt,
			&i.QuarantinedAt,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SelectReapableQuarantinedOutboxMessages runs the :many query against postgresql.
func (q *postgresqlQueries) SelectReapableQuarantinedOutboxMessages(ctx context.Context, db DBTX, arg SelectReapableQuarantinedOutboxMessagesParams) ([]SelectReapableQuarantinedOutboxMessagesRow, error) {
	rows, err := db.QueryContext(ctx, q.selectReapableQuarantinedOutboxMessages,
		arg.Before,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []SelectReapableQuarantinedOutboxMessagesRow

	for rows.Next() {
		var i SelectReapableQuarantinedOutboxMessagesRow

		if err := rows.Scan(
			&i.ID,
			&i.LastError,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ClaimedUntil   *time.Time
		ClaimedBy      *string
		Now            time.Time
		LeaseExpiredBy *time.Time
		IDs            []string
	}(ClaimOutboxMessagesParams{})
	_ = struct {
		ClaimedBy *string
		IDs       []string
	}(FetchClaimedOutboxMessagesParams{})
	_ = struct {
		ID           string
		Topic        string
		PartitionKey string
		Payload      []byte
		Attempts     int64
	}(FetchClaimedOutboxMessagesRow{})
	_ = struct {
		ID           string
		Topic        string
		PartitionKey string
		Payload      []byte
		CreatedAt    time.Time
	}(InsertOutboxMessageParams{})
	_ = struct {
		PublishedAt *time.Time
		HeldBy      *string
		IDs         []string
	}(MarkOutboxMessagesPublishedParams{})
	_ = struct {
		Depth  int64
		Oldest time.Time
	}(OutboxBacklogRow{})
	_ = struct {
		Before      *time.Time
		ResultLimit int64
	}(ReapPublishedOutboxMessagesParams{})
	_ = struct {
		Before      *time.Time
		ResultLimit int64
	}(ReapQuarantinedOutboxMessagesParams{})
	_ = struct {
		ClaimedUntil  *time.Time
		ClaimedBy     *string
		NextAttempt   time.Time
		LastError     *string
		QuarantinedAt *time.Time
		ID            string
		HeldBy        *string
	}(RecordOutboxMessageFailureParams{})
	_ = struct {
		NextAttempt time.Time
		IDs         []string
	}(ReleaseQuarantinedOutboxMessagesParams{})
	_ = struct {
		Now            time.Time
		LeaseExpiredBy *time.Time
		ResultLimit    int64
	}(SelectClaimableOutboxMessagesParams{})
	_ = struct {
		ID string
	}(SelectClaimableOutboxMessagesRow{})
	_ = struct {
		Now            time.Time
		LeaseExpiredBy *time.Time
		ResultLimit    int64
	}(SelectClaimableOutboxMessagesSkipLockedParams{})
	_ = struct {
		ID string
	}(SelectClaimableOutboxMessagesSkipLockedRow{})
	_ = struct {
		ResultLimit int64
	}(SelectQuarantinedOutboxMessagesParams{})
	_ = struct {
		ID            string
		Topic         string
		PartitionKey  string
		CreatedAt     time.Time
		QuarantinedAt *time.Time
		Attempts      int64
		LastError     *string
	}(SelectQuarantinedOutboxMessagesRow{})
	_ = struct {
		Before      *time.Time
		ResultLimit int64
	}(SelectReapableQuarantinedOutboxMessagesParams{})
	_ = struct {
		ID        string
		LastError *string
	}(SelectReapableQuarantinedOutboxMessagesRow{})
)
