// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package outboxdb

import (
	"context"
	"strings"
	"time"
)

const claimOutboxMessagesMySQL = `UPDATE {{prefix}}outbox_messages SET
	claimed_until = ?,
	claimed_by = ?,
	attempts = attempts + 1
WHERE (claimed_until IS NULL OR claimed_until <= ?)
	AND id IN (/*SLICE:ids*/?)`

const fetchClaimedOutboxMessagesMySQL = `SELECT
	id,
	topic,
	partition_key,
	payload,
	attempts
FROM {{prefix}}outbox_messages
WHERE claimed_by = ?
	AND id IN (/*SLICE:ids*/?)
ORDER BY created_at, id`

const insertOutboxMessageMySQL = `
INSERT INTO {{prefix}}outbox_messages (
	id,
	topic,
	partition_key,
	payload,
	created_at,
	next_attempt
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?
)`

const markOutboxMessagesPublishedMySQL = `UPDATE {{prefix}}outbox_messages SET
	published_at = ?,
	claimed_until = NULL,
	claimed_by = NULL,
	last_error = NULL
WHERE claimed_by = ?
	AND id IN (/*SLICE:ids*/?)`

const outboxBacklogMySQL = `SELECT
	COUNT(*) AS depth,
	(
		SELECT queued.created_at
		FROM {{prefix}}outbox_messages AS queued
		WHERE queued.published_at IS NULL
			AND queued.quarantined = FALSE
		ORDER BY queued.created_at ASC
		LIMIT 1
	) AS oldest
FROM {{prefix}}outbox_messages
WHERE {{prefix}}outbox_messages.published_at IS NULL
	AND {{prefix}}outbox_messages.quarantined = FALSE
GROUP BY {{prefix}}outbox_messages.quarantined`

const reapPublishedOutboxMessagesMySQL = `DELETE FROM {{prefix}}outbox_messages
WHERE published_at IS NOT NULL
	AND published_at <= ?
ORDER BY published_at ASC
LIMIT ?`

const recordOutboxMessageFailureMySQL = `UPDATE {{prefix}}outbox_messages SET
	claimed_until = ?,
	claimed_by = ?,
	next_attempt = ?,
	last_error = ?,
	quarantined = ?
WHERE id = ?
	AND claimed_by = ?`

const selectClaimableOutboxMessagesMySQL = `SELECT m.id
FROM {{prefix}}outbox_messages AS m
WHERE m.published_at IS NULL
	AND m.quarantined = FALSE
	AND m.next_attempt <= ?
	AND (m.claimed_until IS NULL OR m.claimed_until <= ?)
	AND (m.partition_key = '' OR NOT EXISTS (
		SELECT 1
		FROM {{prefix}}outbox_messages AS prior
		WHERE prior.partition_key = m.partition_key
			AND prior.published_at IS NULL
			AND prior.quarantined = FALSE
			AND (prior.created_at < m.created_at
				OR (prior.created_at = m.created_at AND prior.id < m.id))
	))
ORDER BY m.created_at, m.id
LIMIT ?`

const selectClaimableOutboxMessagesSkipLockedMySQL = `SELECT m.id
FROM {{prefix}}outbox_messages AS m
WHERE m.published_at IS NULL
	AND m.quarantined = FALSE
	AND m.next_attempt <= ?
	AND (m.claimed_until IS NULL OR m.claimed_until <= ?)
	AND (m.partition_key = '' OR NOT EXISTS (
		SELECT 1
		FROM {{prefix}}outbox_messages AS prior
		WHERE prior.partition_key = m.partition_key
			AND prior.published_at IS NULL
			AND prior.quarantined = FALSE
			AND (prior.created_at < m.created_at
				OR (prior.created_at = m.created_at AND prior.id < m.id))
	))
ORDER BY m.created_at, m.id
LIMIT ?
FOR UPDATE SKIP LOCKED`

// mysqlQueries answers every query in Querier against mysql.
type mysqlQueries struct {
	claimOutboxMessages                     string
	fetchClaimedOutboxMessages              string
	insertOutboxMessage                     string
	markOutboxMessagesPublished             string
	outboxBacklog                           string
	reapPublishedOutboxMessages             string
	recordOutboxMessageFailure              string
	selectClaimableOutboxMessages           string
	selectClaimableOutboxMessagesSkipLocked string
}

// newMySQL returns the mysql querier with prefix substituted into every
// table name the analyzer identified.
func newMySQL(prefix string) *mysqlQueries {
	return &mysqlQueries{
		claimOutboxMessages:                     strings.ReplaceAll(claimOutboxMessagesMySQL, prefixMarker, prefix),
		fetchClaimedOutboxMessages:              strings.ReplaceAll(fetchClaimedOutboxMessagesMySQL, prefixMarker, prefix),
		insertOutboxMessage:                     strings.ReplaceAll(insertOutboxMessageMySQL, prefixMarker, prefix),
		markOutboxMessagesPublished:             strings.ReplaceAll(markOutboxMessagesPublishedMySQL, prefixMarker, prefix),
		outboxBacklog:                           strings.ReplaceAll(outboxBacklogMySQL, prefixMarker, prefix),
		reapPublishedOutboxMessages:             strings.ReplaceAll(reapPublishedOutboxMessagesMySQL, prefixMarker, prefix),
		recordOutboxMessageFailure:              strings.ReplaceAll(recordOutboxMessageFailureMySQL, prefixMarker, prefix),
		selectClaimableOutboxMessages:           strings.ReplaceAll(selectClaimableOutboxMessagesMySQL, prefixMarker, prefix),
		selectClaimableOutboxMessagesSkipLocked: strings.ReplaceAll(selectClaimableOutboxMessagesSkipLockedMySQL, prefixMarker, prefix),
	}
}

// ClaimOutboxMessages runs the :exec query against mysql.
func (q *mysqlQueries) ClaimOutboxMessages(ctx context.Context, db DBTX, arg ClaimOutboxMessagesParams) error {
	query := q.claimOutboxMessages

	args := make([]any, 0, 3+len(arg.IDs))

	args = append(args, arg.ClaimedUntil)

	args = append(args, arg.ClaimedBy)

	args = append(args, arg.LeaseExpiredBy)

	query = strings.Replace(query, "/*SLICE:ids*/?", slicePlaceholders("?", len(arg.IDs)), 1)

	for _, v := range arg.IDs {
		args = append(args, v)
	}

	_, err := db.ExecContext(ctx, query, args...)

	return err
}

// FetchClaimedOutboxMessages runs the :many query against mysql.
func (q *mysqlQueries) FetchClaimedOutboxMessages(ctx context.Context, db DBTX, arg FetchClaimedOutboxMessagesParams) ([]FetchClaimedOutboxMessagesRow, error) {
	query := q.fetchClaimedOutboxMessages

	args := make([]any, 0, 1+len(arg.IDs))

	args = append(args, arg.ClaimedBy)

	query = strings.Replace(query, "/*SLICE:ids*/?", slicePlaceholders("?", len(arg.IDs)), 1)

	for _, v := range arg.IDs {
		args = append(args, v)
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []FetchClaimedOutboxMessagesRow

	for rows.Next() {
		var i FetchClaimedOutboxMessagesRow

		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.PartitionKey,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// InsertOutboxMessage runs the :exec query against mysql.
func (q *mysqlQueries) InsertOutboxMessage(ctx context.Context, db DBTX, arg InsertOutboxMessageParams) error {
	_, err := db.ExecContext(ctx, q.insertOutboxMessage,
		arg.ID,
		arg.Topic,
		arg.PartitionKey,
		arg.Payload,
		arg.CreatedAt,
		arg.CreatedAt,
	)

	return err
}

// MarkOutboxMessagesPublished runs the :execrows query against mysql.
func (q *mysqlQueries) MarkOutboxMessagesPublished(ctx context.Context, db DBTX, arg MarkOutboxMessagesPublishedParams) (int64, error) {
	query := q.markOutboxMessagesPublished

	args := make([]any, 0, 2+len(arg.IDs))

	args = append(args, arg.PublishedAt)

	args = append(args, arg.HeldBy)

	query = strings.Replace(query, "/*SLICE:ids*/?", slicePlaceholders("?", len(arg.IDs)), 1)

	for _, v := range arg.IDs {
		args = append(args, v)
	}

	result, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// OutboxBacklog runs the :one query against mysql.
func (q *mysqlQueries) OutboxBacklog(ctx context.Context, db DBTX) (OutboxBacklogRow, error) {
	row := db.QueryRowContext(ctx, q.outboxBacklog)

	var i OutboxBacklogRow

	err := row.Scan(
		&i.Depth,
		&i.Oldest,
	)

	return i, err
}

// ReapPublishedOutboxMessages runs the :execrows query against mysql.
func (q *mysqlQueries) ReapPublishedOutboxMessages(ctx context.Context, db DBTX, arg ReapPublishedOutboxMessagesParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.reapPublishedOutboxMessages,
		arg.Before,
		arg.ResultLimit,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// RecordOutboxMessageFailure runs the :execrows query against mysql.
func (q *mysqlQueries) RecordOutboxMessageFailure(ctx context.Context, db DBTX, arg RecordOutboxMessageFailureParams) (int64, error) {
	result, err := db.ExecContext(ctx, q.recordOutboxMessageFailure,
		arg.ClaimedUntil,
		arg.ClaimedBy,
		arg.NextAttempt,
		arg.LastError,
		arg.Quarantined,
		arg.ID,
		arg.HeldBy,
	)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// SelectClaimableOutboxMessages runs the :many query against mysql.
func (q *mysqlQueries) SelectClaimableOutboxMessages(ctx context.Context, db DBTX, arg SelectClaimableOutboxMessagesParams) ([]SelectClaimableOutboxMessagesRow, error) {
	rows, err := db.QueryContext(ctx, q.selectClaimableOutboxMessages,
		arg.Now,
		arg.LeaseExpiredBy,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []SelectClaimableOutboxMessagesRow

	for rows.Next() {
		var i SelectClaimableOutboxMessagesRow

		if err := rows.Scan(
			&i.ID,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// SelectClaimableOutboxMessagesSkipLocked runs the :many query against mysql.
func (q *mysqlQueries) SelectClaimableOutboxMessagesSkipLocked(ctx context.Context, db DBTX, arg SelectClaimableOutboxMessagesSkipLockedParams) ([]SelectClaimableOutboxMessagesSkipLockedRow, error) {
	rows, err := db.QueryContext(ctx, q.selectClaimableOutboxMessagesSkipLocked,
		arg.Now,
		arg.LeaseExpiredBy,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}

	defer func() { _ = rows.Close() }()

	var items []SelectClaimableOutboxMessagesSkipLockedRow

	for rows.Next() {
		var i SelectClaimableOutboxMessagesSkipLockedRow

		if err := rows.Scan(
			&i.ID,
		); err != nil {
			return nil, err
		}

		items = append(items, i)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return items, nil
}

// Shape assertions.
//
// Each conversion below compiles only if the shared type still has exactly
// these fields, with these types, in this order — which is what makes a
// disagreement between dialects a compile error here rather than a
// transposition at run time.
var (
	_ = struct {
		ClaimedUntil   *time.Time
		ClaimedBy      *string
		LeaseExpiredBy *time.Time
		IDs            []string
	}(ClaimOutboxMessagesParams{})
	_ = struct {
		ClaimedBy *string
		IDs       []string
	}(FetchClaimedOutboxMessagesParams{})
	_ = struct {
		ID           string
		Topic        string
		PartitionKey string
		Payload      []byte
		Attempts     int64
	}(FetchClaimedOutboxMessagesRow{})
	_ = struct {
		ID           string
		Topic        string
		PartitionKey string
		Payload      []byte
		CreatedAt    time.Time
	}(InsertOutboxMessageParams{})
	_ = struct {
		PublishedAt *time.Time
		HeldBy      *string
		IDs         []string
	}(MarkOutboxMessagesPublishedParams{})
	_ = struct {
		Depth  int64
		Oldest time.Time
	}(OutboxBacklogRow{})
	_ = struct {
		Before      *time.Time
		ResultLimit int64
	}(ReapPublishedOutboxMessagesParams{})
	_ = struct {
		ClaimedUntil *time.Time
		ClaimedBy    *string
		NextAttempt  time.Time
		LastError    *string
		Quarantined  bool
		ID           string
		HeldBy       *string
	}(RecordOutboxMessageFailureParams{})
	_ = struct {
		Now            time.Time
		LeaseExpiredBy *time.Time
		ResultLimit    int64
	}(SelectClaimableOutboxMessagesParams{})
	_ = struct {
		ID string
	}(SelectClaimableOutboxMessagesRow{})
	_ = struct {
		Now            time.Time
		LeaseExpiredBy *time.Time
		ResultLimit    int64
	}(SelectClaimableOutboxMessagesSkipLockedParams{})
	_ = struct {
		ID string
	}(SelectClaimableOutboxMessagesSkipLockedRow{})
)
