// Code generated by github.com/primandproper/sqlc-gen-unison. DO NOT EDIT.
//
// sqlc:   v1.31.1
// unison: v0.3.0

package outboxdb

import (
	"time"
)

// ClaimOutboxMessagesParams are the arguments to ClaimOutboxMessages.
type ClaimOutboxMessagesParams struct {
	ClaimedUntil   *time.Time
	ClaimedBy      *string
	LeaseExpiredBy *time.Time
	IDs            []string
}

// FetchClaimedOutboxMessagesParams are the arguments to FetchClaimedOutboxMessages.
type FetchClaimedOutboxMessagesParams struct {
	ClaimedBy *string
	IDs       []string
}

// FetchClaimedOutboxMessagesRow is one row of FetchClaimedOutboxMessages's result.
type FetchClaimedOutboxMessagesRow struct {
	ID           string
	Topic        string
	PartitionKey string
	Payload      []byte
	Attempts     int64
}

// InsertOutboxMessageParams are the arguments to InsertOutboxMessage.
type InsertOutboxMessageParams struct {
	ID           string
	Topic        string
	PartitionKey string
	Payload      []byte
	CreatedAt    time.Time
}

// MarkOutboxMessagesPublishedParams are the arguments to MarkOutboxMessagesPublished.
type MarkOutboxMessagesPublishedParams struct {
	PublishedAt *time.Time
	IDs         []string
}

// OutboxBacklogRow is one row of OutboxBacklog's result.
type OutboxBacklogRow struct {
	Depth  int64
	Oldest time.Time
}

// ReapPublishedOutboxMessagesParams are the arguments to ReapPublishedOutboxMessages.
type ReapPublishedOutboxMessagesParams struct {
	Before      *time.Time
	ResultLimit int64
}

// RecordOutboxMessageFailureParams are the arguments to RecordOutboxMessageFailure.
type RecordOutboxMessageFailureParams struct {
	ClaimedUntil *time.Time
	ClaimedBy    *string
	NextAttempt  time.Time
	LastError    *string
	Quarantined  bool
	ID           string
}

// SelectClaimableOutboxMessagesParams are the arguments to SelectClaimableOutboxMessages.
type SelectClaimableOutboxMessagesParams struct {
	Now            time.Time
	LeaseExpiredBy *time.Time
	ResultLimit    int64
}

// SelectClaimableOutboxMessagesRow is one row of SelectClaimableOutboxMessages's result.
type SelectClaimableOutboxMessagesRow struct {
	ID string
}

// SelectClaimableOutboxMessagesSkipLockedParams are the arguments to SelectClaimableOutboxMessagesSkipLocked.
type SelectClaimableOutboxMessagesSkipLockedParams struct {
	Now            time.Time
	LeaseExpiredBy *time.Time
	ResultLimit    int64
}

// SelectClaimableOutboxMessagesSkipLockedRow is one row of SelectClaimableOutboxMessagesSkipLocked's result.
type SelectClaimableOutboxMessagesSkipLockedRow struct {
	ID string
}
